Repository sonic-net/sonic-utilities, pull requests merged in 2019-09, with the labels that each got.

#621 [fast-reboot] Check if ASIC config has changed before warm reboot
  scripts/asic_config_check
  scripts/fast-reboot
  setup.py
Labels: Enhancement, Request for 201811 Branch

#629 [neighbor_advertiser]: Change the ICMPv6 type to 135
  scripts/neighbor_advertiser
Labels: Bug, Request for 201811 Branch

#631 [warm/fast reboot] provide strict option to prevent warm reboot under certain conditions
  scripts/fast-reboot
Labels: Enhancement, Request for 201811 Branch

#627 updated "show ntp" to use cgexec when management vrf is enabled
  show/main.py
Labels: Enhancement

#633 [FastReboot]: Send SIGINT to all teamd before stop
  scripts/fast-reboot
Labels: Bug, Request for 201811 Branch, Request for 201904 Branch

#636 [config] Fix naming conflict between 'config syslog' function and 'syslog' module
  config/main.py
Labels: Bug

#637 [warm reboot] Skip ASIC config pre-check if current image does not support it
  scripts/asic_config_check
Labels: Enhancement, Request for 201811 Branch

#625 [config] Add commands to remove BGP neighbor configuration
  config/main.py
  doc/Command-Reference.md
Labels: Enhancement

#639 [warm-reboot]: Do not clean up mirror session state database
  scripts/fast-reboot
Labels: Enhancement, Request for 201811 Branch

#587 Add SSD Health CLI utility
  doc/Command-Reference.md
  setup.py
  show/main.py
  ssdutil/__init__.py
  ssdutil/main.py
Labels: Enhancement

#632 Asym PFC configuration fix
  config/main.py
Labels: Bug, Request for 201811 Branch

#650 Revert "[FastReboot]: Send SIGINT to all teamd before stop"
  scripts/fast-reboot
Labels: Request for 201811 Branch

#652 Revert "Fixed config Asym PFC CLI. (#632)"
  config/main.py
Labels: Included in 201811 Branch

#647 [config] Add '-h' and '-?' as help options to unify with show/sonic-clear cmds
  config/main.py
Labels: Enhancement, Request for 201811 Branch, Request for 201904 Branch

#654 [201811][config] Add '-h' and '-?' as help options to unify with show/sonic-clear cmds
  config/main.py
Labels: Enhancement, Included in 201811 Branch

#660 Use SIGUSR2 to stop teamd before fast-reboot
  scripts/fast-reboot
Labels: Enhancement, Request for 201811 Branch

#668 [warm/fast reboot] some service docker might have been stopped already
  scripts/fast-reboot
Labels: Bug, Request for 201811 Branch

#662 [acl_loader]: Add monitor port column in show mirror_session output
  acl_loader/main.py
Labels: Enhancement, Request for 201811 Branch

#670 [neighbor_advertiser] Verify that DIPs returned from ferret are not in device VLAN
  scripts/neighbor_advertiser
Labels: Enhancement, Request for 201811 Branch

#683 [fast reboot] kill teamd docker directly
  scripts/fast-reboot
Labels: Request for 201811 Branch
