Repository sonic-net/sonic-utilities, pull requests merged in 2019-03, with the labels that each got.

#440 show interface status <interface-name> throws error (fixes #427)
  scripts/intfutil
Labels: bug

#470 Update watermark default polling interval to 10s
  counterpoll/main.py
Labels: Request_for_201811_branch

#476 [aclshow] restore PRIO column and sort entries by priority
  scripts/aclshow
Labels: Request_for_201811_branch

#469 neighbor advertiser script
  scripts/neighbor_advertiser
  setup.py
Labels: enhancement

#484 [reboot script] add -h, -? options
  scripts/reboot
Labels: Request_for_201811_branch, enhancement

#487 [warm/fast reboot] setup control plane assistant when available
  scripts/fast-reboot
Labels: Request_for_201811_branch, enhancement

#475 Change PFC watchdog CONFIG_DB table name from PFC_WD_TABLE to PFC_WD
  pfcwd/main.py
Labels: Request_for_201811_branch

#489 [route_check] Move scripts under scripts/ directory, add to setup.py
  scripts/route_check_test.sh
  setup.py
Labels: enhancement

#486 [show ip interface] Add support for 'alias' interface naming mode
  show/main.py
Labels: enhancement

#474 Allow config shutdown and startup operations on valid PortChannel interface names
  config/main.py
Labels: Request_for_201811_branch

#492 [warm-reboot] initialize warm reboot state table before warm rebooting
  scripts/fast-reboot
Labels: Request_for_201811_branch, enhancement
