Repository sonic-net/sonic-utilities, pull requests merged in 2019-07, with the labels that each got.

#569 [PR template] Add reminder to update Command Line Reference Guide if modifying user-facing commands
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Enhancement

#560 [fast reboot] stop removing opennsl module before reboot
  scripts/fast-reboot
Labels: Request for 201811 Branch

#571 [show] Don't abort in InterfaceAliasConverter ctor if PORT table doesn't exist
  show/main.py
Labels: Bug, Request for 201811 Branch

#525 Generate interface table to have an entry for default VRF
  config/main.py
  scripts/db_migrator.py
  scripts/neighbor_advertiser
  scripts/pcmping
  show/main.py
Labels: Enhancement

#546 [Mellanox] Improve the prompt of the Mellanox sdk sniffer command.
  config/mlnx.py
Labels: Enhancement, Platform: Mellanox

#580 [acl_loader]:Fix show mirror_session error
  acl_loader/main.py
Labels: Bug

#572 [fast-reboot] Stop services after killing containers to prevent automatic restart
  scripts/fast-reboot
Labels: Enhancement, Request for 201811 Branch

#584 Fixing the expected neighbor command due to change in output format under sonic-buildimage/pull/3036
  show/main.py
Labels: Bug

#535 [sonic-utilities] Add fstrim to reboot
  scripts/reboot
Labels: Enhancement

#579 [ecnconfig] Validate input WRED parameters
  scripts/ecnconfig
Labels: Enhancement

#559 [warm-reboot] add docker upgrade --warm option and roll back support
  sonic_installer/main.py
Labels: Enhancement

#567 sfpshow: prevent 'show int trans eeprom --dom' from crashing
  scripts/sfpshow
Labels: Bug

#582 [config] Do not stop or restart dependent services when reloading config
  config/main.py
Labels: Bug

#447 show acl table command output should show binding column correctly ev…
  acl_loader/main.py
Labels: Bug

#589 Revert "show acl table command output should show binding column correctly ev…"
  acl_loader/main.py
Labels: Enhancement

#565 sonic_installer: fix read-only filesystem support for firmware update
  sonic_installer/main.py
Labels: Enhancement

#563 [portstat] Fix portstat show RX_UTIL over 100% for 100G
  scripts/portstat
  utilities_common/netstat.py
Labels: Enhancement

#545 sonic_utilities: Support for DOM Threshold values for EEPROM dump
  scripts/sfpshow
  sonic-utilities-tests/mock_tables/state_db.json
  sonic-utilities-tests/sfp_test.py
Labels: Enhancement
