Repository sonic-net/sonic-utilities, pull requests merged in 2019-11, with the labels that each got.

#592 sonic-utilities: Add support for sFlow
  config/main.py
  show/main.py
  sonic_installer/main.py
Labels: Enhancement

#728 Make configlet application script idempotent for updates.
  scripts/configlet
Labels: Request for 201811 Branch

#726 Do not start pfcwd for M0 devices
  config/main.py
Labels: Request for 201811 Branch

#634 [config]: add the vid range check for creating vlan.
  config/main.py
Labels: Enhancement

#750 [neighbor_advertiser] Adds initial support for HTTPS to neighbor advertiser
  scripts/neighbor_advertiser
Labels: Enhancement, Request for 201811 Branch

#712 [show] Add 'features' subcommand to display status for optional features
  show/main.py
Labels: Enhancement

#755 Fix a bug in idempotent check.
  scripts/configlet
Labels: Request for 201811 Branch

#746 [config] Add 'feature' subcommand
  config/main.py
Labels: Enhancement
