Repository sonic-net/sonic-utilities, pull requests merged in 2019-10, with the labels that each got.

#664 [show] Properly replace port name with alias in command output
  show/main.py
Labels: Bug, Request for 201811 Branch, Request for 201904 Branch

#689 [neighbor_advertiser] hand pick partial change from #525
  scripts/neighbor_advertiser
Labels: Bug, Included in 201811 Branch

#690 Revert "[fast reboot] kill teamd docker directly"
  scripts/fast-reboot
Labels: Request for 201811 Branch

#686 Address the 'show ipv6 interface' crash and include the missed bgp columns
  show/main.py
Labels: Bug

#669 [config]: Add hostname command to config CLI
  config/main.py
  doc/Command-Reference.md
Labels: Enhancement

#692 Fix bgp 'show' and 'clear' commands
  clear/bgp_frr_v6.py
  clear/main.py
  show/bgp_frr_v6.py
  show/main.py
Labels: Bug, Enhancement

#575 [acl-loader] egress mirror action support and action ASIC support check
  .gitignore
  acl_loader/main.py
  config/main.py
  doc/Command-Reference.md
  sonic-utilities-tests/acl_loader_test.py
  sonic-utilities-tests/aclshow_test.py
  sonic-utilities-tests/mock_tables/config_db.json
  sonic-utilities-tests/mock_tables/state_db.json
Labels: Enhancement

#703 [neighbor_advertiser]: Adapt to different mirror ACL table names
  scripts/neighbor_advertiser
Labels: Enhancement, Request for 201811 Branch

#701 [generate_dump] Make regex more specific for disabling/enabling logrotate
  scripts/generate_dump
Labels: Bug

#707 [Command Reference] Unify style and formatting; Fix organization; Other fixes
  doc/Command-Reference.md
Labels: Documentation

#708 [PR template] Add reminder to add/modify/remove unit tests as appropriate
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation

#704 [command reference] add warm reboot command document
  doc/Command-Reference.md
Labels: Documentation

#713 [warm/fast reboot] continue executing when killing docker failed
  scripts/fast-reboot
Labels: Enhancement, Request for 201811 Branch

#714 [neighbor_advertiser]: Add sleep in setting mirror session and ACL rules
  scripts/neighbor_advertiser
Labels: Enhancement, Request for 201811 Branch

#606 [config]: Flush the neighbor table when removing the router interface
  config/main.py
Labels: Enhancement
