Repository sonic-net/sonic-utilities, pull requests merged in 2019-08, with the labels that each got.

#598 [show] Add BGP neighbor info to 'show ip/ipv6 interfaces' command output
  doc/Command-Reference.md
  show/main.py
Labels: Enhancement

#596 [config]: fix the runtime error of the 'show line' command (#595)
  consutil/__init__.py
  consutil/main.py
Labels: Bug

#603 Revert "Removed 'show interfaces alias'. (#412)"
  show/main.py
Labels: Request for 201811 Branch, Request for 201904 Branch

#583 [debug][undebug] Rework of CLI for BGP
  debug/aliases.ini
  debug/main.py
  scripts/generate_dump
  undebug/aliases.ini
  undebug/main.py
Labels: Enhancement

#585 [config] Add commands to add/remove DHCP server address from a VLAN
  config/main.py
Labels: Enhancement

#604 [neighbor_advertiser] Use full vlan name for vxlan tunnel map programming
  scripts/neighbor_advertiser
Labels: Bug, Request for 201811 Branch

#605 [neighbor_advertise]: Use the existing MIRROR ACL table
  scripts/neighbor_advertiser
Labels: Enhancement, Request for 201811 Branch

#594 Read config DB for running interface(s) and display per port/interface
  show/main.py
Labels: Enhancement

#608 [fast/warm reboot] kill radv docker before stopping BGP
  scripts/fast-reboot
Labels: Bug, Request for 201811 Branch

#609 [config] Add commands for adding/removing syslog servers
  config/main.py
  doc/Command-Reference.md
Labels: Enhancement

#607 [config] Call 'systemctl reset-failed' before 'systemctl restart' when restarting services
  config/main.py
Labels: Enhancement, Request for 201811 Branch, Request for 201904 Branch

#610 [Command Reference] Add config commands for DHCP relay destination address
  doc/Command-Reference.md
Labels: Documentation

#611 [config] Add commands for adding/removing NTP servers
  config/main.py
  doc/Command-Reference.md
Labels: Enhancement
