Repository sonic-net/sonic-utilities, pull requests merged in 2019-04, with the labels that each got.

#450 [clear/main.py]: clear ndp command.
  clear/main.py
Labels: enhancement

#498 Update neighbor advertiser
  scripts/neighbor_advertiser
Labels: Request_for_201811_branch, enhancement

#504 [config]: Change the order of interface commands
  config/main.py
Labels: bug

#505 [neighbor advertiser] convert int to string before concatenating
  scripts/neighbor_advertiser
Labels: Request_for_201811_branch, bug

#507 In sync with our latest change, where we default failthrough to be False
  show/main.py
Labels: Request_for_201811_branch

#510 [fast/warm reboot] add some sanity check before warm reboot
  scripts/fast-reboot
Labels: Request_for_201811_branch, enhancement

#511 load_minigraph: restart hostcfgd
  config/main.py
Labels: Request_for_201811_branch

#515 If fast-reboot-dump gives an error, don't continue with fast-reboot
  scripts/fast-reboot
  scripts/fast-reboot-dump.py
Labels: Request_for_201811_branch, enhancement

#517 [scripts] remove duplicate script copying for nbrshow
  setup.py
Labels: enhancement

#500 Bring queue storm status to 'pfcwd show stats'
  pfcwd/main.py
Labels: Request_for_201811_branch, enhancement

#519 [db migrator] Introduce the DB migration infrastructure
  config/main.py
  scripts/db_migrator.py
  setup.py
Labels: Request_for_201811_branch, enhancement

#524 [show] Call teamshow using sudo in 'show interfaces portchannel'
  scripts/teamshow
  show/main.py
Labels: Request_for_201811_branch, bug
