Repository sonic-net/sonic-utilities, pull requests merged in 2020-11, with the labels that each got.

#1078 [sfputil] Display 'N/A' for non-SFP ports
  sfputil/main.py
Labels: Enhancement

#1190 [201911][fwutil]: Use logger from sonic-py-common
  fwutil/log.py
Labels: Enhancement, Included in 201911 Branch

#1211 [show/fgnhg.py] Fix whitespace issues
  show/fgnhg.py
Labels: Bug, Cleanup :droplet:

#1197 SONiC installer - fix string formatting during image type check
  sonic_installer/main.py
Labels: Request for 201911 Branch

#1214 [connect][clear] Support --devicename option for connect/clear line commands
  clear/main.py
  connect/main.py
  consutil/main.py
  doc/Command-Reference.md
Labels: Enhancement, clear, connect

#1217 Replace swsssdk.SonicV2Connector with swsscommon.SonicV2Connector (SWIG wrapper of C++ implementation) in production code
  acl_loader/main.py
  config/config_mgmt.py
  config/main.py
  config/nat.py
  scripts/db_migrator.py
  scripts/fanshow
  scripts/fdbclear
  scripts/fdbshow
  scripts/natclear
  scripts/natshow
  scripts/nbrshow
  scripts/neighbor_advertiser
  scripts/psushow
  scripts/tempershow
  show/fgnhg.py
  show/main.py
  sonic_installer/main.py
  tests/mock_tables/dbconnector.py
Labels: Cleanup :droplet:

#1222 [sonic_sku_create] Move tests from sonic-utilities-tests/ folder to tests/ folder
  scripts/sonic_sku_create.py
  tests/sku_create_input/ACS-MSN2700/buffers.json.j2
  tests/sku_create_input/ACS-MSN2700/buffers_defaults_t0.j2
  tests/sku_create_input/ACS-MSN2700/buffers_defaults_t1.j2
  tests/sku_create_input/ACS-MSN2700/pg_profile_lookup.ini
  tests/sku_create_input/ACS-MSN2700/port_config.ini
  tests/sku_create_input/ACS-MSN2700/qos.json
  tests/sku_create_input/ACS-MSN2700/sai.profile
  tests/sku_create_input/Mellanox-SN2700-D48C8.xml
  tests/sku_create_input/Mellanox-SN2700-D48C8/buffers.json.j2
  tests/sku_create_input/Mellanox-SN2700-D48C8/buffers_defaults_t0.j2
  tests/sku_create_input/Mellanox-SN2700-D48C8/buffers_defaults_t1.j2
  tests/sku_create_input/Mellanox-SN2700-D48C8/pg_profile_lookup.ini
  tests/sku_create_input/Mellanox-SN2700-D48C8/port_config.ini
  tests/sku_create_input/Mellanox-SN2700-D48C8/port_config.ini.bak
  tests/sku_create_input/Mellanox-SN2700-D48C8/port_config.ini.new
  tests/sku_create_input/Mellanox-SN2700-D48C8/port_config.ini.orig
  tests/sku_create_input/Mellanox-SN2700-D48C8/qos.json
  tests/sku_create_input/Mellanox-SN2700-D48C8/sai.profile
  tests/sku_create_input/Mellanox-SN2700-D48C8/sai_2700_48x50g_8x100g.xml
  tests/sku_create_input/default_sku
  tests/sku_create_test.py
Labels: Cleanup :droplet:

#1189 [201911][show] Fix 'show int neigh expected'
  show/main.py
Labels: Bug, Included in 201911 Branch, show

#1194 [show] Fix `show ip bgp sum`
  utilities_common/bgp_util.py
Labels: Bug, Request for 201911 Branch, show

#1193 [show][techsupport][multi-ASIC] Add support to collect tech support on multi ASIC platform
  scripts/generate_dump
Labels: Request for 201911 Branch

#1226 Remove SKU create pytest output directory before execution of the script
  tests/sku_create_test.py
Labels: Enhancement, tests

#1203 [CLI][pfcwd][start] Fix port validation issue when specifying port options in Multi ASIC platform
  pfcwd/main.py
Labels: Request for 201911 Branch

#1224 Updates to bgp config and show commands with BGP_INTERNAL_NEIGHBOR table
  config/main.py
  show/main.py
  tests/bgp_commands_test.py
  tests/mock_tables/config_db.json
  utilities_common/bgp_util.py
Labels: Request for 201911 Branch

#1233 [tests] Do not trim from PATH if we did not append to it; Clean up/fix shebangs in scripts
  clear/main.py
  config/kube.py
  connect/main.py
  counterpoll/main.py
  debug/main.py
  pfcwd/main.py
  scripts/aclshow
  scripts/dump_nat_entries.py
  scripts/ecnconfig
  scripts/fanshow
  scripts/fdbclear
  scripts/fdbshow
  scripts/gearboxutil
  scripts/intfutil
  scripts/mmuconfig
  scripts/natclear
  scripts/natconfig
  scripts/natshow
  scripts/nbrshow
  scripts/portconfig
  scripts/psushow
  scripts/sfpshow
  scripts/sonic-kdump-config
  scripts/sonic_sku_create.py
  scripts/tempershow
  scripts/watermarkstat
  show/kube.py
  show/main.py
  sonic_installer/main.py
  tests/crm_test.py
  tests/sflow_test.py
  tests/show_breakout_test.py
  tests/show_platform_test.py
  tests/system_health_test.py
  undebug/main.py
Labels: Bug, Cleanup :droplet:, tests

#1240 Add 'requests' as install dependency in setup.py
  setup.py
Labels: Bug

#1239 Clean up LGTM alerts
  pcieutil/main.py
  scripts/db_migrator.py
  scripts/natconfig
  scripts/natshow
  show/bgp_frr_v4.py
  show/interfaces/portchannel.py
  utilities_common/bgp_util.py
Labels: Cleanup :droplet:

#1243 Remove unnecessary conversions to list() and calls to dict.keys()
  acl_loader/main.py
  config/config_mgmt.py
  config/main.py
  config/nat.py
  fdbutil/filter_fdb_entries.py
  fwutil/lib.py
  pfcwd/main.py
  scripts/aclshow
  scripts/configlet
  scripts/db_migrator.py
  scripts/fast-reboot-dump.py
  scripts/intfutil
  scripts/neighbor_advertiser
  scripts/pcmping
  scripts/sonic_sku_create.py
  scripts/update_json.py
  show/fgnhg.py
  show/interfaces/__init__.py
  show/main.py
  show/vlan.py
  tests/config_mgmt_test.py
  tests/mock_tables/dbconnector.py
  utilities_common/bgp_util.py
  utilities_common/cli.py
Labels: Cleanup :droplet:

#1247 [configlet][portconfig] Remove calls to dict.has_key() which is not available in Python 3
  scripts/configlet
  scripts/portconfig
Labels: Bug

#1254 Cosmetic fix - replace hard-coded fast-reboot with REBOOT_TYPE variable
  scripts/fast-reboot
Labels: Cleanup :droplet:, fast-reboot

#1257 [acl-loader] Make list sorting compliant with Python 3
  acl_loader/main.py
Labels: Bug, acl-loader/aclshow

#1260 Remove unnecessary calls to str.encode() now that the package is Python 3; Fix deprecation warning
  acl_loader/main.py
  fwutil/lib.py
  scripts/decode-syseeprom
Labels: Bug, acl-loader/aclshow
