Repository sonic-net/sonic-utilities, pull requests merged in 2020-01, with the labels that each got.

#743 [portstat] fix header used
  scripts/portstat
Labels: Request for 201911 Branch

#754 [show] enhance 'show ip[v6] bgp summary' command
  doc/Command-Reference.md
  show/bgp_frr_v6.py
  show/bgp_quagga_v4.py
  show/bgp_quagga_v6.py
  show/main.py
Labels: Enhancement, Request for 201911 Branch

#784 [dropconfig] Clean-up error output for devices that do not support drop counters
  scripts/dropconfig
Labels: Bug, Request for 201911 Branch

#759 [config] Merge duplicate vrf configuration
  config/main.py
Labels: Request for 201911 Branch

#786 ipaddr module to ipaddress
  show/main.py
Labels: Bug, Request for 201911 Branch

#789 [fdbshow][nbrshow] Print interface OID in lieu of name if there is no OID->interface name mapping
  scripts/fdbshow
  scripts/nbrshow
Labels: Enhancement, Request for 201811 Branch, Request for 201911 Branch

#777 Add command line support for thermal control
  scripts/fanshow
  scripts/tempershow
  setup.py
  show/main.py
Labels: Enhancement

#788 [acl-loader] Use V6 EtherType for IPv6 ACL rule
  acl_loader/main.py
Labels: Enhancement, Request for 201811 Branch, Request for 201911 Branch

#785 [dropconfig] Move prefix-handling from CLI to orchagent
  scripts/dropconfig
  sonic-utilities-tests/mock_tables/state_db.json
Labels: Request for 201911 Branch

#791 [fast/warm reboot] watchdog log message mentions the right reboot type
  scripts/fast-reboot
Labels: Included in 201811 Branch
