Repository sonic-net/sonic-utilities, pull requests merged in 2020-08, with the labels that each got.

#1022 Rename 'sonic-utilities-tests' to 'tests'
  .github/PULL_REQUEST_TEMPLATE.md
  scripts/dropconfig
  scripts/dropstat
  scripts/gearboxutil
  scripts/intfstat
  scripts/intfutil
  scripts/psushow
  scripts/sfpshow
  setup.py
  tests/__init__.py
  tests/acl_input/acl1.json
  tests/acl_input/acl2.json
  tests/acl_input/empty_acl.json
  tests/acl_loader_test.py
  tests/aclshow_test.py
  tests/config_mgmt_test.py
  tests/drops_group_test.py
  tests/filter_fdb_entries_test.py
  tests/filter_fdb_input/__init__.py
  tests/filter_fdb_input/arp.json
  tests/filter_fdb_input/config_db.json
  tests/filter_fdb_input/expected_fdb.json
  tests/filter_fdb_input/fdb.json
  tests/filter_fdb_input/test_vectors.py
  tests/gearbox_test.py
  tests/intfstat_test.py
  tests/intfutil_test.py
  tests/mock_tables/__init__.py
  tests/mock_tables/appl_db.json
  tests/mock_tables/asic_db.json
  tests/mock_tables/config_db.json
  tests/mock_tables/counters_db.json
  tests/mock_tables/dbconnector.py
  tests/mock_tables/state_db.json
  tests/port2alias_test.py
  tests/psu_test.py
  tests/pytest.ini
  tests/sfp_test.py
  tests/show_breakout_test.py
Labels: Cleanup :droplet:

#1023 [tests]: fix drops_group_test failure on second run
  tests/drops_group_test.py
Labels: Bug

#1027 [tests]: mv feature_test into tests folder
  tests/feature_test.py
Labels: Bug

#1021 [tests] Add unit tests for 'show platform ...' commands
  tests/show_platform_test.py
Labels: tests

#940 [PDDF] Make utilities compatible to platform API 2.0, in accordance with pddf_2.0
  pddf_fanutil/main.py
  pddf_ledutil/main.py
  pddf_psuutil/main.py
  pddf_thermalutil/main.py
  utilities_common/util_base.py
Labels: Enhancement, PDDF

#1008 [Python] Migrate applications/scripts to import sonic-py-common package
  acl_loader/main.py
  config/main.py
  config/mlnx.py
  fwutil/lib.py
  fwutil/log.py
  pcieutil/main.py
  pddf_fanutil/main.py
  pddf_ledutil/main.py
  pddf_psuutil/main.py
  pddf_thermalutil/main.py
  psuutil/main.py
  scripts/db_migrator.py
  scripts/decode-syseeprom
  scripts/lldpshow
  scripts/neighbor_advertiser
  scripts/port2alias
  setup.py
  sfputil/main.py
  show/main.py
  sonic_installer/main.py
  ssdutil/main.py
  tests/conftest.py
  utilities_common/util_base.py
  watchdogutil/main.py
Labels: Cleanup :droplet:, acl-loader/aclshow, config, show, sonic-installer, utilities-common

#1039 [tests]:add coverage for config/main/utilities_common module
  pytest.ini
Labels: Enhancement, tests

#1037 [fast-reboot/warm-reboot] Enable watchdog before running platform specific reboot plugin
  scripts/fast-reboot
Labels: Request for 201911 Branch, fast-reboot

#1041 [pytest/coverage]: add coverage for all scripts
  pytest.ini
Labels: Enhancement, tests

#1038 [config/show]: split vlan into separate file
  config/aaa.py
  config/main.py
  config/mlnx.py
  config/utils.py
  config/vlan.py
  show/bgp_frr_v4.py
  show/bgp_frr_v6.py
  show/main.py
  show/vlan.py
  tests/config_test.py
  tests/conftest.py
  tests/intfutil_test.py
  tests/mock_tables/appl_db.json
  tests/mock_tables/config_db.json
  tests/vlan_test.py
  utilities_common/cli.py
Labels: Cleanup :droplet:, Enhancement, config, show, tests

#1033 Update all references to new 'sonic-installer' file name
  scripts/fast-reboot
  scripts/reboot
  sonic_installer/exception.py
Labels: Cleanup :droplet:, fast-reboot, reboot

#1043 Python 3 compliance
  config/aaa.py
  config/main.py
  config/mlnx.py
  consutil/main.py
  counterpoll/main.py
  crm/main.py
  pcieutil/main.py
  pddf_thermalutil/main.py
  pfc/main.py
  pfcwd/main.py
  scripts/boot_part
  scripts/decode-syseeprom
  scripts/fast-reboot-dump.py
  scripts/fdbclear
  scripts/fdbshow
  scripts/gearboxutil
  scripts/intfstat
  scripts/intfutil
  scripts/natclear
  scripts/natconfig
  scripts/natshow
  scripts/nbrshow
  scripts/pcmping
  scripts/pfcstat
  scripts/portstat
  scripts/psushow
  scripts/queuestat
  scripts/sfpshow
  scripts/sonic-kdump-config
  scripts/teamshow
  scripts/watermarkcfg
  scripts/watermarkstat
  sfputil/main.py
  show/main.py
  show/mlnx.py
  ssdutil/main.py
  tests/config_test.py
  utilities_common/cli.py
Labels: Cleanup :droplet:, Enhancement, PDDF, config, show, tests, utilities-common

#1048 [watermarkstat] Import print_function from __future__
  scripts/watermarkstat
Labels: Bug

#1045 [config] Eliminate port breakout-related globals
  config/main.py
Labels: Bug, Enhancement, config

#1018 [PFCWD] Fix issue with "pfcwd show stats" command during SONiC init
  pfcwd/main.py
Labels: Request for 201911 Branch

#1050 [show/vlan]: fix show vlan config
  show/vlan.py
  tests/vlan_test.py
Labels: Bug, show

#993 [db_migrator] Support migrating database regarding buffer configuration for all Mellanox switches
  scripts/db_migrator.py
  scripts/mellanox_buffer_migrator.py
  setup.py
Labels: Request for 201911 Branch

#1040 [201911][Python] Migrate applications/scripts to import sonic-py-common package
  acl_loader/main.py
  config/main.py
  fwutil/lib.py
  scripts/db_migrator.py
  scripts/decode-syseeprom
  scripts/lldpshow
  scripts/neighbor_advertiser
  scripts/teamshow
  show/main.py
  show/mlnx.py
Labels: Cleanup :droplet:, Included in 201911 Branch, acl-loader/aclshow, config, show

#999 Common functions for show CLI support on multi ASIC
  utilities_common/constants.py
  utilities_common/multi_asic.py
Labels: Enhancement, Multi-ASIC :1234:, Request for 201911 Branch, utilities-common

#1036 Change fast-reboot script to use swss and radv service script
  scripts/fast-reboot
Labels: Enhancement, fast-reboot

#1055 [201911] fix show version
  scripts/decode-syseeprom
Labels: Bug, Included in 201911 Branch

#1052 [config] Reduce Calls to SONiC Cfggen
  config/main.py
Labels: Enhancement, Request for 201911 Branch

#1061 [sonic-installer] Import 're' module
  sonic_installer/main.py
Labels: Bug, sonic-installer

#1046 Add ip_prefix len based on proxy_arp status
  scripts/neighbor_advertiser
  tests/mock_tables/appl_db.json
  tests/mock_tables/config_db.json
  tests/neighbor_advertiser_test.py
  tests/vlan_test.py
Labels: Request for 201911 Branch

#1069 [config] Remove _get_breakout_cfg_file_name helper function
  config/main.py
Labels: Cleanup :droplet:

#1059 [filter-fdb] Fix Filter FDB With IPv6 Present in Config DB
  fdbutil/filter_fdb_entries.py
  tests/filter_fdb_input/config_db.json
  tests/filter_fdb_input/expected_fdb.json
  tests/filter_fdb_input/test_vectors.py
Labels: Bug, Request for 201811 Branch, Request for 201911 Branch

#878 Multi asic platform changes for interface, portchannel commands
  config/main.py
  scripts/portconfig
  sfputil/main.py
Labels: Multi-ASIC :1234:, Request for 201911 Branch

#1073 [config] Update SONiC Environment Vars When Loading Minigraph
  config/main.py
Labels: Enhancement, Request for 201911 Branch

#1079 [show][bgp] Display the Total number of neighbors in the show ip bgp(v6) summary
  tests/bgp_commands_test.py
  tests/multi_asic_intfutil_test.py
  utilities_common/bgp_util.py
Labels: Bug

#1077 [pfcwd] Fix stats crash with invalid queue name
  pfcwd/main.py
Labels: Bug, Request for 201811 Branch, Request for 201911 Branch
