Repository sonic-net/sonic-utilities, pull requests merged in 2020-06, with the labels that each got.

#933 [201911][config] Support abbreviation
  config/main.py
Labels: Enhancement, Included in 201911 Branch

#915 [warm-reboot]: added pre-check for ISSU file
  scripts/fast-reboot
Labels: Enhancement, Platform: Mellanox, Request for 201911 Branch

#931 [show] Add support for SONiC Gearbox Manager via new gearboxutil utility
  doc/Command-Reference.md
  scripts/gearboxutil
  setup.py
  show/main.py
  sonic-utilities-tests/gearbox_test.py
  sonic-utilities-tests/mock_tables/appl_db.json
Labels: Enhancement

#934 [Mellanox] Add 'hw-management-generate-dump.sh' to 'show techsupport' command
  scripts/generate_dump
Labels: Enhancement, Platform: Mellanox, Request for 201911 Branch

#767 [sfputil] Add support of platform.json
  sfputil/main.py
Labels: Port Breakout :trident:

#871 Fixed warm-reboot for BFN platform
  scripts/fast-reboot
Labels: Request for 201911 Branch

#944 [config] Don't attempt to restart disabled services
  config/main.py
Labels: Enhancement, Request for 201911 Branch

#918 handled the priority of ACL rules to be case insensitive
  acl_loader/main.py
  scripts/aclshow
  sonic-utilities-tests/aclshow_test.py
  sonic-utilities-tests/mock_tables/config_db.json
  sonic-utilities-tests/mock_tables/counters_db.json
Labels: Bug

#942 [fwutil]: Update fwutil to v2.0.0.0
  data/etc/bash_completion.d/fwutil
  fwutil/lib.py
  fwutil/log.py
  fwutil/main.py
  show/main.py
Labels: Enhancement

#941 [fwutil]: Update fwutil to v2.0.0.0
  data/etc/bash_completion.d/fwutil
  fwutil/lib.py
  fwutil/log.py
  fwutil/main.py
  show/main.py
Labels: Enhancement

#955 [show interface transceiver] Ensure key exists in dom_info_dict before accessing
  scripts/sfpshow
Labels: Bug, Request for 201911 Branch

#957 [filter-fdb] Check VLAN Presence When Filter FDB
  scripts/fast-reboot
  scripts/filter_fdb_entries.py
  sonic-utilities-tests/filter_fdb_entries_test.py
  sonic-utilities-tests/filter_fdb_input/config_db.json
  sonic-utilities-tests/filter_fdb_input/test_vectors.py
Labels: Request for 201811 Branch, Request for 201911 Branch

#961 [show] Add missing verbose option to "show line"
  show/main.py
Labels: Bug

#958 [sfpshow][mock_state_db] Tweak key names of some transceiver info fields
  scripts/sfpshow
  sonic-utilities-tests/mock_tables/state_db.json
Labels: Enhancement, Request for 201911 Branch

#859 [Show | Command Reference] Add Port breakout Show Command
  doc/Command-Reference.md
  show/main.py
  sonic-utilities-tests/mock_tables/config_db.json
  sonic-utilities-tests/show_breakout_test.py
Labels: Port Breakout :trident:

#965 [config] Fix indentation level in _get_disabled_services_list()
  config/main.py
Labels: Bug, Request for 201911 Branch

#966 [config] Fix 'except' syntax error
  config/main.py
Labels: Bug, Request for 201911 Branch
