Repository sonic-net/sonic-utilities, pull requests merged in 2020-09, with the labels that each got.

#1085 [pfcwd] Add single asic unit tests for show commands
  setup.py
  tests/mock_tables/config_db.json
  tests/mock_tables/counters_db.json
  tests/pfcwd_input/__init__.py
  tests/pfcwd_input/pfcwd_test_vectors.py
  tests/pfcwd_test.py
Labels: Request for 201911 Branch, pfcwd, show, tests

#1088 [setup.py] Add aliases.ini to sonic_installer package
  setup.py
Labels: Bug

#1091 Add ASIC namespace ID to core filename, if any
  scripts/coredump-compress
Labels: Enhancement, Request for 201911 Branch

#1080 [CLI][PFCWD][Multi-ASIC] Added multi ASIC support to 'pfcwd' CLI command
  pfcwd/main.py
  show/main.py
  tests/mock_tables/asic0/config_db.json
  tests/mock_tables/asic0/counters_db.json
  tests/mock_tables/asic1/config_db.json
  tests/mock_tables/asic1/counters_db.json
  tests/pfcstat_test.py
  tests/pfcwd_input/pfcwd_test_vectors.py
  tests/pfcwd_test.py
Labels: Enhancement, Multi-ASIC :1234:, pfcwd, show

#1090 [Mellanox] Fix a typo in mellanox_buffer_migrator
  scripts/mellanox_buffer_migrator.py
Labels: Bug, Request for 201911 Branch

#1086 [filter-fdb] Call Filter FDB Main From Within Test Code #1051
  fdbutil/__init__.py
  fdbutil/filter_fdb_entries.py
  scripts/fast-reboot
  setup.py
  sonic-utilities-tests/filter_fdb_entries_test.py
  sonic-utilities-tests/filter_fdb_input/config_db.json
  sonic-utilities-tests/filter_fdb_input/expected_fdb.json
  sonic-utilities-tests/filter_fdb_input/test_vectors.py
Labels: Included in 201811 Branch

#1103 [drop counters] Fix configuration for counters with lowercase names
  scripts/dropconfig
  tests/drops_group_test.py
  tests/mock_tables/config_db.json
  tests/mock_tables/counters_db.json
Labels: Bug, Request for 201911 Branch, config, show, tests

#1107 Skip default route present in ASIC-DB but not in APP-DB.
  scripts/route_check.py
Labels: Enhancement

#1113 [utilities] Define Explicit Dependency On Ipaddress Package
  setup.py
Labels: Request for 201811 Branch

#1115 Update to make config load/reload backward compatible.
  config/main.py
Labels: Request for 201911 Branch

#1118 [teamshow] Remove 't' from argument when calling docker exec
  scripts/teamshow
Labels: Bug, Request for 201911 Branch

#1106 [show] Fix 'show int neighbor expected'
  show/main.py
Labels: Bug, Request for 201911 Branch, show

#1120 [consutil] Display remote device name in show command
  consutil/lib.py
  consutil/main.py
Labels: Enhancement

#1122 Support building sonic-utilities as a Python wheel package instead of a Debian package
  .gitignore
  config/main.py
  scripts/fast-reboot
  scripts/generate_dump
  scripts/sonic-kdump-config
  setup.py
  sonic-utilities-data/LICENSE
  sonic-utilities-data/MAINTAINERS
  sonic-utilities-data/README.md
  sonic-utilities-data/bash_completion.d/acl-loader
  sonic-utilities-data/bash_completion.d/config
  sonic-utilities-data/bash_completion.d/connect
  sonic-utilities-data/bash_completion.d/consutil
  sonic-utilities-data/bash_completion.d/counterpoll
  sonic-utilities-data/bash_completion.d/crm
  sonic-utilities-data/bash_completion.d/debug
  sonic-utilities-data/bash_completion.d/fwutil
  sonic-utilities-data/bash_completion.d/pddf_fanutil
  sonic-utilities-data/bash_completion.d/pddf_ledutil
  sonic-utilities-data/bash_completion.d/pddf_psuutil
  sonic-utilities-data/bash_completion.d/pddf_thermalutil
  sonic-utilities-data/bash_completion.d/pfc
  sonic-utilities-data/bash_completion.d/pfcwd
  sonic-utilities-data/bash_completion.d/psuutil
  sonic-utilities-data/bash_completion.d/sfputil
  sonic-utilities-data/bash_completion.d/show
  sonic-utilities-data/bash_completion.d/sonic-clear
  sonic-utilities-data/bash_completion.d/sonic-installer
  sonic-utilities-data/bash_completion.d/sonic_installer
  sonic-utilities-data/bash_completion.d/undebug
  sonic-utilities-data/debian/changelog
  sonic-utilities-data/debian/compat
  sonic-utilities-data/debian/control
  sonic-utilities-data/debian/copyright
  sonic-utilities-data/debian/install
  sonic-utilities-data/debian/rules
  sonic-utilities-data/templates/sonic-environment.j2
Labels: Enhancement

#1125 [setup.py] Update dependencies
  setup.py
Labels: Enhancement

#1123 Fixed config load_minigrpah not working for Multi-asic platfroms.
  config/main.py
Labels: Multi-ASIC :1234:, Request for 201911 Branch

#1124 [201911] Fix load minigraph for multi-asic platforms
  config/main.py
Labels: Multi-ASIC :1234:

#1126 [show] Add missing import to fix `show ip interfaces`
  show/main.py
Labels: Bug

#1131 [README.md] Describe new package creation schema
  README.md
Labels: Documentation

#1137 use vtysh in the show ip bgp summary command
  utilities_common/bgp_util.py
Labels: Multi-ASIC :1234:, Request for 201911 Branch

#1136 [config/console] Support add/del console port setting commands
  config/console.py
  config/main.py
  tests/console_test.py
Labels: config

#1143 Show sflow interface to display all interfaces enabled for sflow
  show/main.py
Labels: Request for 201911 Branch
