Repository sonic-net/sonic-utilities, pull requests merged in 2020-04, with the labels that each got.

#796 [pfc] Add command line to enable/disable/show PFC
  config/main.py
  doc/Command-Reference.md
  pfc/main.py
  show/main.py
Labels: Enhancement

#862 [watermarkstat] Fix issue of fields overwritten before display
  scripts/watermarkstat
Labels: Bug, Request for 201811 Branch, Request for 201911 Branch

#852 Explicitly specify command names with underscores (continued)
  config/main.py
  debug/main.py
  pddf_fanutil/main.py
  pddf_psuutil/main.py
  pddf_thermalutil/main.py
  pfcwd/main.py
  show/main.py
  sonic_installer/main.py
  undebug/main.py
Labels: Enhancement, Request for 201911 Branch

#863 [201811] [watermarkstat] Fix issue of fields overwritten before display
  scripts/watermarkstat
Labels: Bug, Included in 201811 Branch

#867 Fix Python warnings
  clear/main.py
  config/aaa.py
  config/main.py
  config/mlnx.py
  psuutil/main.py
  scripts/boot_part
  scripts/decode-syseeprom
  scripts/fdbshow
  scripts/natconfig
  scripts/nbrshow
  scripts/neighbor_advertiser
  scripts/pcmping
  scripts/portstat
  scripts/sonic-kdump-config
  sfputil/main.py
  show/bgp_frr_v6.py
  show/bgp_quagga_v4.py
  show/bgp_quagga_v6.py
  show/main.py
  sonic_installer/main.py
  ssdutil/main.py
  utilities_common/util_base.py
Labels: Cleanup :droplet:

#869 Fix more Python warnings
  config/main.py
  config/mlnx.py
  config/nat.py
  connect/main.py
  consutil/lib.py
  consutil/main.py
  crm/main.py
  debug/main.py
  pddf_fanutil/main.py
  pddf_ledutil/main.py
  pddf_psuutil/main.py
  pddf_thermalutil/main.py
  pfc/main.py
  psuutil/main.py
  scripts/aclshow
  scripts/configlet
  scripts/db_migrator.py
  scripts/decode-syseeprom
  scripts/dump_nat_entries.py
  scripts/ecnconfig
  scripts/fanshow
  scripts/fdbclear
  scripts/intfstat
  scripts/natclear
  scripts/natconfig
  scripts/natshow
  scripts/neighbor_advertiser
  scripts/pfcstat
  scripts/portconfig
  scripts/portstat
  scripts/queuestat
  scripts/sfpshow
  scripts/sonic-kdump-config
  scripts/teamshow
  scripts/tempershow
  scripts/update_json.py
  scripts/watermarkstat
  sfputil/main.py
  show/main.py
  show/mlnx.py
  sonic-utilities-tests/drops_group_test.py
  sonic-utilities-tests/intfstat_test.py
  sonic-utilities-tests/psu_test.py
  sonic-utilities-tests/sfp_test.py
  sonic_installer/main.py
  undebug/main.py
  utilities_common/util_base.py
Labels: Cleanup :droplet:

#868 [201911] Explicitly specify command names with underscores (continued)
  config/main.py
  debug/main.py
  pddf_fanutil/main.py
  pddf_psuutil/main.py
  pfcwd/main.py
  show/main.py
  sonic_installer/main.py
  undebug/main.py
Labels: Enhancement, Included in 201911 Branch

#873 Fix even more Python warnings
  clear/bgp_frr_v6.py
  clear/bgp_quagga_v4.py
  clear/bgp_quagga_v6.py
  config/main.py
  config/nat.py
  fwutil/lib.py
  pddf_fanutil/main.py
  pddf_psuutil/main.py
  pddf_thermalutil/main.py
  psuutil/main.py
  scripts/aclshow
  scripts/ecnconfig
  scripts/intfstat
  scripts/intfutil
  scripts/natshow
  scripts/nbrshow
  scripts/neighbor_advertiser
  scripts/pfcstat
  scripts/queuestat
  scripts/sonic-kdump-config
  scripts/teamshow
  sfputil/main.py
  show/main.py
  sonic_installer/main.py
Labels: Cleanup :droplet:

#875 [doc]: add ltgm and jenkins badge
  README.md
Labels: Documentation

#876 [fwutil]: Update documentation: CPLD update on Mellanox platforms
  doc/Command-Reference.md
Labels: Documentation, Platform: Mellanox, Request for 201911 Branch

#602 [generate_dump] Dump systemd specific information
  scripts/generate_dump
Labels: Enhancement

#884 [show][bgp] Use only 'show ip bgp' as the base and use bgp_frr_v4 file for FRR routing stack
  show/bgp_frr_v4.py
  show/main.py
Labels: Enhancement, Request for 201911 Branch

#880 [Vxlan] : adding show vnet/vxlan cmds
  doc/Command-Reference.md
  show/main.py
Labels: Request for 201911 Branch

#888 [show] Add 'ip/ipv6 bgp network' commands
  doc/Command-Reference.md
  show/bgp_frr_v4.py
  show/bgp_frr_v6.py
Labels: Enhancement, Request for 201911 Branch

#887 [fast reboot] set a fast-reboot DB flag
  scripts/fast-reboot
Labels: Enhancement, Request for 201911 Branch

#895 [fwutil]: Fix firmware update command
  fwutil/main.py
Labels: Request for 201911 Branch

#844 [mellanox] enable watchdog before fast-reboot
  scripts/watchdog
Labels: Enhancement, Platform: Mellanox
