Repository sonic-net/sonic-utilities, pull requests merged in 2020-10, with the labels that each got.

#1150 [pfcstat] Create new copies of Rx and Tx dictionaries
  scripts/pfcstat
  tests/mock_tables/asic0/counters_db.json
  tests/mock_tables/asic1/counters_db.json
  tests/mock_tables/counters_db.json
  tests/pfcstat_test.py
Labels: Bug, Request for 201911 Branch

#1132 [config] Reload Monit configuration after potential hostname changes
  config/main.py
  tests/config_test.py
Labels: Enhancement, Request for 201911 Branch

#1151 [setup.py] Pin external runtime dependencies at known working versions
  setup.py
  tests/bgp_commands_test.py
  tests/console_test.py
  tests/counterpoll_test.py
Labels: Enhancement

#1161 [README.md] Add instructions for setting up a build/test environment
  README.md
Labels: Documentation

#971 [show] Add 'show' CLI for system-health feature
  doc/Command-Reference.md
  show/main.py
  show/system_health.py
  tests/system_health_test.py
Labels: Enhancement, show

#1164 [fast-reboot] Fix unicode issue in ipaddress for python2
  scripts/fast-reboot-dump.py
Labels: fast-reboot

#1157 [watermarkstat] Add unit tests for watermarkstat show commands
  scripts/watermarkstat
  setup.py
  tests/mock_tables/counters_db.json
  tests/watermarkstat_test.py
  tests/wm_input/__init__.py
  tests/wm_input/wm_test_vectors.py
Labels: Request for 201911 Branch, show, tests

#1173 [consutil] Fix issue where the show line command crash if no ttyUSB exists
  consutil/lib.py
Labels: Bug

#1177 Modify fast-reboot script to use BGP script to stop bgp service
  scripts/fast-reboot
Labels: Enhancement, fast-reboot

#1176 [consutil] Add brief option to show line command
  consutil/lib.py
  consutil/main.py
  show/main.py
Labels: Enhancement

#1180 Fixes the issue with show interface counters and for pfc and queue counters.
  scripts/pfcstat
  scripts/portstat
  scripts/queuestat
  utilities_common/netstat.py
Labels: Bug, Request for 201911 Branch

#1174 [counterpoll] Disable Counter Poll When Entering Fast Reboot
  counterpoll/main.py
  scripts/fast-reboot
  setup.py
  tests/counterpoll_input/config_db.json
  tests/counterpoll_test.py
Labels: Enhancement, Request for 201911 Branch

#1182 Remove stdeb.cfg; no longer used now that we build as wheel
  stdeb.cfg
Labels: Cleanup :droplet:

#1191 [fwutil]: Set min log priority to INFO
  fwutil/log.py
Labels: Bug

#1192 Add license file, remove third-party licenses file
  LICENSE
  ThirdPartyLicenses.txt
Labels: Documentation
