Repository sonic-net/sonic-utilities, pull requests merged in 2020-12, with the labels that each got.

#1276 [config][loopback] Fix Bug that cannot add loopback interface by CLI
  config/main.py
Labels: Bug, config

#1272 [show/fgnhg] Fix crash bug
  show/fgnhg.py
Labels: Bug, show

#1210 Add `show reboot-cause history` cli
  doc/Command-Reference.md
  show/main.py
  show/reboot_cause.py
  tests/mock_tables/state_db.json
  tests/reboot_cause_test.py
Labels: Enhancement, show

#1277 [pfcwd] Use floor division in Python3
  pfcwd/main.py
Labels: Bug, pfcwd

#1280 Fixing python porting errors in fdbshow, natshow and nbrshow
  scripts/fdbshow
  scripts/natshow
  scripts/nbrshow
Labels: Bug

#1259 [show] Break some groups out into their own modules
  show/acl.py
  show/dropcounters.py
  show/gearbox.py
  show/kdump.py
  show/main.py
  show/nat.py
  show/platform.py
  show/processes.py
  show/sflow.py
  show/vnet.py
  show/vxlan.py
  show/warm_restart.py
  tests/config_test.py
  tests/drops_group_test.py
  tests/psu_test.py
  tests/sflow_test.py
  tests/show_platform_test.py
  tests/vlan_test.py
  utilities_common/cli.py
Labels: Cleanup :droplet:, show

#1250 [201911-Mellanox] SKU creator Tool (#1163)
  scripts/sonic_sku_create.py
  setup.py
  sonic-utilities-tests/sku_create_input/ACS-MSN2700/buffers.json.j2
  sonic-utilities-tests/sku_create_input/ACS-MSN2700/buffers_defaults_t0.j2
  sonic-utilities-tests/sku_create_input/ACS-MSN2700/buffers_defaults_t1.j2
  sonic-utilities-tests/sku_create_input/ACS-MSN2700/pg_profile_lookup.ini
  sonic-utilities-tests/sku_create_input/ACS-MSN2700/port_config.ini
  sonic-utilities-tests/sku_create_input/ACS-MSN2700/qos.json
  sonic-utilities-tests/sku_create_input/ACS-MSN2700/sai.profile
  sonic-utilities-tests/sku_create_input/Mellanox-SN2700-D48C8.xml
  sonic-utilities-tests/sku_create_input/Mellanox-SN2700-D48C8/buffers.json.j2
  sonic-utilities-tests/sku_create_input/Mellanox-SN2700-D48C8/buffers_defaults_t0.j2
  sonic-utilities-tests/sku_create_input/Mellanox-SN2700-D48C8/buffers_defaults_t1.j2
  sonic-utilities-tests/sku_create_input/Mellanox-SN2700-D48C8/pg_profile_lookup.ini
  sonic-utilities-tests/sku_create_input/Mellanox-SN2700-D48C8/port_config.ini
  sonic-utilities-tests/sku_create_input/Mellanox-SN2700-D48C8/port_config.ini.bak
  sonic-utilities-tests/sku_create_input/Mellanox-SN2700-D48C8/port_config.ini.new
  sonic-utilities-tests/sku_create_input/Mellanox-SN2700-D48C8/port_config.ini.orig
  sonic-utilities-tests/sku_create_input/Mellanox-SN2700-D48C8/qos.json
  sonic-utilities-tests/sku_create_input/Mellanox-SN2700-D48C8/sai.profile
  sonic-utilities-tests/sku_create_input/Mellanox-SN2700-D48C8/sai_2700_48x50g_8x100g.xml
  sonic-utilities-tests/sku_create_input/default_sku
  sonic-utilities-tests/sku_create_test.py
Labels: Enhancement, Included in 201911 Branch

#1269 [config vlan] Stop, reset-failed, then start dhcp_relay service
  config/vlan.py
  doc/Command-Reference.md
  tests/vlan_test.py
Labels: Bug, config

#1295 [fast-reboot] Fix fast-reboot when NDP entries are present
  fdbutil/filter_fdb_entries.py
Labels: Request for 201911 Branch

#1144 Add show and clear commands for headroom pool watermark
  clear/main.py
  scripts/watermarkstat
  show/main.py
  tests/mock_tables/counters_db.json
  tests/watermarkstat_test.py
  tests/wm_input/wm_test_vectors.py
Labels: clear, show, tests

#1281 [acl_loader] Fix default DENY rule for V6 dataplane ACLs
  acl_loader/main.py
Labels: Bug, Request for 201911 Branch, acl-loader/aclshow

#1299 Added 'detailed' option for 'show interface counters' command
  scripts/portstat
  show/interfaces/__init__.py
  tests/mock_tables/counters_db.json
  tests/portstat_test.py
Labels: brcm-upstream

#1297 [pcieutil] Remove 'pcie-' prefix from subcommands
  pcieutil/main.py
  show/platform.py
Labels: Cleanup :droplet:

#1291 Parse sonic_platform kernel command line parameter to read the platform identifier string
  scripts/reboot
Labels: brcm-upstream

#1298 [Mellanox] Add FW dump with new SAI implementation and remove mst dump
  scripts/generate_dump
Labels: Request for 201911 Branch

#1289 Mgmt vrf validations and bug fixes
  config/main.py
  show/main.py
Labels: brcm-upstream

#1152 [Multi-asic] Enhanced Feature Table configuration for multi-asic platforms
  config/feature.py
  tests/crm_test.py
  tests/feature_test.py
  tests/ip_show_routes_multi_asic_test.py
  tests/mock_tables/asic0/config_db.json
  tests/mock_tables/asic1/config_db.json
  tests/mock_tables/asic2/config_db.json
Labels: Enhancement

#1253 [dropcounters] Fix clear for non-root users
  scripts/dropstat
  tests/drops_group_test.py
Labels: Bug, Request for 201911 Branch, clear

#1324 Fix exception handling code in python3
  scripts/aclshow
  scripts/ecnconfig
  scripts/fdbclear
  scripts/fdbshow
  scripts/lldpshow
  scripts/mmuconfig
  scripts/natclear
  scripts/natconfig
  scripts/natshow
  scripts/nbrshow
  scripts/portconfig
  scripts/sonic_sku_create.py
Labels: Bug

#1258 Add support for snat, dnat and ipmc crm resources
  crm/main.py
  tests/crm_test.py
  tests/mock_tables/asic0/config_db.json
  tests/mock_tables/asic0/counters_db.json
  tests/mock_tables/asic1/config_db.json
  tests/mock_tables/asic1/counters_db.json
  tests/mock_tables/config_db.json
  tests/mock_tables/counters_db.json
Labels: brcm-upstream

#1266 [pytest][qos][config] Added pytests for "config qos reload" commands
  config/main.py
  pfcwd/main.py
  scripts/intfutil
  tests/config_test.py
  tests/conftest.py
  tests/crm_test.py
  tests/mock_tables/mock_multi_asic.py
  tests/qos_config_input/0/buffers.json.j2
  tests/qos_config_input/0/buffers_config.j2
  tests/qos_config_input/0/buffers_defaults_t0.j2
  tests/qos_config_input/0/buffers_defaults_t1.j2
  tests/qos_config_input/0/config_qos.json
  tests/qos_config_input/0/qos.json.j2
  tests/qos_config_input/0/qos_config.j2
  tests/qos_config_input/1/buffers.json.j2
  tests/qos_config_input/1/buffers_config.j2
  tests/qos_config_input/1/buffers_defaults_t0.j2
  tests/qos_config_input/1/buffers_defaults_t1.j2
  tests/qos_config_input/1/config_qos.json
  tests/qos_config_input/1/qos.json.j2
  tests/qos_config_input/1/qos_config.j2
  tests/qos_config_input/buffers.json.j2
  tests/qos_config_input/buffers_config.j2
  tests/qos_config_input/buffers_defaults_t1.j2
  tests/qos_config_input/config_qos.json
  tests/qos_config_input/qos.json.j2
  tests/qos_config_input/qos_config.j2
  tests/qos_config_input/sonic_version.yml
Labels: tests

#1296 Update Fast-reboot to stop sflow during fast-reboot
  scripts/fast-reboot
Labels: brcm-upstream
