Repository sonic-net/sonic-utilities, pull requests merged in 2020-03, with the labels that each got.

#821 [fwutil]: Set default socket timeout for FW download to 30 sec
  fwutil/lib.py
Labels: Bug, Request for 201911 Branch

#832 [Mellanox] add document for thermal control related cli
  doc/Command-Reference.md
Labels: Documentation

#839 [intfutil] set speed to 0 when interface speed is not available
  scripts/intfutil
Labels: Enhancement, Request for 201911 Branch

#840 [201811][intfutil] set speed to 0 when interface speed is not available
  scripts/intfutil
Labels: Enhancement, Included in 201811 Branch

#833 [db_migrator]Do DB migration for buffer pool size change on Mellanox platform
  scripts/db_migrator.py
Labels: Bug, Platform: Mellanox, Request for 201911 Branch

#846 explicitly specify command with underscores
  config/main.py
  pfcwd/main.py
Labels: Enhancement

#835 [decode-syseeprom] fix getattribute check for some platforms
  scripts/decode-syseeprom
Labels: Bug, Request for 201911 Branch

#822 FIX the issue "config load_minigraph -y" command fails
  config/main.py
Labels: Bug

#825 [fwutil]: Use overlay driver when mounting next image filesystem
  doc/Command-Reference.md
  fwutil/lib.py
  fwutil/log.py
  fwutil/main.py
Labels: Bug, Request for 201911 Branch

#826 Fix for adding L3 interface to Vlan group
  config/main.py
Labels: Request for 201911 Branch

#831 [fwutil]: Fix component table layout
  fwutil/lib.py
Labels: Bug, Request for 201911 Branch

#856 [multi-asic]: Update reload of systemd services to support multi-asic platforms
  config/main.py
Labels: Request for 201911 Branch
