Repository sonic-net/sonic-utilities, pull requests merged in 2020-02, with the labels that each got.

#795 [showtech]: dump a few more DB in generate dump
  scripts/generate_dump
Labels: Enhancement

#720 Add document for warm restart use case
  doc/Command-Reference.md
Labels: Documentation

#794 Fix 'show platform eeprom' on virtual switch
  scripts/decode-syseeprom
Labels: Bug

#798 [show] Add subcommand to display the status of auto-restart feature for each container
  show/main.py
Labels: Enhancement, Request for 201911 Branch

#801 [config] Add subcommand to configure the status of auto-restart feature for each container
  config/main.py
Labels: Enhancement, Request for 201911 Branch

#802 [Command Reference] Document CLI commands related to container auto-restart feature
  doc/Command-Reference.md
Labels: Documentation, Request for 201911 Branch

#808 [Command Reference] Correct a typo and fix link jump in the section container auto-restart feature.
  doc/Command-Reference.md
Labels: Documentation

#599 ZTP CLI commands
  config/main.py
  show/main.py
Labels: Enhancement, Request for 201911 Branch

#812 [config/main.py] Modify reload() function to load configuration from init_cfg.json implicitly
  config/main.py
Labels: Enhancement, Request for 201911 Branch

#772 [fwutil]: Command-line utility for interacting with platform components
  config/main.py
  data/etc/bash_completion.d/fwutil
  doc/Command-Reference.md
  fwutil/__init__.py
  fwutil/lib.py
  fwutil/log.py
  fwutil/main.py
  setup.py
  show/main.py
Labels: Enhancement

#793 [config] Add 'config interface mtu' command
  config/main.py
  doc/Command-Reference.md
  scripts/portconfig
Labels: Enhancement

#815 [config] Check if service exists before start/stop/restart of service
  config/main.py
Labels: Enhancement, Request for 201911 Branch

#813 Fix for dhcp_relay deletion on a VLAN
  config/main.py
Labels: Bug, Request for 201911 Branch

#816 [Command-Reference.md] Unify Usage statments and Examples (including sample prompts)
  doc/Command-Reference.md
Labels: Documentation

#819 [reboot] make sure the reboot happens even if platform reboot failed
  scripts/reboot
Labels: Enhancement, Request for 201811 Branch, Request for 201911 Branch

#453 add support for MCLAG
  config/main.py
  scripts/fast-reboot
Labels: Enhancement
