Repository sonic-net/sonic-utilities, pull requests merged in 2020-07, with the labels that each got.

#765 [config] Add ConfigMgmt class for config validation, delete ports, add ports
  config/config_mgmt.py
  sonic-utilities-tests/config_mgmt_test.py
  sonic-utilities-tests/mock_tables/counters_db.json
Labels: Port Breakout :trident:

#945 Add watchdogutil to control the hw watchdog
  setup.py
  watchdogutil/__init__.py
  watchdogutil/main.py
Labels: Enhancement

#917 [Multi NPU] Time Improvements to the config reload/load_minigraph commands
  config/main.py
Labels: Enhancement

#976 [filter-fdb] Fix For Vlan Defined With No CIDR
  scripts/filter_fdb_entries.py
  sonic-utilities-tests/filter_fdb_input/test_vectors.py
Labels: Request for 201811 Branch, Request for 201911 Branch

#979 Support to verify reboot for secure boot
  scripts/fast-reboot
  scripts/reboot
  sonic_installer/bootloader/aboot.py
  sonic_installer/bootloader/bootloader.py
  sonic_installer/main.py
Labels: Enhancement, fast-reboot, reboot, sonic-installer

#986 Fix the None Type Exception when Interface Table does not exist (cold boot) as part of db migration
  scripts/db_migrator.py
Labels: Request for 201911 Branch

#983 [sonic-installer] Hyphens instead of underscores in command and subcommands
  data/etc/bash_completion.d/sonic-installer
  doc/Command-Reference.md
  fwutil/lib.py
  scripts/asic_config_check
  scripts/fast-reboot
  scripts/reboot
  scripts/sonic-kdump-config
  setup.py
  show/main.py
  sonic_installer/aliases.ini
  sonic_installer/common.py
  sonic_installer/main.py
Labels: Cleanup :droplet:, Enhancement, sonic-installer

#989 [show] Add support for QSFP-DD cables on 'show' command
  scripts/sfpshow
  sonic-utilities-tests/mock_tables/state_db.json
  sonic-utilities-tests/sfp_test.py
Labels: Enhancement, Request for 201911 Branch, show

#991 [acl-loader] Fix bugs in acl-loader
  acl_loader/main.py
Labels: Bug, acl-loader/aclshow

#995 [sonic-installer] Update group name for 'verify-next-image' subcommand
  sonic_installer/main.py
Labels: Bug, sonic-installer

#992 [config] Restart telemetry service upon config (re)load
  config/main.py
Labels: Enhancement, Request for 201911 Branch, config

#766 [config] Add Initial draft of Breakout Mode subcommand
  config/main.py
  doc/Command-Reference.md
Labels: Enhancement, Port Breakout :trident:, config

#1010 importing json needed for DPB CLI
  config/main.py
Labels: Port Breakout :trident:

#1002 [show] Fix for 'trunk' PortChannel reported as 'routed' port
  scripts/intfutil
Labels: Bug, Request for 201911 Branch

#1012 [config/config_mgmt.py]: Fix typo and enable test for tablesWithOutYang()
  config/config_mgmt.py
  sonic-utilities-tests/config_mgmt_test.py
Labels: Cleanup :droplet:, Enhancement
