Repository sonic-net/sonic-utilities, pull requests merged in 2021-07, with the labels that each got.

#1679 [show priority-group drop counters] Remove backup with cached PG drop counters after 'config reload'
  config/main.py
  tests/pgdropstat_test.py
Labels: Request for 202012 branch

#1705 [minigraph][port_config] Consume port_config.json while loading minigraph
  config/main.py
  tests/config_test.py
Labels: Enhancement, Request for 201811 Branch, Request for 201911 Branch, Request for 202012 branch, Request for 202106 branch, config

#1709 Fixed IP validation in "config interface ip add/remove"
  config/main.py
  tests/ip_config_test.py
Labels: Request for 202012 branch

#1721 [configlet] Python3 compatible syntax for extracting a key from the dict
  scripts/configlet
Labels: Bug, Request for 202012 branch, Request for 202106 branch

#1724 [minigraph][port_config] Use imported config.main and add conditional patch
  tests/config_test.py
Labels: Enhancement

#1708 [doc][fwutil]: Update command reference: per component FW update
  doc/Command-Reference.md
Labels: Documentation

#1731 [show] fix show muxcable metrics <port> for sorted output
  show/muxcable.py
  tests/muxcable_test.py
Labels: Request for 202012 branch, show
