Repository sonic-net/sonic-utilities, pull requests merged in 2021-02, with the labels that each got.

#1364 [show] Run fwutil with sudo
  show/platform.py
Labels: Bug, show

#1388 [storyteller] allow storyteller to work on downloaded logs
  scripts/storyteller
Labels: Enhancement

#1398 do not parse stderr to get correct routing stack
  clear/main.py
  show/main.py
Labels: Request for 202012 branch

#1399 [route_check.py] Skip route check for tun0 interfaces
  scripts/route_check.py
Labels: Request for 202012 branch

#1386 [config][show] cli support for retrieving ber, eye-info and configuring prbs, loopback on Y-cable
  config/muxcable.py
  doc/Command-Reference.md
  setup.py
  show/muxcable.py
  tests/muxcable_test.py
Labels: config, show

#1400 [storyteller] Enhance the storyteller utility
  scripts/storyteller
Labels: Enhancement, Request for 202012 branch

#1402 Advertise ipv6 link local address
  scripts/neighbor_advertiser
  tests/neighbor_advertiser_test.py
Labels: Request for 201911 Branch

#1366 Fix sonic-installer install for Arista secureboot
  sonic_installer/bootloader/aboot.py
  sonic_installer/bootloader/bootloader.py
  sonic_installer/common.py
  sonic_installer/main.py
Labels: Bug, sonic-installer

#1407 [Mellanox] Revert "Add FW dump with new SAI implementation (#1338)"
  scripts/generate_dump
Labels: Request for 202012 branch

#1415 Import 'mock' module from 'unittest' library
  tests/config_dpb_test.py
  tests/config_mgmt_test.py
  tests/reboot_cause_test.py
Labels: Cleanup :droplet:

#1419 [GitHub] Tweak PR and issue templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/issue_template.md
  .github/pull_request_template.md
Labels: Documentation

#1406 [ci] Test and build package using Azure Pipelines
  .artifactignore
  .coveragerc
  azure-pipelines.yml
  pytest.ini
Labels: CI

#1418 [show mux]: Sort output by intf name
  show/muxcable.py
  tests/muxcable_test.py
Labels: Request for 202012 branch, show

#1423 Fix deprecation warnings
  config/config_mgmt.py
  config/main.py
  scripts/route_check.py
  tests/sku_create_test.py
Labels: Cleanup :droplet:

#1430 [storyteller] sort output by time and improve lag support
  scripts/storyteller
Labels: Bug, Enhancement

#1431 [consutil] Look for udevprefix.conf file under platform dir, not plugins
  consutil/lib.py
Labels: Cleanup :droplet:, Request for 202012 branch

#1435 [decode-syseeprom] Refactor to utilize sonic-platform package
  scripts/decode-syseeprom
Labels: Cleanup :droplet:, Request for 202012 branch

#1434 [psuutil] Refactor to utilize sonic-platform package
  psuutil/main.py
  tests/psuutil_test.py
Labels: Cleanup :droplet:, Enhancement, Request for 202012 branch

#1405 [sfpshow] Cleanup
  scripts/sfpshow
Labels: Cleanup :droplet:, Request for 202012 branch

#1421 [sfputil] Refactor to utilize sonic-platform package
  sfputil/main.py
  tests/sfputil_test.py
Labels: Cleanup :droplet:, Enhancement, Request for 202012 branch

#1427 Refactor neighbor_advertiser script and use mock for testing
  scripts/neighbor_advertiser
  tests/neighbor_advertiser_test.py
Labels: Request for 201911 Branch

#1446 [ci] No longer pass '--privileged' option to slave container
  azure-pipelines.yml
Labels: CI

#1441 Update SonicDBConfig calls for centralize_database to use C++ APIs
  scripts/centralize_database
Labels: Request for 202012 branch

#1456 [doc] Add documentation for console feature switch
  doc/Command-Reference.md
Labels: Documentation

#1440 [dpb|config] Fix the validation logic of breakout mode
  config/main.py
  tests/config_dpb_test.py
Labels: Port Breakout :trident:

#1444 [decode-syseeprom] Refactor use of swsscommon; Add unit tests
  scripts/decode-syseeprom
  tests/decode_syseeprom_test.py
  tests/mock_tables/state_db.json
Labels: Cleanup :droplet:, Request for 202012 branch, Unit Tests

#1420 [VLAN] Do not allow to delete a VLAN with members
  config/vlan.py
  tests/vlan_test.py
Labels: Request for 202012 branch

#1463 Dropped redundant code.
  scripts/route_check.py
Labels: Bug, Request for 201911 Branch, Request for 202012 branch

#1462 [Mellanox] Add support for SN4600 system
  scripts/mellanox_buffer_migrator.py
Labels: Enhancement, Platform: Mellanox, Request for 202012 branch

#1448 [show] cli support for show muxcable cableinfo
  show/muxcable.py
  tests/muxcable_test.py
  utilities_common/platform_sfputil_helper.py
Labels: show

#1416 [psushow] Add more output columns; Add option to output in JSON format
  scripts/psushow
  show/platform.py
  tests/mock_tables/state_db.json
  tests/psu_test.py
  tests/psushow_test.py
  tests/show_platform_test.py
Labels: Enhancement, Request for 202012 branch

#1454 [reboot] Add platform-specific reboot cause update hook
  scripts/reboot
Labels: Enhancement, Request for 201911 Branch, Request for 202012 branch, reboot
