Repository sonic-net/sonic-utilities, pull requests merged in 2021-06, with the labels that each got.

#1624 [show platform summary] Add chassis hardware info to platform summary and version
  doc/Command-Reference.md
  show/main.py
  show/platform.py
  tests/show_platform_test.py
Labels: Enhancement, show

#1642 [config] support for configuring muxcable to manual mode of operation
  config/muxcable.py
  tests/mock_tables/config_db.json
  tests/muxcable_test.py
Labels: Request for 202012 branch, config

#1675 [CI] sonic-config-engine now depends on SONiC YANG packages
  azure-pipelines.yml
Labels: Bug, CI

#1648 [201811] Change to use rvtysh when calling the show commands
  show/bgp_quagga_v4.py
  show/bgp_quagga_v6.py
  show/main.py
Labels: Included in 201811 Branch

#1674 Fixing db_migrator for Feature table
  scripts/db_migrator.py
  tests/db_migrator_input/config_db/feature-expected.json
  tests/db_migrator_input/config_db/feature-input.json
  tests/db_migrator_input/init_cfg.json
Labels: Bug

#1673 [config]: Update environment file during config reload
  config/main.py
Labels: Request for 202012 branch

#1681 Make the soft-reboot available in the SONiC image on master
  setup.py
Labels: Enhancement, Request for 202012 branch, reboot

#1653 [vnet_route_check] Fix logic for getting VNET routes from ASIC DB
  scripts/vnet_route_check.py
Labels: Request for 202012 branch

#1664 [config] Adding sanity checks for config reload
  config/main.py
Labels: Enhancement, config

#1686 [show] fix `show version`
  show/platform.py
Labels: Bug, show

#1693 [ci]: Fix config prompt question issue
  .azure-pipelines/build_and_install_module.sh
Labels: CI, Request for 202012 branch

#1691 [pfcwd] Fix the return code in invalid case
  pfcwd/main.py
  tests/pfcwd_test.py
Labels: Bug, Request for 201911 Branch, Request for 202012 branch, pfcwd

#1658 [sfputil] Expose error status fetched from STATE_DB or platform API to CLI
  doc/Command-Reference.md
  sfputil/main.py
  show/interfaces/__init__.py
  tests/mock_tables/state_db.json
  tests/sfputil_test.py
Labels: Enhancement, show

#1640 [Mellanox] Update mellanoxs dump generation to include SDK dumps
  scripts/generate_dump
Labels: Request for 202012 branch

#1672 Pcieutil to load the platform api first instead of using common api
  pcieutil/main.py
Labels: Enhancement, Request for 202012 branch

#1702 Fix the name 'mock_show_bgp_command' not defined issue
  sonic-utilities-tests/conftest.py
Labels: Bug

#1698 [202012] [pfcwd] Fix the return code in invalid case
  pfcwd/main.py
  tests/pfcwd_test.py
Labels: Bug, pfcwd

#1699 [show][config] support for interface alias for muxcable commands
  config/muxcable.py
  show/muxcable.py
  utilities_common/platform_sfputil_helper.py
Labels: Request for 202012 branch, config, show
