Repository sonic-net/sonic-utilities, pull requests merged in 2021-05, with the labels that each got.

#1566 [test][db migrator] Enhancement: handle the case that no buffer change in the latest database version
  tests/db_migrator_test.py
Labels: Request for 202012 branch, Unit Tests

#1530 Relax the install_requires, no need to exact version as long as there are no broken changes with future versions
  setup.py
Labels: Request for 202012 branch

#1583 [pg-drop counter] Add pg-drop script to sonic filesystem
  setup.py
Labels: Bug, Request for 202012 branch

#1589 [neighbor_advertiser] Use existing tunnel if present for creating tunnel mappings
  scripts/neighbor_advertiser
  tests/neighbor_advertiser_test.py
Labels: Request for 201911 Branch

#1580 Fixing serial number read to get from DB if it is populated
  show/main.py
Labels: Enhancement, Request for 202012 branch, show

#1592 Relax the install_requires, no need to exact version as long as there are no broken changes with future versions
  setup.py
Labels: Included in 202012 branch

#1347 [show][config] Add new snmp commands
  config/main.py
  show/main.py
  tests/config_snmp_test.py
  tests/mock_tables/config_db.json
  tests/show_snmp_test.py
Labels: Enhancement, Unit Tests, config, show

#1591 [sonic_installer] dont fail package migration
  sonic_installer/common.py
  sonic_installer/main.py
Labels: Bug, sonic-installer

#1594 [sfpshow] Gracefully handle improper 'specification_compliance' field
  scripts/sfpshow
Labels: Bug, Request for 201911 Branch, Request for 202012 branch

#1605 [201811]Add soft-reboot to script list to copy to /usr/bin
  setup.py
Labels: Included in 201811 Branch

#1603 [201911] Add soft-reboot to script list to copy to /usr/bin
  setup.py
Labels: Enhancement, Included in 201911 Branch

#1303 Shut down interface before dynamic port breakout
  config/config_mgmt.py
  config/main.py
  tests/config_mgmt_test.py
Labels: Enhancement, Port Breakout :trident:

#1615 [show] add support for muxcable metrics
  show/muxcable.py
  tests/mock_tables/state_db.json
  tests/muxcable_test.py
Labels: Request for 202012 branch, show

#1614 [test][db_migrator] Make advance_version_for_expected_database available for other db migrator test cases as well
  tests/db_migrator_input/config_db/non-default-config-expected.json
  tests/db_migrator_test.py
Labels: Unit Tests

#1601 Add psu hardware revision to psushow table
  doc/Command-Reference.md
  scripts/psushow
  tests/mock_tables/state_db.json
  tests/psushow_test.py
Labels: Enhancement

#1627 Fix Unicode issue in ipaddress for python2
  scripts/fast-reboot-dump.py
Labels: Request for 201911 Branch

#1617 [202012][natshow] Fix undefined variable error for fetch_translations
  scripts/natshow
Labels: Included in 202012 branch

#1629 [show] support for show muxcable firmware version of only active banks
  show/muxcable.py
  tests/muxcable_test.py
Labels: Enhancement, Request for 202012 branch, show

#1641 [console][show] Force refresh all lines status during show line
  consutil/lib.py
  consutil/main.py
  tests/console_test.py
Labels: Bug, Enhancement, show

#1572 Change to use rvtysh when calling the show commands
  show/bgp_common.py
  show/bgp_quagga_v4.py
  show/bgp_quagga_v6.py
  show/main.py
  tests/conftest.py
  utilities_common/bgp_util.py
  utilities_common/constants.py
Labels: Request for 201811 Branch, Request for 201911 Branch, Request for 202012 branch
