Repository sonic-net/sonic-utilities, pull requests merged in 2021-11, with the labels that each got.

#1819 [config] fix interface IPv6 address removal.
  config/main.py
  tests/ip_config_test.py
Labels: Request for 202106 branch

#1771 [supervisor][show][interfaces]Fixed show interfaces command shows warning on Supervisor card
  tests/interfaces_test.py
  utilities_common/cli.py
Labels: Triaged, Chassis

#1902 [config] Allow user to set none value for interface type
  scripts/portconfig
  tests/config_an_test.py
Labels: Request for 202106 branch

#1910 Dump media_settings from appDB during fast-reboot
  scripts/fast-reboot-dump.py
Labels: Request for 202012 branch

#1921 [sonic-package-manager] fix registry requests failing when no "service" field in Authorization header
  setup.py
  sonic_package_manager/registry.py
  tests/sonic_package_manager/test_registry.py
Labels: Request for 202106 branch

#1922 [show][platform summary] Add chassis type in the platform summary
  show/platform.py
Labels: show, Chassis

#1644 [sonic-cli-gen] first phase implementation of the SONiC CLI Auto-generation tool
  clear/main.py
  clear/plugins/auto/__init__.py
  config/main.py
  config/plugins/auto/__init__.py
  setup.py
  show/main.py
  show/plugins/auto/__init__.py
  sonic-utilities-data/bash_completion.d/sonic-cli-gen
  sonic-utilities-data/debian/install
  sonic-utilities-data/templates/sonic-cli-gen/common.j2
  sonic-utilities-data/templates/sonic-cli-gen/config.py.j2
  sonic-utilities-data/templates/sonic-cli-gen/show.py.j2
  sonic_cli_gen/__init__.py
  sonic_cli_gen/generator.py
  sonic_cli_gen/main.py
  sonic_cli_gen/yang_parser.py
  tests/cli_autogen_input/autogen_test/show_cmd_output.py
  tests/cli_autogen_input/autogen_test/sonic-device_metadata.yang
  tests/cli_autogen_input/autogen_test/sonic-device_neighbor.yang
  tests/cli_autogen_input/cli_autogen_common.py
  tests/cli_autogen_input/config_db.json
  tests/cli_autogen_input/yang_parser_test/assert_dictionaries.py
  tests/cli_autogen_input/yang_parser_test/sonic-1-list.yang
  tests/cli_autogen_input/yang_parser_test/sonic-1-object-container.yang
  tests/cli_autogen_input/yang_parser_test/sonic-1-table-container.yang
  tests/cli_autogen_input/yang_parser_test/sonic-2-lists.yang
  tests/cli_autogen_input/yang_parser_test/sonic-2-object-containers.yang
  tests/cli_autogen_input/yang_parser_test/sonic-2-table-containers.yang
  tests/cli_autogen_input/yang_parser_test/sonic-choice-complex.yang
  tests/cli_autogen_input/yang_parser_test/sonic-dynamic-object-complex-1.yang
  tests/cli_autogen_input/yang_parser_test/sonic-dynamic-object-complex-2.yang
  tests/cli_autogen_input/yang_parser_test/sonic-grouping-1.yang
  tests/cli_autogen_input/yang_parser_test/sonic-grouping-2.yang
  tests/cli_autogen_input/yang_parser_test/sonic-grouping-complex.yang
  tests/cli_autogen_input/yang_parser_test/sonic-static-object-complex-1.yang
  tests/cli_autogen_input/yang_parser_test/sonic-static-object-complex-2.yang
  tests/cli_autogen_test.py
  tests/cli_autogen_yang_parser_test.py
  utilities_common/util_base.py
Labels: Request for 202111 branch

#1918 [fdbshow]: Handle FDB cleanup gracefully
  scripts/fdbshow
Labels: Bug, show

#1926 [fdbshow]: Handle FDB cleanup gracefully
  scripts/fdbshow
Labels: Bug, show, Request for 202012 branch, Request for 202106 branch

#1928 [202012] Fix bug introduced by cherry-picking of fastboot changes
  scripts/fast-reboot-dump.py
Labels: fast-reboot, Request for 202012 branch

#1650 [sonic-package-manager] support sonic-cli-gen and packages with YANG model
  config/config_mgmt.py
  sonic_package_manager/main.py
  sonic_package_manager/manager.py
  sonic_package_manager/manifest.py
  sonic_package_manager/metadata.py
  sonic_package_manager/service_creator/creator.py
  sonic_package_manager/service_creator/feature.py
  tests/sonic_package_manager/conftest.py
  tests/sonic_package_manager/test_service_creator.py
Labels: Request for 202111 branch

#1937 [load_minigraph] Delay pfcwd start until the buffer templates are rendered
  config/main.py
  tests/config_test.py
Labels: Bug, pfcwd, Request for 202012 branch, Request for 202106 branch, Request for 202111 branch
