Repository sonic-net/sonic-utilities, pull requests merged in 2021-03, with the labels that each got.

#1471 [config] Enable/disable container monitoring when starting/stopping the services.
  config/main.py
  tests/config_test.py
Labels: Enhancement, Request for 202012 branch, config

#1469 [acl-loader] Add support for matching on ICMP and VLAN info
  acl_loader/main.py
  tests/acl_input/acl1.json
  tests/acl_input/illegal_icmp_code_300.json
  tests/acl_input/illegal_icmp_code_nan.json
  tests/acl_input/illegal_icmp_code_neg_1.json
  tests/acl_input/illegal_icmp_type_300.json
  tests/acl_input/illegal_icmp_type_nan.json
  tests/acl_input/illegal_icmp_type_neg_1.json
  tests/acl_input/illegal_vlan_0.json
  tests/acl_input/illegal_vlan_9000.json
  tests/acl_input/illegal_vlan_nan.json
  tests/acl_loader_test.py
  tests/aclshow_test.py
  tests/mock_tables/config_db.json
Labels: Enhancement, Request for 201911 Branch, Request for 202012 branch, acl-loader/aclshow

#1470 [Mellanox] Change mellanox buffer migrator for new SKU Mellanox-SN2700-D40C8S8
  scripts/mellanox_buffer_migrator.py
  tests/db_migrator_input/appl_db/mellanox-sn2700-d40c8s8-t0-version_1_0_5.json
  tests/db_migrator_input/appl_db/mellanox-sn2700-d40c8s8-t0-version_2_0_0.json
  tests/db_migrator_input/appl_db/mellanox-sn2700-d40c8s8-t1-version_1_0_5.json
  tests/db_migrator_input/appl_db/mellanox-sn2700-d40c8s8-t1-version_2_0_0.json
  tests/db_migrator_input/config_db/mellanox-sn2700-d40c8s8-t0-version_1_0_5.json
  tests/db_migrator_input/config_db/mellanox-sn2700-d40c8s8-t0-version_2_0_0.json
  tests/db_migrator_input/config_db/mellanox-sn2700-d40c8s8-t1-version_1_0_5.json
  tests/db_migrator_input/config_db/mellanox-sn2700-d40c8s8-t1-version_2_0_0.json
  tests/db_migrator_test.py
Labels: Platform: Mellanox, Request for 201911 Branch, Request for 202012 branch

#1465 [config reload]: On dual ToR systems, cache ARP and FDB tables
  config/main.py
Labels: Request for 202012 branch

#1475 [acl] Expand VLAN into VLAN members when creating an ACL table
  config/main.py
  doc/Command-Reference.md
  tests/acl_config_test.py
  tests/mock_tables/config_db.json
  tests/vlan_test.py
Labels: Enhancement, Request for 201911 Branch, Request for 202012 branch, config

#1476 [201911][acl-loader] Add support for matching on ICMP and VLAN info
  acl_loader/main.py
  sonic-utilities-tests/acl_input/acl1.json
  sonic-utilities-tests/acl_input/illegal_icmp_code_300.json
  sonic-utilities-tests/acl_input/illegal_icmp_code_nan.json
  sonic-utilities-tests/acl_input/illegal_icmp_code_neg_1.json
  sonic-utilities-tests/acl_input/illegal_icmp_type_300.json
  sonic-utilities-tests/acl_input/illegal_icmp_type_nan.json
  sonic-utilities-tests/acl_input/illegal_icmp_type_neg_1.json
  sonic-utilities-tests/acl_input/illegal_vlan_0.json
  sonic-utilities-tests/acl_input/illegal_vlan_9000.json
  sonic-utilities-tests/acl_input/illegal_vlan_nan.json
  sonic-utilities-tests/acl_loader_test.py
  sonic-utilities-tests/aclshow_test.py
  sonic-utilities-tests/mock_tables/config_db.json
Labels: Included in 201911 Branch, acl-loader/aclshow

#1477 [201911][acl] Expand VLAN into VLAN members when creating an ACL table
  config/main.py
  doc/Command-Reference.md
  sonic-utilities-tests/acl_config_test.py
  sonic-utilities-tests/mock_tables/config_db.json
Labels: acl-loader/aclshow, config

#1479 [acl-loader] Improve input validation for acl_loader
  acl_loader/main.py
  tests/acl_input/acl1.json
  tests/acl_input/icmp_bad_protocol_number.json
  tests/acl_input/icmpv6_bad_protocol_number.json
  tests/acl_input/tcp_bad_protocol_number.json
  tests/acl_loader_test.py
  tests/mock_tables/config_db.json
Labels: Bug, Request for 201911 Branch, Request for 202012 branch, acl-loader/aclshow

#1481 [201911][acl-loader] Improve input validation for acl_loader
  acl_loader/main.py
  sonic-utilities-tests/acl_input/acl1.json
  sonic-utilities-tests/acl_input/icmp_bad_protocol_number.json
  sonic-utilities-tests/acl_input/icmpv6_bad_protocol_number.json
  sonic-utilities-tests/acl_input/tcp_bad_protocol_number.json
  sonic-utilities-tests/acl_loader_test.py
  sonic-utilities-tests/mock_tables/config_db.json
Labels: Bug, Included in 201911 Branch, acl-loader/aclshow

#1468 [CLI][techsupport] Merge 'show techsupport' changes from master
  scripts/generate_dump
  show/main.py
Labels: Request for 201911 Branch

#1474 [201811] Warmboot script improvements - timeout in exec and disable swss autorestart
  scripts/fast-reboot
Labels: Enhancement, Included in 201811 Branch, fast-reboot

#1449 [201911] Add soft-reboot reboot type
  scripts/soft-reboot
Labels: Enhancement, Included in 201911 Branch, reboot

#1467 [show][config] fix show mux status health field; add support for hwmode functionality to toggle mux, check mux direction for Y cable
  config/muxcable.py
  show/muxcable.py
  tests/mock_tables/state_db.json
  tests/muxcable_test.py
  utilities_common/platform_sfputil_helper.py
Labels: Request for 202012 branch

#1485 [PDDF] Remove references to deprecated platform plugins
  pddf_fanutil/main.py
  pddf_ledutil/main.py
  pddf_psuutil/main.py
  pddf_thermalutil/main.py
  utilities_common/util_base.py
Labels: Cleanup :droplet:, PDDF

#1451 [pytest] Increase verbosity
  pytest.ini
Labels: Unit Tests

#1494 [show][config] fix for show/config muxcable hwmode model value; fix show/config muxcable return codes;
  config/muxcable.py
  show/muxcable.py
  tests/mock_tables/state_db.json
  tests/muxcable_test.py
Labels: Request for 202012 branch

#1496 [warm-reboot] Fix key error - check empty key before issuing redis hget
  scripts/fast-reboot
Labels: Bug, Request for 202012 branch

#1482 [generate-dump] Remove Arista specific logic
  scripts/generate_dump
Labels: Cleanup :droplet:, Request for 202012 branch

#1352 [201911 SKU creator] fix wrong speed in case breakout of 2x50
  scripts/sonic_sku_create.py
  setup.py
  sonic-utilities-tests/sku_create_input/2700_files/ACS-MSN2700/buffers.json.j2
  sonic-utilities-tests/sku_create_input/2700_files/ACS-MSN2700/buffers_defaults_t0.j2
  sonic-utilities-tests/sku_create_input/2700_files/ACS-MSN2700/buffers_defaults_t1.j2
  sonic-utilities-tests/sku_create_input/2700_files/ACS-MSN2700/pg_profile_lookup.ini
  sonic-utilities-tests/sku_create_input/2700_files/ACS-MSN2700/port_config.ini
  sonic-utilities-tests/sku_create_input/2700_files/ACS-MSN2700/qos.json
  sonic-utilities-tests/sku_create_input/2700_files/ACS-MSN2700/qos.json.j2
  sonic-utilities-tests/sku_create_input/2700_files/ACS-MSN2700/sai.profile
  sonic-utilities-tests/sku_create_input/2700_files/ACS-MSN2700/sai_2700.xml
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-C28D8-ORIG/buffers.json.j2
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-C28D8-ORIG/buffers_defaults_t0.j2
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-C28D8-ORIG/buffers_defaults_t1.j2
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-C28D8-ORIG/pg_profile_lookup.ini
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-C28D8-ORIG/port_config.ini
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-C28D8-ORIG/qos.json.j2
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-C28D8-ORIG/sai.profile
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-C28D8-ORIG/sai_2700_8x50g_28x100g.xml
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-D48C8.xml
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-D48C8/buffers.json.j2
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-D48C8/buffers_defaults_t0.j2
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-D48C8/buffers_defaults_t1.j2
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-D48C8/pg_profile_lookup.ini
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-D48C8/port_config.ini
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-D48C8/port_config.ini.bak
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-D48C8/port_config.ini.new
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-D48C8/port_config.ini.orig
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-D48C8/qos.json
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-D48C8/qos.json.j2
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-D48C8/sai.profile
  sonic-utilities-tests/sku_create_input/2700_files/Mellanox-SN2700-D48C8/sai_2700_48x50g_8x100g.xml
  sonic-utilities-tests/sku_create_input/2700_files/config_db.json
  sonic-utilities-tests/sku_create_input/2700_files/default_sku
  sonic-utilities-tests/sku_create_input/3800_files/ACS-MSN3800/buffers_defaults_t0.j2
  sonic-utilities-tests/sku_create_input/3800_files/ACS-MSN3800/buffers_defaults_t1.j2
  sonic-utilities-tests/sku_create_input/3800_files/ACS-MSN3800/pg_profile_lookup.ini
  sonic-utilities-tests/sku_create_input/3800_files/ACS-MSN3800/port_config.ini
  sonic-utilities-tests/sku_create_input/3800_files/ACS-MSN3800/sai.profile
  sonic-utilities-tests/sku_create_input/3800_files/ACS-MSN3800/sai_3800.xml
  sonic-utilities-tests/sku_create_input/3800_files/Mellanox-SN3800-D28C50/buffers.json.j2
  sonic-utilities-tests/sku_create_input/3800_files/Mellanox-SN3800-D28C50/buffers_defaults_t0.j2
  sonic-utilities-tests/sku_create_input/3800_files/Mellanox-SN3800-D28C50/buffers_defaults_t1.j2
  sonic-utilities-tests/sku_create_input/3800_files/Mellanox-SN3800-D28C50/pg_profile_lookup.ini
  sonic-utilities-tests/sku_create_input/3800_files/Mellanox-SN3800-D28C50/port_config.ini
  sonic-utilities-tests/sku_create_input/3800_files/Mellanox-SN3800-D28C50/qos.json.j2
  sonic-utilities-tests/sku_create_input/3800_files/Mellanox-SN3800-D28C50/sai.profile
  sonic-utilities-tests/sku_create_input/3800_files/Mellanox-SN3800-D28C50/sai_3800_28x50g_52x100g.xml
  sonic-utilities-tests/sku_create_input/3800_files/default_sku
  sonic-utilities-tests/sku_create_input/3800_files/t0-1-06-minigraph.xml
  sonic-utilities-tests/sku_create_input/ACS-MSN2700/pg_profile_lookup.ini
  sonic-utilities-tests/sku_create_input/ACS-MSN2700/port_config.ini
  sonic-utilities-tests/sku_create_input/ACS-MSN2700/sai.profile
  sonic-utilities-tests/sku_create_input/Mellanox-SN2700-D48C8/pg_profile_lookup.ini
  sonic-utilities-tests/sku_create_input/Mellanox-SN2700-D48C8/port_config.ini.orig
  sonic-utilities-tests/sku_create_test.py
Labels: Bug, Included in 201911 Branch

#1500 [reboot]: Stop mux before reboot on dual ToR
  scripts/reboot
Labels: Enhancement, Request for 202012 branch, reboot

#1502 Add self timeout and crash if exceeded.
  scripts/route_check.py
  tests/route_check_test.py
Labels: Enhancement

#1499 [config] Disable/enable container monitoring when stopping/starting services
  config/main.py
Labels: Enhancement, Request for 202012 branch, config

#1503 Fix bug: show vlan config for vlan with no members
  show/vlan.py
  tests/vlan_test.py
Labels: Request for 202012 branch

#1501 [show][config] add support for setting and displaying switching modes on Y cable
  config/muxcable.py
  show/muxcable.py
Labels: Request for 202012 branch, config, show

#1520 route_check: Fix hanging & logging level
  scripts/route_check.py
  tests/route_check_test.py
Labels: Bug, Request for 202012 branch

#1478 [show] Fix int status of LAGs, configured as Vlan members
  scripts/intfutil
  tests/intfutil_test.py
  tests/mock_tables/asic0/config_db.json
  tests/mock_tables/config_db.json
  tests/multi_asic_intfutil_test.py
  tests/vlan_test.py
Labels: Request for 202012 branch

#1495 Warmboot script improvements - timeout exec, disable swss autorestart, remove trap
  scripts/fast-reboot
Labels: Request for 201911 Branch, Request for 202012 branch

#1508 Enable PFCWD only on ports where PFC is enabled
  pfcwd/main.py
  tests/mock_tables/asic0/config_db.json
  tests/mock_tables/asic1/config_db.json
  tests/mock_tables/config_db.json
  tests/pfcwd_input/pfcwd_test_vectors.py
  tests/pfcwd_test.py
Labels: Bug, Request for 202012 branch

#1464 Modified the tests to use mock functionality of get_child_port function under portconfig utility
  tests/config_dpb_test.py
Labels: Unit Tests, config

#1525 [201811] Add missing variable DEVPATH to fast-reboot script
  scripts/fast-reboot
Labels: Bug, Included in 201811 Branch

#1526 [201811] Fast reboot: check if the files are present before accessing
  scripts/fast-reboot
Labels: Included in 201811 Branch

#1522 Copy missing values from INIT_CFG to config_db during db_migration
  config/main.py
  scripts/db_migrator.py
  sonic-utilities-tests/db_migrator_test.py
Labels: Request for 201911 Branch

#1486 [reboot] User-friendly reboot cause message for kernel panic
  scripts/reboot
  show/reboot_cause.py
  tests/reboot_cause_test.py
Labels: Enhancement, Request for 202012 branch

#1436 [ci]: add vstest
  .azure-pipelines/build-docker-sonic-vs-template.yml
  .azure-pipelines/build_and_install_module.sh
  .azure-pipelines/docker-sonic-vs/Dockerfile
  .azure-pipelines/test-docker-sonic-vs-template.yml
  azure-pipelines.yml
Labels: CI
