Repository sonic-net/sonic-utilities, pull requests merged in 2021-04, with the labels that each got.

#1393 [fast-reboot] Fix dump script to support PortChannels in a VLAN group
  scripts/fast-reboot-dump.py
  setup.py
  tests/fast_reboot_dump_dbs/APPL_DB.json
  tests/fast_reboot_dump_dbs/ASIC_DB.json
  tests/fast_reboot_dump_test.py
Labels: Request for 202012 branch

#1541 [ci]: use docker-sonic-vs from sonic-swss repo
  .azure-pipelines/build-docker-sonic-vs-template.yml
  azure-pipelines.yml
Labels: CI

#1542 [setup.py]: move the module to test requirement
  setup.py
Labels: Bug

#1538 [reboot] No need enable the Linux magic system request key
  scripts/reboot
Labels: Request for 202012 branch

#1544 Reduce time taken by show commands on multi-asic platforms
  utilities_common/multi_asic.py
Labels: Request for 201911 Branch

#1543 [config] Eliminate race condition between reloading Monit config and monitoring container_checker
  config/main.py
Labels: Bug, Request for 202012 branch

#1548 [201811] Fix fast-reboot fdb filtering for IPv6 addresses
  fdbutil/filter_fdb_entries.py
Labels: Request for 201811 Branch

#1528 [show][config] cli support for firmware upgrade on Y-Cable
  config/muxcable.py
  show/muxcable.py
  tests/muxcable_test.py
Labels: Request for 202012 branch, config, show

#1546 [fast-reboot] Fix fast-reboot-dump.py SonicV2Connector after late merge
  scripts/fast-reboot-dump.py
Labels: Request for 202012 branch

#1533 [fwutil]: Fix next image mount
  fwutil/lib.py
Labels: Bug, Request for 202012 branch

#1551 Fixed the possibility of using uninitialized variable in route_check.py
  scripts/route_check.py
Labels: Bug, Request for 201911 Branch, Request for 202012 branch

#1450 Use 'importlib' module in lieu of deprecated 'imp' module
  config/config_mgmt.py
  pfcwd/main.py
  tests/aclshow_test.py
  tests/buffer_test.py
  tests/config_dpb_test.py
  tests/config_mgmt_test.py
  tests/config_test.py
  tests/crm_test.py
  tests/decode_syseeprom_test.py
  tests/feature_test.py
  tests/neighbor_advertiser_test.py
  tests/pfcstat_test.py
  tests/pfcwd_test.py
  tests/port2alias_test.py
  tests/psushow_test.py
  tests/watermarkstat_test.py
  utilities_common/general.py
  utilities_common/util_base.py
Labels: Cleanup :droplet:, Request for 202012 branch

#1552 Prevent starting PFCWD for EPMS devicetype
  config/main.py
Labels: Request for 201811 Branch

#1553 sonic-installer: fix py3 issues in bootloader.aboot
  sonic_installer/bootloader/aboot.py
Labels: Request for 202012 branch

#1514 Stop PMON docker before cold and soft reboots
  scripts/reboot
  scripts/soft-reboot
Labels: Enhancement, Request for 201911 Branch, Request for 202012 branch, reboot

#1562 [techsupport] Update show ip interface command
  scripts/generate_dump
Labels: Request for 201911 Branch, Request for 202012 branch

#1565 route_check: Updates
  scripts/route_check.py
  tests/route_check_test.py
Labels: Bug, Enhancement, Request for 201911 Branch, Request for 202012 branch

#1515 [201811] Stop PMON docker before cold boot and soft reboot
  scripts/reboot
  scripts/soft-reboot
Labels: Enhancement, Included in 201811 Branch, reboot

#1519 [acl] Use a list instead of a comma-separated string for ACL port list
  config/main.py
  tests/acl_config_test.py
Labels: Bug, Request for 201911 Branch, Request for 202012 branch

#1576 [201911][acl] Use a list instead of a comma-separated string for ACL port list
  config/main.py
  sonic-utilities-tests/acl_config_test.py
Labels: Bug, Included in 201911 Branch, config

#1579 [console] Display success message after line cleared
  consutil/main.py
  tests/console_test.py
Labels: Enhancement, clear

#1569 disk_check: Check & mount RO as RW using tmpfs
  scripts/disk_check.py
  setup.py
  tests/disk_check_test.py
Labels: Enhancement, Request for 201911 Branch, Request for 202012 branch

#1527 [sonic-package-manager] first phase implementation of sonic-package-manager
  doc/Command-Reference.md
  setup.py
  sonic-utilities-data/bash_completion.d/sonic-package-manager
  sonic-utilities-data/bash_completion.d/spm
  sonic-utilities-data/templates/dump.sh.j2
  sonic-utilities-data/templates/service_mgmt.sh.j2
  sonic-utilities-data/templates/sonic.service.j2
  sonic-utilities-data/templates/timer.unit.j2
  sonic_installer/bootloader/aboot.py
  sonic_installer/bootloader/bootloader.py
  sonic_installer/common.py
  sonic_installer/main.py
  sonic_package_manager/__init__.py
  sonic_package_manager/constraint.py
  sonic_package_manager/database.py
  sonic_package_manager/dockerapi.py
  sonic_package_manager/errors.py
  sonic_package_manager/logger.py
  sonic_package_manager/main.py
  sonic_package_manager/manager.py
  sonic_package_manager/manifest.py
  sonic_package_manager/metadata.py
  sonic_package_manager/package.py
  sonic_package_manager/progress.py
  sonic_package_manager/reference.py
  sonic_package_manager/registry.py
  sonic_package_manager/service_creator/__init__.py
  sonic_package_manager/service_creator/creator.py
  sonic_package_manager/service_creator/feature.py
  sonic_package_manager/service_creator/sonic_db.py
  sonic_package_manager/service_creator/utils.py
  sonic_package_manager/source.py
  sonic_package_manager/utils.py
  sonic_package_manager/version.py
  tests/sonic_package_manager/conftest.py
  tests/sonic_package_manager/test_cli.py
  tests/sonic_package_manager/test_constraint.py
  tests/sonic_package_manager/test_database.py
  tests/sonic_package_manager/test_manager.py
  tests/sonic_package_manager/test_manifest.py
  tests/sonic_package_manager/test_metadata.py
  tests/sonic_package_manager/test_reference.py
  tests/sonic_package_manager/test_registry.py
  tests/sonic_package_manager/test_service_creator.py
  tests/sonic_package_manager/test_utils.py
Labels: appext

#1584 [show] revert back to swsssdk from swsscommon for ConfigDBConnector() for muxcable
  show/muxcable.py
Labels: Bug, Included in 202012 branch, show
