Repository sonic-net/sonic-utilities, pull requests merged in 2021-12, with the labels that each got.

#1948 [Auto-Techsupport] Issues related to Multiple Cores crashing handled
  scripts/coredump_gen_handler.py
  scripts/generate_dump
  scripts/techsupport_cleanup.py
  tests/coredump_gen_handler_test.py
  utilities_common/auto_techsupport_helper.py
Labels: Request for 202111 branch

#1857 [config] Add portchannel support for static route
  config/main.py
  tests/static_routes_test.py
Labels: Request for 202106 branch

#1947 [sfputil] Firmware download/upgrade CLI support for QSFP-DD
  sfputil/main.py
  tests/sfputil_test.py
Labels: Feature Request :rocket:

#1945 [202012] [generate_dump] allow to extend dump with plugin scripts
  scripts/generate_dump
Labels: Request for 201911 Branch

#1964 preserve old order for config reload
  config/main.py
Labels: Request for 202111 branch

#1971 [build] adapt for upstream target path change
  azure-pipelines.yml
Labels: CI

#1840 [portstat] check TX/RX utilization calculation correctness
  tests/mock_tables/counters_db.json
  tests/portstat_test.py
Labels: Request for 202106 branch

#1611 [config] Fix 'config reload -l' command to get filename by default
  config/main.py
  tests/config_reload_input/config_db.json
  tests/config_reload_input/init_cfg.json
  tests/config_test.py
Labels: Request for 202111 branch

#1438 [doc|DPB] Update DPB related interface breakout command Info
  doc/Command-Reference.md
Labels: Request for 202111 branch

#1765 [breakout] Fix the check when port is not present in BREAKOUT_CFG table
  show/interfaces/__init__.py
  tests/show_breakout_test.py
Labels: Request for 202111 branch

#1978 Fix wrong help message for cable length setting
  config/main.py
Labels: Request for 202106 branch, Request for 202111 branch
