Repository sonic-net/sonic-utilities, pull requests merged in 2022-04, with the labels that each got.

#2122 [QoS] Fix issues in clear_qos
  config/main.py
Labels: Bug, Request for 202012 branch, Request for 202111 branch

#2114 [techsupport] Handle minor fixes of TS Lock and update auto-TS
  scripts/coredump_gen_handler.py
  scripts/generate_dump
  tests/coredump_gen_handler_test.py
  utilities_common/auto_techsupport_helper.py
Labels: Request for 202111 branch

#2066 [config/config_mgmt.py]: Fix dpb issue with upper case mac in device_metadata.
  config/config_mgmt.py
  tests/config_mgmt_test.py
Labels: Request for 202111 branch

#2132 [scripts/fast-reboot] cleanup
  scripts/fast-reboot
Labels: Request for 202111 branch

#2131 [scripts/fast-reboot] stop timers in advance
  scripts/fast-reboot
Labels: Request for 202012 branch, Request for 202111 branch

#2136 [config] Do not enable pfcwd for BmcMgmtToRRouter
  config/main.py
Labels: Request for 202012 branch

#2110 [intfutil] Display RJ45 port and portchannel speed in 'M' instead of 'G' when it's <= 1000M
  scripts/intfutil
  tests/intfutil_test.py
  tests/mock_tables/appl_db.json
  tests/mock_tables/config_db.json
  tests/mock_tables/state_db.json
  tests/tpid_test.py
Labels: Enhancement

#2117 [techsupport] improve robustness
  scripts/generate_dump
  show/main.py
  tests/techsupport_test.py
Labels: Request for 202111 branch

#2112 Enhance "config interface type/advertised-type" to be blocked on RJ45 ports
  scripts/portconfig
  tests/config_an_test.py
Labels: Enhancement

#2107 [Mellanox] [reboot] [asan] stop asan-enabled containers on reboot
  scripts/reboot
Labels: Platform: Mellanox

#2040 Allow fw update for other boot type against on the previous "none" boot fw update
  fwutil/lib.py
  fwutil/main.py
Labels: Request for 202106 branch, Request for 202111 branch
