Repository sonic-net/sonic-utilities, pull requests merged in 2022-09, with the labels that each got.

#2346 [route_check]: Ignore standalone tunnel routes
  scripts/route_check.py
  scripts/route_check_test.sh
  tests/config_test.py
  tests/mock_tables/config_db.json
  tests/route_check_test.py
Labels: Included in 202205 branch

#2338 Add Password hardening CLI support
  config/plugins/sonic-passwh_yang.py
  show/plugins/sonic-passwh_yang.py
  tests/passw_hardening_input/assert_show_output.py
  tests/passw_hardening_input/default_config_db.json
  tests/passw_hardening_test.py
Labels: Request for 202205 branch

#2335 [fast-reboot]Avoid stopping masked services during fast-reboot
  scripts/fast-reboot
Labels: Request for 202205 branch

#2355 [counterpoll]Fixing counterpoll show for tunnel and acl stats
  counterpoll/main.py
  tests/counterpoll_test.py
  tests/mock_tables/config_db.json
Labels: Request for 202205 branch

#2356 [generate dump]Added error message when saisdkdump fails
  scripts/generate_dump
Labels: Request for 202205 branch

#2345 [subinterface]Added additional checks in portchannel and subinterface commands
  config/main.py
  tests/intfutil_test.py
  tests/ip_config_test.py
  tests/loopback_action_test.py
  tests/mock_tables/appl_db.json
  tests/mock_tables/config_db.json
  tests/portchannel_test.py
  tests/show_vrf_test.py
  tests/static_routes_test.py
  tests/subintf_test.py
  tests/vrf_input/config_db.json
Labels: Request for 202205 branch

#2341 Added support for tunnel route status in show vnet routes all.
  doc/Command-Reference.md
  show/vnet.py
  tests/mock_tables/appl_db.json
  tests/mock_tables/state_db.json
  tests/show_vnet_test.py
Labels: Request for 202205 branch

#2281 Vnet_route_check Vxlan tunnel route update.
  scripts/vnet_route_check.py
  tests/vnet_route_check_test.py
Labels: Request for 202205 branch

#2374 Fix typo in platform_sfputil_helper.is_rj45_port
  utilities_common/platform_sfputil_helper.py
Labels: Bug, Request for 202205 branch

#2367 [warm-reboot] fix warm-reboot when /tmp/cache is missing
  scripts/fast-reboot
Labels: Bug

#2343 [GCU]Remove GCU unique lane check for duplicate lanes platforms
  generic_config_updater/gu_common.py
Labels: Request for 202205 branch

#2350 [minigraph] add option to specify golden path in load_minigraph
  config/main.py
  tests/config_test.py
Labels: Request for 202205 branch

#2394 [link-local]Modify RIF check to include link-local enabled interfaces
  tests/ipv6_link_local_test.py
  tests/mock_tables/config_db.json
  utilities_common/cli.py
Labels: Request for 202205 branch

#2395 [202012] [generate_dump]: Enhance show techsupport for cisco-8000 pla…
  scripts/generate_dump
Labels: Request for 202012 branch, Request for 202205 branch

#2398 [Vxlanmgrd] [CPA] Update the vxlan_tunnel name len to be under IFNAMIZ to overcome netdev creation failure
  scripts/neighbor_advertiser
Labels: Request for 202205 branch

#2409 [doc] update "config feature" section with "--block" option
  doc/Command-Reference.md
Labels: Request for 202205 branch

#2411 [doc] add documentation on automatic techsupport based on memory availability
  doc/Command-Reference.md
Labels: Request for 202205 branch

#2404 [VxLAN]Fix Vxlan delete command to throw error when there are references
  config/vxlan.py
  tests/vnet_input/config_db.json
  tests/vxlan_test.py
Labels: Request for 202012 branch, Request for 202205 branch

#2391 Fix for show vxlan tunnel command display issue #11902
  show/vxlan.py
  tests/vxlan_test.py
Labels: Request for 202205 branch

#2388 check for vxlan mapping before removing vlan
  config/vlan.py
  tests/vlan_test.py
Labels: Request for 202205 branch
