Repository sonic-net/sonic-utilities, pull requests merged in 2022-12, with the labels that each got.

#2503 [QoS] Introduce delay to the qos reload flow
  config/main.py
  tests/config_test.py
Labels: Bug, Request for 202205 branch

#2500 [GCU] Add RemoveCreateOnlyDependency Validator/Generator
  generic_config_updater/patch_sorter.py
  tests/generic_config_updater/files/config_db_with_port_critical.json
  tests/generic_config_updater/files/patch_sorter_test_success.json
  tests/generic_config_updater/patch_sorter_test.py
Labels: Request for 202205 branch

#2535 Transceiver eeprom dom CLI modification to show output from TRANSCEIVER_DOM_THRESHOLD table
  scripts/sfpshow
  tests/mock_tables/asic0/state_db.json
  tests/mock_tables/asic1/state_db.json
  tests/mock_tables/state_db.json
Labels: Enhancement

#2539 [config]Block adding IP address on portchannel member
  config/main.py
  tests/ip_config_test.py
Labels: Request for 202205 branch

#2548 [route_check]: Ignore ASIC only SOC IPs
  scripts/route_check.py
  tests/mock_tables/config_db.json
  tests/route_check_test.py
  tests/route_check_test_data.py
Labels: Request for 202111 branch, Request for 202205 branch

#2547 [202205][show]Fix show route return code on error
  config/main.py
  config/vlan.py
  show/kdump.py
  tests/config_test.py
  tests/conftest.py
  tests/ip_config_test.py
  tests/ip_show_routes_test.py
  tests/vlan_test.py
  utilities_common/bgp_util.py
  utilities_common/cli.py
Labels: Request for 202205 branch

#2553 [muxcable][show] update `show mux tunnel-route` to separate ASIC and kernel into two columns
  show/muxcable.py
  tests/mock_tables/asic_db.json
  tests/muxcable_test.py
Labels: Request for 202205 branch

#2504 [generate_dump] Optimize the execution time of the 'show techsupport' script to 5-10% by reducing calls to the 'tar append' operation
  scripts/generate_dump
Labels: Request for 202205 branch

#2560 [db_migrator] Fix migration of Loopback data: handle all Loopback interfaces
  scripts/db_migrator.py
  tests/db_migrator_input/appl_db/loopback_interface_migrate_from_1_0_1_expected.json
  tests/db_migrator_input/appl_db/loopback_interface_migrate_from_1_0_1_input.json
  tests/db_migrator_input/config_db/loopback_interface_migrate_from_1_0_1_expected.json
  tests/db_migrator_input/config_db/loopback_interface_migrate_from_1_0_1_input.json
  tests/db_migrator_test.py
Labels: Request for 202012 branch, Request for 202205 branch

#2513 Fixes #12170: Delete subinterface and recreate the subinterface in
  config/main.py
  tests/vrf_test.py
Labels: Request for 202205 branch, Request for 202211 branch

#2490 [202012]Revert "[config reload]: On dual ToR systems, cache ARP and FDB table…
  config/main.py
  tests/pgdropstat_test.py
Labels: Request for 202012 branch

#2556 Fix issue: unconfigured PGs are displayed in watermarkstat
  scripts/pg-drop
  scripts/watermarkstat
Labels: Request for 202205 branch, Request for 202211 branch

#2569 [Mellanox] Change severity to NOTICE in Mellanox buffer migrator when unable to fetch DEVICE_METADATA due to empty CONFIG_DB during initialization
  scripts/mellanox_buffer_migrator.py
Labels: Request for 202205 branch, Request for 202211 branch
