Repository sonic-net/sonic-utilities, pull requests merged in 2022-11, with the labels that each got.

#2373 Fix sudo sfputil show error-status on a multiasic platform issue
  sfputil/main.py
  tests/sfputil_test.py
Labels: Chassis, Request for 202205 branch

#2477 [GCU] Fix JsonPointerFilter bug
  generic_config_updater/patch_sorter.py
  tests/generic_config_updater/patch_sorter_test.py
Labels: Request for 202205 branch

#2456 Do not configure physical attributes on port channels in portconfig
  scripts/portconfig
  tests/config_an_test.py
  tests/config_lt_test.py
  tests/config_xcvr_test.py
Labels: Bug, Request for 202205 branch

#2502 avoid printing error if no neighbors are present
  tests/bgp_commands_test.py
  tests/conftest.py
  utilities_common/bgp_util.py
Labels: Request for 201911 Branch, Request for 202012 branch, Request for 202205 branch

#2422 [show][multiasic]Fixed SONIC_CLI_IFACE_MODE=alias show ip|ipv6 route output in default mode issue
  show/bgp_common.py
  tests/conftest.py
  tests/ip_show_routes_multi_asic_test.py
  tests/ip_show_routes_test.py
  tests/mock_tables/asic0/config_db.json
  tests/show_ip_route_common.py
  utilities_common/bgp_util.py
  utilities_common/cli.py
Labels: Chassis, Request for 202205 branch

#2507 Show tech save file to skip non-file entries in cisco-8000 platform
  scripts/generate_dump
Labels: Request for 202012 branch, Request for 202205 branch

#2491 [sfp] Fix issue: Application Advertisement is not well formatted
  scripts/sfpshow
  sfputil/main.py
  tests/mock_tables/state_db.json
  tests/sfp_test.py
  tests/sfputil_test.py
  utilities_common/sfp_helper.py
Labels: Enhancement

#2326 [psushow & psuutil] Support PSU power threshold checking
  doc/Command-Reference.md
  psuutil/main.py
  scripts/psushow
  tests/mock_tables/state_db.json
  tests/psushow_test.py
  tests/psuutil_test.py
Labels: Enhancement

#2506 [VXLAN]Fixing traceback in show remotemac when mac moves during command execution
  show/vxlan.py
  tests/mock_tables/appl_db.json
  tests/vxlan_test.py
Labels: Request for 202205 branch

#2517 Change show kube command default value of insecure key to True
  show/kube.py
  tests/kube_test.py
Labels: Request for 202012 branch, Request for 202205 branch
