Repository sonic-net/sonic-utilities, pull requests merged in 2022-06, with the labels that each got.

#2141 Add check to not allow deleting PO if its member of vlan.
  .DS_Store
  config/main.py
  tests/portchannel_test.py
Labels: Request for 202111 branch

#2189 [config][muxcable] Add support for displaying soc_ipv4 and cable_type in config/show muxcable commands
  config/muxcable.py
  show/muxcable.py
  tests/mock_tables/config_db.json
  tests/muxcable_test.py
  utilities_common/general.py
Labels: Requested for 202205 branch

#2193 [yang] remove mistakenly added parameter for 'get_module_name'
  config/config_mgmt.py
  tests/config_mgmt_test.py
Labels: Request for 202111 branch

#1813 [gendump] Add Support to dump BCM-DNX commands
  scripts/generate_dump
Labels: Chassis

#2210 [config][muxcable] fix minor config DB logic issue
  config/muxcable.py
Labels: Requested for 202205 branch

#2200 [config reload] Fixing config reload when timer based services are disabled
  config/main.py
  tests/config_test.py
Labels: Requested for 202205 branch

#1827 Add an option in queue stat to display voq counters.
  scripts/queuestat
  show/main.py
  tests/mock_tables/counters_db.json
  tests/queue_counter_test.py
Labels: Chassis

#2209 [generate dump] Move the Core/Log collection to the End of process Execution and removed default timeout
  scripts/generate_dump
  show/main.py
  tests/coredump_gen_handler_test.py
  tests/techsupport_test.py
  utilities_common/auto_techsupport_helper.py
Labels: Requested for 202205 branch

#2172 Image-installer: Fix duplication of image prefix
  sonic_installer/bootloader/aboot.py
  sonic_installer/bootloader/bootloader.py
  sonic_installer/bootloader/grub.py
  sonic_installer/bootloader/onie.py
  sonic_installer/bootloader/uboot.py
  sonic_installer/main.py
  tests/installer_bootloader_aboot_test.py
  tests/installer_bootloader_bootloader_test.py
  tests/installer_bootloader_grub_test.py
  tests/installer_bootloader_onie_test.py
  tests/installer_bootloader_uboot_test.py
Labels: Requested for 202205 branch

#2237 [202205] Add check to not allow deleting PO if its member of vlan
  config/main.py
  tests/portchannel_test.py
Labels: Included in 202205 branch
