Repository sonic-net/sonic-utilities, pull requests merged in 2022-08, with the labels that each got.

#2293 [crm] add CLI validation for CRM polling interval range
  crm/main.py
  tests/crm_test.py
Labels: Request for 202205 branch

#2295 Fix GCU bug when backend service modifying config
  generic_config_updater/change_applier.py
  generic_config_updater/generic_updater.py
Labels: Request for 202205 branch

#2297 [config][muxcable] add support to enable/disable ycable telemetry
  config/muxcable.py
  tests/muxcable_test.py
Labels: Request for 202012 branch, Request for 202205 branch

#2303 Support to enable fips for the command sonic_installer (#2154)
  sonic_installer/bootloader/aboot.py
  sonic_installer/bootloader/bootloader.py
  sonic_installer/bootloader/grub.py
  sonic_installer/bootloader/uboot.py
  sonic_installer/main.py
  tests/installer_bootloader_aboot_test.py
  tests/installer_bootloader_grub_test.py
  tests/installer_bootloader_input/host/grub/grub.cfg
  tests/installer_bootloader_uboot_test.py
  tests/test_sonic_installer.py
Labels: Included in 202205 branch

#2299 Convert IPv6 addresses to lowercase in apply-patch
  config/main.py
  tests/ip_config_input/patch_ipv6.test
  tests/ip_config_test.py
Labels: Request for 202205 branch

#2244 Delete .DS_Store
  .DS_Store
Labels: Request for 202111 branch

#2313 Fix issue: exception in is_rj45_port in multi ASIC env
  utilities_common/platform_sfputil_helper.py
Labels: Request for 202205 branch

#2323 Fix issue: port_type is referenced before initialized
  utilities_common/platform_sfputil_helper.py
Labels: Request for 202205 branch

#2319 [service_mgmt]: Fix fetch MULTI_INST_DEPENDENT bug in service_mgmt.sh.j2
  sonic-utilities-data/templates/service_mgmt.sh.j2
Labels: Request for 202205 branch

#2327 Handle non-front-panel ports in is_rj45_port
  utilities_common/platform_sfputil_helper.py
Labels: Request for 202205 branch

#2333 [VRF]Adding CLI checks to ensure Vrf is valid in interface bind and static route commands
  config/main.py
  tests/ip_config_test.py
  tests/static_routes_test.py
Labels: Request for 202205 branch

#2211 Subinterface vrf bind issue fix
  config/main.py
  tests/intfutil_test.py
  tests/ip_config_test.py
  tests/mock_tables/appl_db.json
  tests/mock_tables/config_db.json
  tests/show_vrf_test.py
  tests/subintf_test.py
  tests/vrf_input/config_db.json
Labels: Request for 202205 branch

#2325 [route_check]: Ignore standalone tunnel routes
  scripts/route_check.py
  scripts/route_check_test.sh
  tests/config_test.py
  tests/mock_tables/config_db.json
  tests/route_check_test.py
Labels: Request for 202205 branch
