Repository sonic-net/sonic-utilities, pull requests merged in 2022-10, with the labels that each got.

#2342 [show] vnet endpoint [ip/ipv6] command
  doc/Command-Reference.md
  show/vnet.py
  tests/mock_tables/appl_db.json
  tests/mock_tables/state_db.json
  tests/show_bfd_test.py
  tests/show_vnet_vxlan_cli_test.py
Labels: Request for 202205 branch

#2396 [minigraph] new workflow for golden path
  config/main.py
  tests/config_test.py
Labels: Request for 202205 branch

#2425 [muxcable][config] add CLI support for mux mode detach
  config/muxcable.py
Labels: Request for 202205 branch

#2386 [show priority-group drop counters] show priority-group drop counters] Properly handle missing COUNTERS_PG_PORT_MAP and COUNTERS_PG_NAME_MAP in db
  scripts/pg-drop
  tests/pgdrop_input/counters_db.json
  tests/pgdrop_input/counters_db2.json
  tests/pgdrop_input/counters_db3.json
  tests/pgdrop_input/counters_db4.json
  tests/pgdropstat_test.py
Labels: Request for 202205 branch

#2390 [show] vnet advertised-route command
  show/vnet.py
  tests/mock_tables/appl_db.json
  tests/mock_tables/state_db.json
  tests/show_vnet_test.py
Labels: Request for 202205 branch

#2403 [generate_dump]: Enhance show techsupport for cisco-8000 platform
  scripts/generate_dump
Labels: Request for 202205 branch

#2377 Update sonic command doc to add CLIs relative to SONiC fips
  doc/Command-Reference.md
Labels: Documentation

#1860 [voq] Add fabric counter cli commands
  scripts/fabricstat
  setup.py
  show/fabric.py
  show/main.py
  tests/fabricstat_test.py
  tests/mock_tables/asic0/counters_db.json
  tests/mock_tables/asic0/state_db.json
  tests/mock_tables/asic1/counters_db.json
  tests/mock_tables/asic1/state_db.json
  utilities_common/multi_asic.py
Labels: Chassis, Request for 202205 branch

#2442 [techsupport]Adding FRR evpn dumps
  scripts/generate_dump
Labels: Request for 202205 branch

#2458 Fix exception in adding mirror_session when `gre_type` is absent
  config/main.py
  tests/config_mirror_session_test.py
Labels: Request for 202111 branch, Request for 202205 branch

#2460 Revert "[config reload]: On dual ToR systems, cache ARP and FDB table…
  config/main.py
  tests/config_test.py
Labels: Request for 202012 branch
