Repository sonic-net/sonic-utilities, pull requests merged in 2022-02, with the labels that each got.

#2063 [ci] allow download partially succeeded builds for sonic-swss-pytests artifact
  .azure-pipelines/test-docker-sonic-vs-template.yml
Labels: CI

#2042 [Mellanox] [simx] [techsupport] Avoid running show_platform_info for simx
  scripts/generate_dump
Labels: Bug, Platform: Mellanox, Request for 202111 branch

#2037 [aclshow] fix aclshow when clear is called before counters are populated
  scripts/aclshow
  tests/aclshow_test.py
  tests/mock_tables/config_db.json
  tests/mock_tables/counters_db.json
Labels: Bug, Request for 202111 branch

#2046 [show][config] add muxcable command line support for retrieve / reset ICMP packet loss data
  config/muxcable.py
  show/muxcable.py
  tests/mock_tables/state_db.json
  tests/muxcable_test.py
Labels: config, show

#2082 [counterpoll] Display the correct default poll interval for watermark counters
  counterpoll/main.py
  tests/counterpoll_test.py
  tests/mock_tables/config_db.json
Labels: Bug, show, Request for 202012 branch, Request for 202106 branch, Request for 202111 branch
