Repository sonic-net/sonic-utilities, pull requests merged in 2022-05, with the labels that each got.

#2158 [show][vrf]Fixing show vrf to include vlan subinterface
  doc/Command-Reference.md
  show/main.py
  tests/show_vrf_test.py
  tests/vrf_input/config_db.json
Labels: Request for 202111 branch

#2162 Fix validation of input of `config mirror_session add`
  config/main.py
  tests/config_mirror_session_test.py
Labels: Request for 202012 branch, Request for 202111 branch

#2151 [portchannel] Added ACL/PBH binding checks to the port before getting added to portchannel
  config/main.py
  dump/match_helper.py
  dump/match_infra.py
  tests/mock_tables/config_db.json
  tests/portchannel_test.py
  utilities_common/db.py
  utilities_common/helper.py
Labels: Request for 202111 branch

#2169 [portconfig] Allow to configure interface mtu for physical ports only
  scripts/portconfig
  tests/config_an_test.py
Labels: Bug, Request for 202111 branch

#2176 Add sonic-delayed.target to Application Extension .timer file generator
  sonic-utilities-data/templates/timer.unit.j2
Labels: Request for 202111 branch

#2118 [yang] extend ConfigMgmt constructor to pass YANG options
  config/config_mgmt.py
  sonic_package_manager/manager.py
Labels: Request for 202111 branch

#2180 [subinterface] Fix route add command to accept subinterface as dev
  config/main.py
  doc/Command-Reference.md
  tests/mock_tables/config_db.json
  tests/static_routes_test.py
Labels: Bug
