Repository sonic-net/sonic-utilities, pull requests merged in 2022-01, with the labels that each got.

#1986 [Auto Techsupport] Event driven Techsupport Bug Fixes
  scripts/coredump_gen_handler.py
  tests/coredump_gen_handler_test.py
Labels: Request for 202111 branch

#1967 [config reload] Fixing config reload when timer based delayed services are disabled
  config/main.py
  tests/config_test.py
Labels: Request for 202012 branch, Request for 202106 branch, Request for 202111 branch

#2011 [Bug]: Fix show ip bgp nei command rw required issue
  show/bgp_frr_v4.py
  show/bgp_frr_v6.py
Labels: Bug, Request for 201911 Branch, Request for 202106 branch, Request for 202111 branch

#1985 [Auto Techsupport] Added Event Driven TS to Command Reference
  doc/Command-Reference.md
Labels: Request for 202111 branch

#2014 [debug dump] Missing Dict Key handled in the MatchOptimizer
  dump/match_infra.py
  tests/dump_tests/match_engine_test.py
Labels: Request for 202111 branch

#2020 [generic-config-updater] Handle failed service restarts
  generic_config_updater/services_validator.py
  tests/generic_config_updater/service_validator_test.py
Labels: generic-config-updater

#2028 [generic_config_updater] Minor update - No logical code change
  generic_config_updater/services_validator.py
  tests/generic_config_updater/service_validator_test.py
Labels: generic-config-updater

#2043 [build] allowPartiallySucceededBuilds: true
  .azure-pipelines/build-docker-sonic-vs-template.yml
Labels: CI
