Repository sonic-net/sonic-utilities, pull requests merged in 2022-07, with the labels that each got.

#2206 [config/load_mgmt_config] Support load IPv6 mgmt IP
  config/main.py
  doc/Command-Reference.md
  tests/config_test.py
Labels: Request for 201911 Branch, Request for 202012 branch, Request for 202111 branch, Requested for 202205 branch

#2254 show linkmgrd status in `show mux status`
  show/muxcable.py
  tests/mock_tables/appl_db.json
  tests/muxcable_test.py
Labels: Requested for 202205 branch

#2236 Update load minigraph to load backend acl
  config/main.py
  tests/config_test.py
Labels: config, Unit Tests, Request for 202111 branch, Requested for 202205 branch

#2192 Add support for IP interface loopback action
  config/main.py
  doc/Command-Reference.md
  show/main.py
  tests/loopback_action_test.py
  tests/mock_tables/config_db.json
  utilities_common/cli.py
Labels: Requested for 202205 branch

#2235 [202012] Update load minigraph to load backend acl
  config/main.py
  tests/config_test.py
Labels: config, Unit Tests

#2261 show commands for SYSTEM READY (#1851)
  scripts/sysreadyshow
  setup.py
  show/system_health.py
  sonic_package_manager/manifest.py
  sonic_package_manager/service_creator/feature.py
  tests/mock_tables/state_db.json
  tests/sonic_package_manager/test_service_creator.py
  tests/system_health_test.py
Labels: Included in 202205 branch

#2268 [vnet_route_check] Align DB data parse logic with format used by swss…
  scripts/vnet_route_check.py
  tests/vnet_route_check_test.py
Labels: Request for 202012 branch, Request for 202111 branch, Request for 202205 branch

#2258 [MultiAsic] sudo reboot command doesn't gracefully stop Asic syncd# on multiasic platform
  scripts/reboot
Labels: Bug, Multi-ASIC :1234:, Chassis, Request for 202205 branch

#2253 Fix test for pfcwd_sw_enable in db_migrator_test
  tests/db_migrator_input/config_db/qos_map_table_expected.json
  tests/db_migrator_input/config_db/qos_map_table_input.json
Labels: Request for 202205 branch

#2205 Update db_migrator to support `PORT_QOS_MAP|global`
  scripts/db_migrator.py
  tests/db_migrator_input/config_db/qos_map_table_global_expected.json
  tests/db_migrator_input/config_db/qos_map_table_global_input.json
  tests/db_migrator_test.py
Labels: Request for 202205 branch

#2232 [counters] Keep counters cache in a single directory
  config/main.py
  config/plugins/pbh.py
  scripts/aclshow
  scripts/dropstat
  scripts/fast-reboot
  scripts/flow_counters_stat
  scripts/intfstat
  scripts/pfcstat
  scripts/pg-drop
  scripts/portstat
  scripts/queuestat
  scripts/tunnelstat
  show/plugins/pbh.py
  tests/aclshow_test.py
  tests/config_test.py
  tests/pbh_test.py
  tests/pfcstat_test.py
  tests/pgdropstat_test.py
  tests/portstat_test.py
  utilities_common/cli.py
Labels: Request for 202205 branch

#2239 [watermarkstat] Fix CLI script for unconfigured PG counters
  scripts/watermarkstat
Labels: Enhancement, Request for 202205 branch
