Repository sonic-net/sonic-utilities, pull requests merged in 2023-02, with the labels that each got.

#2427 [masic support] 'show run bgp' support for multi-asic
  show/main.py
  tests/conftest.py
  tests/mock_tables/asic0/show_not_running_bgp.txt
  tests/mock_tables/asic0/show_run_bgp.txt
  tests/mock_tables/asic1/show_run_bgp.txt
  tests/mock_tables/show_run_bgp.txt
  tests/show_run_bgp_test.py
Labels: Multi-ASIC :1234:, Request for 202205 branch, Request for 202211 branch

#2499 Add asic id for linecards so "show fabric counters queue/port" can work.
  scripts/fabricstat
  tests/fabricstat_test.py
  tests/mock_tables/counters_db.json
  tests/mock_tables/state_db.json
Labels: Request for 202205 branch

#2644 [Bugfix] "show vnet routes all"
  show/vnet.py
  tests/mock_tables/appl_db.json
  tests/mock_tables/state_db.json
  tests/show_vnet_test.py
  tests/show_vnet_vxlan_cli_test.py
Labels: Request for 202205 branch, Request for 202211 branch

#2651 [db_migrator] make LOG_LEVEL_DB migration more robust
  scripts/db_migrator.py
  tests/db_migrator_input/loglevel_db/logger_tables_input.json
Labels: Request for 202211 branch

#2633 [sai_failure_dump]Invoking dump during SAI failure
  scripts/generate_dump
Labels: Request for 202205 branch, Request for 202211 branch

#2630 Add transceiver info CLI support to show output from TRANSCEIVER_INFO for ZR
  doc/Command-Reference.md
  scripts/sfpshow
  show/interfaces/__init__.py
  tests/mock_tables/asic0/state_db.json
  tests/mock_tables/asic1/state_db.json
  tests/mock_tables/state_db.json
  tests/multi_asic_intfutil_test.py
  tests/sfp_test.py
  utilities_common/sfp_helper.py
Labels: Request for 202205 branch, Request for 202211 branch

#2670 [portstat CLI] don't print reminder if use json format
  scripts/portstat
Labels: Request for 202205 branch, Request for 202211 branch

#2532 Add support of secure warm-boot
  scripts/fast-reboot
Labels: Request for 202211 branch
