Repository sonic-net/sonic-utilities, pull requests merged in 2023-09, with the labels that each got.

#2961 Remove SFP index usage in generating list of SFP hw error
  sfputil/main.py
  tests/sfputil_test.py
Labels: Bug

#2959 Remove the CONFIG_DB_INIT flag dependency on db_migrator
  scripts/db_migrator.py
Labels: Request for 202205 branch, Request for 202211 branch, Request for 202305 branch

#2978 Added support to display only nonzero queue counter.
  scripts/queuestat
  show/main.py
  tests/mock_tables/counters_db.json
  tests/queue_counter_test.py
Labels: Chassis for 202205 branch, included in chassis for 202205 branch, Request for 202305 branch

#2979 Techsupport tmpfs logging
  scripts/generate_dump
Labels: Request for 201911 Branch, Request for 202012 branch, Request for 202106 branch, Request for 202111 branch, Request for 202205 branch, Request for 202211 branch, Request for 202305 branch

#2985 Handle NotImplementedError exception while changing optoe write max
  sfputil/main.py
  tests/sfputil_test.py
Labels: Request for 202205 branch, Request for 202305 branch

#2987 [vlan][dhcp_relay] Fix error while delete vlan
  config/vlan.py
  tests/mock_tables/config_db.json
  tests/vlan_test.py
  utilities_common/dhcp_relay_util.py
Labels: Request for 202305 branch

#2994 [acl-loader] Identity ICMP v4/v6 based on IP_PROTOCOL for custom ACL table types
  acl_loader/main.py
  tests/acl_input/acl1.json
  tests/acl_loader_test.py
Labels: Request for 202205 branch, Request for 202305 branch

#2991 Remove syslog service validator in GCU
  generic_config_updater/gcu_services_validator.conf.json
  generic_config_updater/services_validator.py
  tests/generic_config_updater/service_validator_test.py
Labels: Request for 202305 branch
