Repository sonic-net/sonic-utilities, pull requests merged in 2023-01, with the labels that each got.

#2585 [storyteller] add link prober state change to story teller
  scripts/storyteller
Labels: Request for 202205 branch, Request for 202211 branch

#2349 [sfputil] Firmware download/upgrade CLI support for QSFP-DD (#1947)
  sfputil/main.py
  tests/sfputil_test.py
Labels: Enhancement

#2524 Preserve copp tables through DB migration
  scripts/db_migrator.py
Labels: Request for 202211 branch

#2577 Extend fast-reboot STATE_DB entry timer
  scripts/fast-reboot
Labels: Request for 202205 branch, Request for 202211 branch

#2537 [show] Add bgpraw to show run all
  show/main.py
  tests/show_test.py
Labels: Request for 201811 Branch, Request for 201911 Branch, Request for 202012 branch, Request for 202106 branch, Request for 202111 branch, Request for 202205 branch, Request for 202211 branch

#2528 Add "show fabric reachability" command.
  scripts/fabricstat
  show/fabric.py
  tests/fabricstat_test.py
Labels: Chassis

#2622 [muxcable][config] Add support to enable/disable ceasing to be an advertisement interface when `radv` service is stopped
  config/muxcable.py
  tests/muxcable_test.py
Labels: Request for 202205 branch, Request for 202211 branch

#2439 suppport multi asic for show queue counter
  scripts/queuestat
  show/main.py
  tests/mock_tables/asic0/counters_db.json
  tests/multi_asic_queue_counter_test.py
Labels: Chassis, Request for 202205 branch

#2635 [system-health] Fix issue: show system-health CLI crashes
  show/system_health.py
Labels: Request for 202211 branch

#2637 Skip saidump for Spine Router as this can take more than 5 sec
  scripts/generate_dump
Labels: Request for 202205 branch
