Repository sonic-net/sonic-utilities, pull requests merged in 2023-12, with the labels that each got.

#3067 [action] [PR:3024] [ci] Use correct bullseye docker image according to source branch.
  azure-pipelines.yml
Labels: automerge

#3008 Support reading/writing module EEPROM data by page and offset
  doc/Command-Reference.md
  sfputil/main.py
  tests/sfputil_test.py
Labels: Request for 202311 Branch, Cherry Pick Conflict_202311

#3074 [action] [PR:3052] Reduce generate_dump mem usage for cores (#3052)
  scripts/generate_dump
Labels: automerge

#3068 [db_migrator]Remove route migration
  scripts/db_migrator.py
  tests/db_migrator_input/appl_db/routes_migrate_expected.json
  tests/db_migrator_input/appl_db/routes_migrate_input.json
  tests/db_migrator_test.py
Labels: Request for 202305 Branch, Request for 202311 Branch

#3071 route_check.py should not print too many outputs to stdout
  scripts/route_check.py
  tests/route_check_test.py
  tests/route_check_test_data.py
Labels: Request for 202305 Branch, Request for 202311 Branch

#3085 [action] [PR:3068] [db_migrator]Remove route migration (#3068)
  scripts/db_migrator.py
  tests/db_migrator_input/appl_db/routes_migrate_expected.json
  tests/db_migrator_input/appl_db/routes_migrate_input.json
  tests/db_migrator_test.py
Labels: automerge

#3077 Enhanced route_check.py for multi_asic platforms
  scripts/route_check.py
  scripts/route_check_test.sh
  tests/route_check_test.py
  tests/route_check_test_data.py
Labels: p0, Cherry Pick Conflict_202205, Request for 202205 Branch, Request for 202305 Branch

#3009 Collect module EEPROM data in dump
  doc/Command-Reference.md
  scripts/generate_dump
  sfputil/main.py
  tests/sfputil_test.py
Labels: Request for 202311 Branch, Cherry Pick Conflict_202311

#3092 [action] [PR:3071] route_check.py should not print too many outputs to stdout (#3071)
  scripts/route_check.py
  tests/route_check_test.py
  tests/route_check_test_data.py
Labels: automerge

#3096 [action] [PR:2936] [GCU] Add PORT table StateDB Validator (#2936)
  generic_config_updater/field_operation_validators.py
  generic_config_updater/gcu_field_operation_validators.conf.json
  scripts/portconfig
  tests/generic_config_updater/field_operation_validator_test.py
  utilities_common/constants.py
Labels: automerge

#3075 route_check: Skip route checks if bgp feature is not enabled
  scripts/route_check.py
  tests/route_check_test.py
  tests/route_check_test_data.py
Labels: Request for 202305 Branch, Cherry Pick Conflict_202305

#3072 Support disable/enable syslog rate limit feature
  config/syslog.py
  doc/Command-Reference.md
  tests/syslog_test.py
Labels: Request for 202305 Branch, Request for 202311 Branch

#3101 [action] [PR:3072] Support disable/enable syslog rate limit feature (#3072)
  config/syslog.py
  doc/Command-Reference.md
  tests/syslog_test.py
Labels: automerge
