Repository sonic-net/sonic-utilities, pull requests merged in 2023-03, with the labels that each got.

#2714 [warm/fast-reboot] Backup logs from tmpfs to disk during fast/warm shutdown
  scripts/fast-reboot
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202211 branch

#2728 execute a platform-provided pre-reboot script before shutting down swss
  scripts/fast-reboot
Labels: Included in 202205 branch, Request for 202211 branch

#2621 Remove timer from FAST_REBOOT STATE_DB entry and use finalizer
  scripts/db_migrator.py
  scripts/fast-reboot
  sonic-utilities-data/templates/service_mgmt.sh.j2
  tests/db_migrator_input/state_db/fast_reboot_expected.json
  tests/db_migrator_input/state_db/fast_reboot_input.json
  tests/db_migrator_test.py
Labels: fast-reboot, Request for 202211 branch

#2720 Enhance the logic to wait for all buffer tables to be removed in _clear_qos
  config/main.py
  tests/config_test.py
Labels: Request for 202205 branch, Request for 202211 branch

#2731 Update the ref guide to reflect the vlan brief output
  doc/Command-Reference.md
Labels: Request for 202205 branch, Request for 202211 branch

#2735 Revert "Update load minigraph to load backend acl"
  config/main.py
  tests/config_test.py
Labels: Request for 202205 branch

#2703 Fix the `show interface counters` throwing exception on device with no external interfaces
  scripts/portstat
Labels: Chassis, Request for 202111 branch, Request for 202205 branch
