Repository sonic-net/sonic-utilities, pull requests merged in 2023-05, with the labels that each got.

#2778 [config]config reload should generate sysinfo if missing
  config/main.py
  tests/config_test.py
Labels: Request for 202205 branch, Request for 202211 branch

#2817 Change default CDB run mode to non-hitless
  sfputil/main.py
  tests/sfputil_test.py
Labels: Request for 202205 branch, Request for 202211 branch

#2808 Added platform plugin support in load_minigraph
  config/main.py
  tests/config_test.py
  tests/load_minigraph_input/platform/plugins/platform_mg_post_check
  tests/load_minigraph_input/platform_false/plugins/platform_mg_post_check
Labels: Request for 202205 branch, Request for 202211 branch, Chassis for 202205 branch

#2814 [config]: Dynamically start and stop ndppd
  config/vlan.py
  tests/vlan_test.py
Labels: Request for 202205 branch, Request for 202211 branch

#2806 LAG keepalive script to reduce lacp session wait during warm-reboot
  scripts/fast-reboot
  scripts/lag_keepalive.py
  setup.py
Labels: Request for 202205 branch, Request for 202211 branch

#2830 [build] Fix base OS compilation issue caused by incompatibility of urllib with requests.
  setup.py
Labels: Request for 202205 branch, Request for 202211 branch

#2825 [config]Support multi-asic Golden Config override with fix
  config/config_mgmt.py
  config/main.py
  tests/config_override_input/multi_asic_dm_rm.json
  tests/config_override_input/multi_asic_macsec_ov.json
  tests/config_override_test.py
Labels: Chassis, Request for 202211 branch, Chassis for 202205 branch

#2834 Fix the invalid variable issue when set-fips in uboot
  sonic_installer/bootloader/uboot.py
Labels: Request for 202205 branch, Request for 202211 branch

#2664 replace shell=True, replace xml, and replace exit()
  pfcwd/main.py
  scripts/boot_part
  scripts/check_db_integrity.py
  scripts/configlet
  scripts/disk_check.py
  scripts/dropconfig
  scripts/dump_nat_entries.py
  scripts/ipintutil
  scripts/lldpshow
  scripts/storyteller
  scripts/vnet_route_check.py
  tests/disk_check_test.py
  tests/dropconfig_test.py
  tests/filter_fdb_entries_test.py
  tests/intfutil_test.py
  tests/lldp_test.py
  tests/pfcwd_test.py
Labels: static-code-analysis

#2837 Update TRANSCEIVER_INFO table after CDB FW upgrade
  sfputil/main.py
  tests/sfputil_test.py
Labels: Request for 202205 branch, Request for 202211 branch

#2786 Update pcieutil error message on loading common pcie module
  pcieutil/main.py
  tests/pcieutil_test.py
Labels: Enhancement, Request for 202205 branch, Request for 202211 branch

#2852 [vlan][dhcp_relay] Clear dhcpv6 relay counter while deleting vlan
  config/vlan.py
  tests/vlan_test.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202211 branch

#2842 [sonic-package-manager] fix CLI plugin compatibility issue
  sonic_package_manager/manager.py
  tests/sonic_package_manager/test_manager.py
Labels: Bug

#2821 [db-migrator] Fix hwsku match for 6100 and add errors when hwsku is None
  scripts/db_migrator.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202211 branch

#2800 [CRM][DASH] Extend CRM utility to support DASH resources.
  crm/dash_config.py
  crm/dash_show.py
  crm/main.py
  tests/crm_dash/config_db.json
  tests/crm_dash/counters_db.json
  tests/crm_dash_test.py
Labels: dash

#2718 [utilities_common] replace shell=True
  clear/main.py
  config/main.py
  config/plugins/mlnx.py
  config/syslog.py
  config/vlan.py
  scripts/sonic-bootchart
  show/acl.py
  show/chassis_modules.py
  show/dropcounters.py
  show/fabric.py
  show/flow_counters.py
  show/gearbox.py
  show/interfaces/__init__.py
  show/kdump.py
  show/main.py
  show/nat.py
  show/platform.py
  show/processes.py
  show/system_health.py
  show/vxlan.py
  tests/chassis_modules_test.py
  tests/clear_test.py
  tests/config_int_ip_test.py
  tests/config_test.py
  tests/conftest.py
  tests/ecn_test.py
  tests/fabricstat_test.py
  tests/fdbshow_test.py
  tests/flow_counter_stats_test.py
  tests/multi_asic_intfutil_test.py
  tests/multi_asic_queue_counter_test.py
  tests/pfcstat_test.py
  tests/portstat_test.py
  tests/sfp_test.py
  tests/show_ip_int_test.py
  tests/show_platform_test.py
  tests/show_test.py
  tests/sonic_bootchart_test.py
  tests/utils.py
  tests/vlan_test.py
  utilities_common/bgp_util.py
  utilities_common/cli.py
Labels: static-code-analysis

#2666 [show] replace shell=True, replace xml by lxml, replace exit by sys.exit
  show/bgp_quagga_v4.py
  show/bgp_quagga_v6.py
  show/main.py
  show/platform.py
  tests/fdbshow_test.py
  tests/intfstat_test.py
  tests/pfcstat_test.py
  tests/queue_counter_test.py
  tests/show_test.py
  tests/techsupport_test.py
  tests/tunnelstat_test.py
Labels: static-code-analysis
