Repository sonic-net/sonic-utilities, pull requests merged in 2023-06, with the labels that each got.

#2847 Fix issue: out of range sflow polling interval is accepted and stored in config_db
  config/main.py
  tests/sflow_test.py
Labels: Bug, Request for 202211 branch

#2865 Revert "[config]config reload should generate sysinfo if missing (#2778)
  config/main.py
  tests/config_test.py
Labels: Request for 202205 branch

#2850 [chassis]: remote cli commands infra for sonic chassis
  rcli/__init__.py
  rcli/linecard.py
  rcli/rexec.py
  rcli/rshell.py
  rcli/utils.py
  setup.py
  sonic-utilities-data/bash_completion.d/rexec
  sonic-utilities-data/bash_completion.d/rshell
  tests/chassis_modules_test.py
  tests/mock_tables/asic0/state_db.json
  tests/mock_tables/chassis_state_db.json
  tests/mock_tables/database_config.json
  tests/mock_tables/state_db.json
  tests/remote_cli_test.py
Labels: Chassis for 202205 branch

#2643 [sonic_installer] remove subprocess with shell=True
  sonic_installer/bootloader/aboot.py
  sonic_installer/bootloader/grub.py
  sonic_installer/bootloader/uboot.py
  sonic_installer/common.py
  sonic_installer/main.py
  tests/installer_bootloader_aboot_test.py
  tests/installer_bootloader_grub_test.py
  tests/installer_bootloader_uboot_test.py
  tests/installer_docker_test.py
  tests/swap_allocator_test.py
  tests/test_sonic_installer.py
Labels: static-code-analysis

#2858 Add display support for serial field in show chassis modules status CLI
  show/chassis_modules.py
  tests/chassis_modules_test.py
  tests/mock_tables/state_db.json
Labels: Request for 202205 branch, Request for 202211 branch

#2866 [dhcp-relay] Fix dhcp6relay counter issue
  config/vlan.py
Labels: Request for 202205 branch

#2874 fix precedence in portstat CLI
  scripts/portstat
  tests/portstat_test.py
Labels: Request for 202205 branch

#2789 Clear fabric counters queue/port
  clear/main.py
  scripts/fabricstat
  tests/fabricstat_test.py
Labels: Chassis for 202205 branch

#2525 [chassis][multi asic] change acl_loader to use tcp socket for db communication
  acl_loader/main.py
  tests/acl_loader_test.py
Labels: Chassis, Request for 202205 branch, Request for 202211 branch, Request for 202305 branch

#2698 Secure upgrade v2
  scripts/verify_image_sign.sh
  scripts/verify_image_sign_common.sh
  setup.py
  sonic_installer/bootloader/bootloader.py
  sonic_installer/bootloader/grub.py
  sonic_installer/main.py
  tests/installer_bootloader_aboot_test.py
  tests/installer_bootloader_grub_test.py
  tests/installer_bootloader_onie_test.py
  tests/installer_bootloader_uboot_test.py
  tests/scripts/create_mock_image.sh
  tests/scripts/create_sign_and_verify_test_files.sh
  tests/scripts/verify_image_sign_test.sh
  tests/sign_and_verify_test.py
  tests/test_sonic_installer.py
  tests/verify_image_sign_test.sh
Labels: Request for 202211 branch

#2887 [db_migrator] Remove hardcoded config and migrate config from minigraph
  scripts/db_migrator.py
  scripts/db_migrator_constants.py
  setup.py
  tests/db_migrator_input/config_db/cross_branch_upgrade_to_version_2_0_2_expected.json
  tests/db_migrator_input/minigraph.xml
  tests/db_migrator_test.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202211 branch, Request for 202305 branch

#2750 [doc]:Update Command-Reference.md, change "show bgp peer" command to "show bfd peer"
  doc/Command-Reference.md
Labels: Documentation
