Repository sonic-net/sonic-utilities, pull requests merged in 2023-11, with the labels that each got.

#3031 [config] config reload should generate sysinfo if missing
  config/main.py
  tests/config_test.py
Labels: Request for 202205 branch, Request for 202305 branch

#3034 [dualtor_neighbor_check] Adjust zero-mac check condition
  scripts/dualtor_neighbor_check.py
  tests/dualtor_neighbor_check_test.py
Labels: Request for 202205 branch, Request for 202211 branch, Request for 202305 branch

#3037 [sonic-package-manager] add generated service to /etc/sonic/generated_services.conf
  sonic_package_manager/service_creator/creator.py
  tests/sonic_package_manager/conftest.py
  tests/sonic_package_manager/test_service_creator.py
Labels: Request for 202305 branch

#3032 [sonic-package-manager] do not modify config_db.json
  sonic_package_manager/service_creator/sonic_db.py
Labels: Request for 202305 branch

#3012 Update GCU rsyslog validator
  generic_config_updater/services_validator.py
  tests/generic_config_updater/service_validator_test.py
Labels: Request for 202305 branch

#3028 [202305][sonic_installer]: Improve exception handling: introduce notes
  sonic_installer/common.py
  sonic_installer/exception.py
  tests/test_sonic_installer.py
Labels: Enhancement

#3010 GCU support for Cisco-8000 features
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: Request for 202305 branch

#3040 [sonic-package-manager] insert newline in /etc/sonic/generated_services.conf
  sonic_package_manager/service_creator/creator.py
  tests/sonic_package_manager/test_service_creator.py
Labels: Bug, Request for 202305 branch

#3030 [fast-reboot-filter-routes.py] Remove click and improve error reporting
  scripts/fast-reboot-filter-routes.py
  tests/fast_reboot_filter_routes_test.py
Labels: Request for 202305 branch

#3038 Support new platform in generic configuration update
  generic_config_updater/gcu_field_operation_validators.conf.json
  tests/generic_config_updater/field_operation_validator_test.py
Labels: Request for 202305 branch

#3039 Add container rsyslog.conf to the sys dump
  scripts/generate_dump
Labels: Request for 202305 branch

#3029 [sonic_installer]: Improve exception handling: introduce notes.
  sonic_installer/common.py
  sonic_installer/exception.py
  tests/test_sonic_installer.py
Labels: Enhancement, Request for 202305 branch, Included in 202305 branch, Cherry Pick Conflict_202305
