Repository sonic-net/sonic-utilities, pull requests merged in 2024-05, with the labels that each got.

#3307 [action] [PR:3274] Display target firmware version through CLI (#3274)
  scripts/sfpshow
  tests/mock_tables/asic1/state_db.json
  tests/mock_tables/state_db.json
  tests/sfp_test.py
  utilities_common/sfp_helper.py
Labels: automerge

#3310 [action] [PR:3250] T2-VOQ-VS: Modified exception handling due to new sonic_platform package support for VS (#3250)
  utilities_common/platform_sfputil_helper.py
Labels: automerge

#3320 [action] [PR:3155] Add vlan validation in config interface ip add command (#3155)
  config/main.py
  tests/ip_config_test.py
Labels: automerge

#3319 [action] [PR:3240] [fast/warm-reboot] Retain TRANSCEIVER_INFO tables on fast/warm-reboot (#3240)
  scripts/fast-reboot
Labels: automerge

#3318 [action] [PR:3272] [Mellanox] Support new platform SN5400 in generic configuration update (#3272)
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: automerge

#3292 [chassis][midplane] Add notification to Supervisor when LC is graceful reboot
  scripts/reboot
Labels: Chassis for 202205 Branch, Request for 202305 Branch, Request for 202311 Branch

#3324 [action] [PR:3292] [chassis][midplane] Add notification to Supervisor when LC is graceful reboot (#3292)
  scripts/reboot
Labels: automerge

#3323 [action] [PR:3236] Update sonic-utilities to support new SKU Mellanox-SN5600-O128 (#3236)
  generic_config_updater/gcu_field_operation_validators.conf.json
  scripts/mellanox_buffer_migrator.py
  tests/db_migrator_input/config_db/empty-config-with-device-info-nvidia-expected.json
  tests/db_migrator_input/config_db/empty-config-with-device-info-nvidia-input.json
  tests/db_migrator_test.py
Labels: automerge

#3297 Add show fabric rate command
  scripts/fabricstat
  show/fabric.py
  tests/fabricstat_test.py
  tests/mock_tables/asic0/state_db.json
Labels: chassis-voq

#3329 [action] [PR:3284] Migrate AAA table in db_migrator (#3284)
  scripts/db_migrator.py
  tests/db_migrator_input/config_db/per_command_aaa_disable.json
  tests/db_migrator_input/config_db/per_command_aaa_disable_expected.json
  tests/db_migrator_input/config_db/per_command_aaa_disable_golden.json
  tests/db_migrator_input/config_db/per_command_aaa_enable.json
  tests/db_migrator_input/config_db/per_command_aaa_enable_expected.json
  tests/db_migrator_input/config_db/per_command_aaa_enable_golden.json
  tests/db_migrator_input/config_db/per_command_aaa_no_authentication.json
  tests/db_migrator_input/config_db/per_command_aaa_no_authentication_expected.json
  tests/db_migrator_input/config_db/per_command_aaa_no_authentication_golden.json
  tests/db_migrator_input/config_db/per_command_aaa_no_change.json
  tests/db_migrator_input/config_db/per_command_aaa_no_change_expected.json
  tests/db_migrator_input/config_db/per_command_aaa_no_change_golden.json
  tests/db_migrator_input/config_db/per_command_aaa_no_passkey.json
  tests/db_migrator_input/config_db/per_command_aaa_no_passkey_expected.json
  tests/db_migrator_input/config_db/per_command_aaa_no_passkey_golden.json
  tests/db_migrator_input/config_db/per_command_aaa_no_tacplus.json
  tests/db_migrator_input/config_db/per_command_aaa_no_tacplus_expected.json
  tests/db_migrator_input/config_db/per_command_aaa_no_tacplus_golden.json
  tests/db_migrator_test.py
Labels: automerge

#3330 [action] [PR:3296] Migrate AAA table per-command authorization in db_migrator (#3296)
  scripts/db_migrator.py
  tests/db_migrator_input/config_db/per_command_aaa_enable_expected.json
  tests/db_migrator_input/config_db/per_command_aaa_no_authentication_expected.json
  tests/db_migrator_input/config_db/per_command_aaa_no_passkey.json
  tests/db_migrator_input/config_db/per_command_aaa_no_tacplus_expected.json
Labels: automerge

#3305 [sonic-package-manager] remove leftovers from featured on uninstall
  sonic_package_manager/service_creator/creator.py
  tests/sonic_package_manager/conftest.py
  tests/sonic_package_manager/test_service_creator.py
Labels: Bug, Request for 202305 Branch, Request for 202311 Branch, Approved for 202311 Branch

#3336 [action] [PR:3305] [sonic-package-manager] remove leftovers from featured on uninstall (#3305)
  sonic_package_manager/service_creator/creator.py
  tests/sonic_package_manager/conftest.py
  tests/sonic_package_manager/test_service_creator.py
Labels: automerge

#3328 [build] Fix base OS compilation issue caused by incompatibility between urllib3 and requests packages
  azure-pipelines.yml
  setup.py
Labels: Request for 202311 Branch, Cherry Pick Conflict_202311

#3283 Update for the procedures for insertion/hot swap of Switch Fabric Module(SFM) by using "config chassis modules shutdown/startup" commands
  config/chassis_modules.py
  tests/chassis_modules_test.py
Labels: p0, Chassis for 202205 Branch
