Repository sonic-net/sonic-utilities, pull requests merged in 2024-10, with the labels that each got.

#3564 Add Unit Test for portstat
  tests/portstat_db/on_sup_na/chassis_state_db.json
  tests/portstat_test.py
Labels: Chassis for 202205 Branch, Request for 202405 Branch

#3563 Fix KeyError in pfc config command
  pfc/main.py
Labels: Request for 202405 Branch

#3569 [action] [PR:3563] Fix key error when checking for UTILITIES_UNIT_TESTING env var (#3563)
  pfc/main.py
Labels: automerge

#3576 Add YANG validation for config reload if file is given
  config/main.py
  tests/config_test.py
Labels: Request for 202405 Branch

#3581 [action] [PR:3576] Add YANG validation for config reload if file is given (#3576)
  config/main.py
  tests/config_test.py
Labels: automerge

#3582 [action] [PR:3523] [spm]: Clean up timers auto generation logic. (#3523)
  sonic-utilities-data/templates/timer.unit.j2
  sonic_package_manager/service_creator/creator.py
  sonic_package_manager/service_creator/feature.py
  tests/sonic_package_manager/conftest.py
  tests/sonic_package_manager/test_service_creator.py
Labels: automerge

#3491 [Mellanox]Remove deprecated sdk sniffer cli and collect sdk dump in show techsupport
  config/plugins/mlnx.py
  doc/Command-Reference.md
  scripts/generate_dump
  show/plugins/mlnx.py
  tests/config_mlnx_test.py
Labels: Platform: Mellanox, Request for 202405 Branch

#3583 Record and warn tables which not covered by YANG
  config/main.py
Labels: Request for 202311 Branch, Request for 202405 Branch

#3399 Adds logic to get default disk and check disk type
  ssdutil/main.py
  tests/mocked_libs/__init__.py
  tests/mocked_libs/blkinfo.py
  tests/mocked_libs/psutil.py
  tests/ssdutil_test.py
Labels: Request for 202405 Branch

#3594 [action] [PR:3572] Revert "Skip default lanes dup check (#3489)" (#3572)
  generic_config_updater/gu_common.py
  tests/generic_config_updater/gu_common_test.py
Labels: automerge
