Repository sonic-net/sonic-utilities, pull requests merged in 2024-04, with the labels that each got.

#3244 [dualtor_neighbor_check] Fix the script not exists issue
  scripts/dualtor_neighbor_check.py
  tests/dualtor_neighbor_check_test.py
Labels: Request for 202305 Branch, Request for 202311 Branch

#3252 [action] [PR:3244] [dualtor_neighbor_check] Fix the script not exists issue (#3244)
  scripts/dualtor_neighbor_check.py
  tests/dualtor_neighbor_check_test.py
Labels: automerge

#3251 [action] [PR:3244] [dualtor_neighbor_check] Fix the script not exists issue (#3244)
  scripts/dualtor_neighbor_check.py
  tests/dualtor_neighbor_check_test.py
Labels: automerge

#3258 [action] [PR:3238] Modify "show interface transceiver status" CLI to show SW cmis state (#3238)
  tests/mock_tables/state_db.json
  tests/sfp_test.py
  utilities_common/sfp_helper.py
Labels: automerge

#3261 [action] [PR:3198] [show] multi-asic show running test residue (#3198)
  tests/show_test.py
Labels: automerge

#3263 [action] [PR:3198] [show] multi-asic show running test residue (#3198)
  tests/show_test.py
Labels: automerge

#3262 [action] [PR:2809] [generate_dump] call hw-management-generate-dump.sh in collect_cisco_8000 (#2809)
  scripts/generate_dump
Labels: automerge

#3191 [202305][graceful reboot] Add the pre_reboot_hook script execution, add the watchdog arm before the reboot
  scripts/reboot
Labels: Cherry Pick Conflict_202305

#3235 Add multi ASIC support for syslog rate limit feature
  config/syslog.py
  doc/Command-Reference.md
  show/syslog.py
  syslog_util/common.py
  tests/mock_tables/asic0/config_db.json
  tests/mock_tables/asic1/config_db.json
  tests/mock_tables/config_db.json
  tests/syslog_multi_asic_test.py
  tests/syslog_test.py
Labels: Request for 202311 Branch, Cherry Pick Conflict_202311

#3267 Fix double hex to decimal conversion
  sfputil/main.py
  tests/sfputil_test.py
Labels: Bug

#3249 Add Multi ASIC support for apply-patch
  config/main.py
  generic_config_updater/change_applier.py
  generic_config_updater/generic_updater.py
  generic_config_updater/gu_common.py
  tests/config_test.py
  tests/generic_config_updater/change_applier_test.py
  tests/generic_config_updater/multiasic_change_applier_test.py
  tests/generic_config_updater/multiasic_generic_updater_test.py
Labels: p0, Chassis for 202205 Branch

#3274 Display target firmware version through CLI
  scripts/sfpshow
  tests/mock_tables/asic1/state_db.json
  tests/mock_tables/state_db.json
  tests/sfp_test.py
  utilities_common/sfp_helper.py
Labels: Request for 202305 Branch, Request for 202311 Branch

#3291 [action] [PR:3158] [chassis] fix show bgp summary when no neighbors are present on one ASIC (#3158)
  tests/bgp_commands_test.py
  tests/conftest.py
  tests/mock_tables/asic0/show_ip_bgp_summary.json
  utilities_common/bgp_util.py
Labels: automerge

#3236 Update sonic-utilities to support new SKU Mellanox-SN5600-O128
  generic_config_updater/gcu_field_operation_validators.conf.json
  scripts/mellanox_buffer_migrator.py
  tests/db_migrator_input/config_db/empty-config-with-device-info-nvidia-expected.json
  tests/db_migrator_input/config_db/empty-config-with-device-info-nvidia-input.json
  tests/db_migrator_test.py
Labels: Request for 202311 Branch, Cherry Pick Conflict_202311

#3298 [action] [PR:3274] Display target firmware version through CLI (#3274)
  scripts/sfpshow
  tests/mock_tables/asic1/state_db.json
  tests/mock_tables/state_db.json
  tests/sfp_test.py
  utilities_common/sfp_helper.py
Labels: automerge
