Repository sonic-net/sonic-utilities, pull requests merged in 2024-02, with the labels that each got.

#3146 [action] [PR:3131] Add all SKUs to the generic config update list (#3131)
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: automerge

#3145 [action] [PR:3069] Modify teamd retry count script to base BGP status on default BGP status (#3069)
  scripts/teamd_increase_retry_count.py
Labels: automerge

#3144 [action] [PR:3068] [db_migrator]Remove route migration (#3068)
  scripts/db_migrator.py
  tests/db_migrator_input/appl_db/routes_migrate_expected.json
  tests/db_migrator_input/appl_db/routes_migrate_input.json
  tests/db_migrator_test.py
Labels: automerge

#3142 [action] [PR:3118] [Techsupport]Adding more FRR and BGP dumps (#3118)
  scripts/generate_dump
Labels: automerge

#3141 [action] [PR:3115] Disable Key Validation feature during sonic-installation for Cisco Platforms (#3115)
  sonic_installer/bootloader/grub.py
Labels: automerge

#3140 [action] [PR:3052] Reduce generate_dump mem usage for cores (#3052)
  scripts/generate_dump
Labels: automerge

#3114 [Mellanox buffer migrator] Do not touch the buffer model on generic SKUs if the buffer configuration is empty
  scripts/mellanox_buffer_migrator.py
  tests/db_migrator_input/config_db/empty-config-with-device-info-generic-expected.json
  tests/db_migrator_input/config_db/empty-config-with-device-info-generic-input.json
  tests/db_migrator_input/config_db/empty-config-with-device-info-traditional-expected.json
  tests/db_migrator_input/config_db/empty-config-with-device-info-traditional-input.json
  tests/db_migrator_test.py
Labels: Request for 202311 Branch

#3157 [action] [PR:3149] Fix `sudo config load_mgmt_config` fails with error "File /var/run/dhclient.eth0.pid does not exist" (#3149)
  config/main.py
  tests/config_test.py
Labels: automerge

#3156 [action] [PR:3149] Fix `sudo config load_mgmt_config` fails with error "File /var/run/dhclient.eth0.pid does not exist" (#3149)
  config/main.py
  tests/config_test.py
Labels: automerge

#3153 Fix the sfputil treats page number as decimal instead of hexadecimal
  doc/Command-Reference.md
  sfputil/main.py
Labels: Bug

#3162 [action] [PR:3158] [chassis] fix show bgp summary when no neighbors are present on one ASIC (#3158)
  tests/bgp_commands_test.py
  tests/conftest.py
  tests/mock_tables/asic0/show_ip_bgp_summary.json
  utilities_common/bgp_util.py
Labels: automerge

#3165 [action] [PR:3131] Add all SKUs to the generic config update list (#3131)
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: automerge

#3166 [action] [PR:3114] [Mellanox buffer migrator] Do not touch the buffer model on generic SKUs if the buffer configuration is empty (#3114)
  scripts/mellanox_buffer_migrator.py
  tests/db_migrator_input/config_db/empty-config-with-device-info-generic-expected.json
  tests/db_migrator_input/config_db/empty-config-with-device-info-generic-input.json
  tests/db_migrator_input/config_db/empty-config-with-device-info-traditional-expected.json
  tests/db_migrator_input/config_db/empty-config-with-device-info-traditional-input.json
  tests/db_migrator_test.py
Labels: automerge

#3148 [show] Update show run all to cover all asic config in multiasic
  show/main.py
  tests/show_test.py
Labels: Request for 202305 Branch, Request for 202311 Branch

#3169 [config] Check golden config exist early if flag is set
  config/main.py
Labels: Request for 202311 Branch

#3168 Fix sfputil CLI failure for multi-asic platforms
  sfputil/main.py
  tests/sfputil_test.py
Labels: Request for 202305 Branch, Cherry Pick Conflict_202305, Request for 202311 Branch

#3174 Modify transceiver PM CLI to handle N/A value for DOM threshold
  scripts/sfpshow
Labels: Request for 202205 Branch, Request for 202305 Branch, Request for 202311 Branch

#3177 CLI enhancements to revtrieve data from TRANSCEIVER_FIRMWARE_INFO table
  scripts/sfpshow
  sfputil/main.py
  tests/mock_tables/asic1/state_db.json
  tests/mock_tables/state_db.json
  tests/sfputil_test.py
Labels: Request for 202305 Branch, Request for 202311 Branch

#3183 [action] [PR:3174] Modify transceiver PM CLI to handle N/A value for DOM threshold (#3174)
  scripts/sfpshow
Labels: automerge

#3185 [action] [PR:3177] CLI enhancements to revtrieve data from TRANSCEIVER_FIRMWARE_INFO table (#3177)
  scripts/sfpshow
  sfputil/main.py
  tests/mock_tables/asic1/state_db.json
  tests/mock_tables/state_db.json
  tests/sfputil_test.py
Labels: automerge
