Repository sonic-net/sonic-utilities, pull requests merged in 2024-08, with the labels that each got.

#3469 [action] [PR:3357] [DPB]Fixing return code of breakout command on failure (#3357)
  config/main.py
  tests/config_dpb_test.py
Labels: automerge

#3468 [action] [PR:3299] Add Checkpoint and Rollback for Multi ASIC. (#3299)
  config/main.py
  generic_config_updater/change_applier.py
  generic_config_updater/generic_updater.py
  generic_config_updater/gu_common.py
  tests/config_test.py
  tests/generic_config_updater/change_applier_test.py
  tests/generic_config_updater/generic_updater_test.py
  tests/generic_config_updater/gu_common_test.py
  tests/generic_config_updater/multiasic_change_applier_test.py
  tests/generic_config_updater/multiasic_generic_updater_test.py
Labels: automerge

#3467 [action] [PR:3342] [fast-reboot] Backup database after syncd/swss stopped (#3342)
  scripts/fast-reboot
Labels: automerge

#3466 [action] [PR:3356] [pbh]: Fix show PBH counters when cache is partial (#3356)
  show/plugins/pbh.py
  tests/pbh_input/assert_show_output.py
  tests/pbh_input/counters_db_partial.json
  tests/pbh_test.py
Labels: automerge

#3465 [action] [PR:3358] [chassis][mutli-asic][lldp] "show lldp table/neighbors" displays error message in output on multi-asis linecard. (#3358)
  scripts/lldpshow
  tests/lldp_test.py
  tests/mock_tables/config_db.json
  utilities_common/general.py
Labels: automerge

#3464 [action] [PR:3365] Improve load_mingraph to wait eth0 restart before exit (#3365)
  config/main.py
  tests/config_test.py
Labels: automerge

#3463 [action] [PR:3383] Add the definition of `log` in `script decode-syseeprom` (#3383)
  scripts/decode-syseeprom
Labels: automerge

#3462 [action] [PR:3383] Add the definition of `log` in `script decode-syseeprom` (#3383)
  scripts/decode-syseeprom
Labels: automerge

#3461 [action] [PR:3383] Add the definition of `log` in `script decode-syseeprom` (#3383)
  scripts/decode-syseeprom
Labels: automerge

#3460 [action] [PR:3417] Enable show ip bgp on sup and -n all for show ip bgp network (#3417)
  README.md
  rcli/linecard.py
  rcli/rexec.py
  rcli/rshell.py
  rcli/utils.py
  show/bgp_frr_v4.py
  show/main.py
  tests/bgp_commands_input/bgp_network_test_vector.py
  tests/conftest.py
  tests/mock_tables/chassis_state_db.json
  tests/remote_cli_test.py
  tests/remote_show_test.py
  tests/show_bgp_network_test.py
Labels: automerge

#3439 Fix kexec_unload failure on secure boot enabled platforms
  scripts/fast-reboot
Labels: Request for 202405 Branch

#3487 [action] [PR:3215] Fix to use IPv6 linklocal address as snmp agent address (#3215)
  config/main.py
  tests/config_snmp_test.py
Labels: automerge

#3475 Add lock to config reload/load_minigraph
  config/main.py
  tests/config_test.py
  tests/flock_test.py
  utilities_common/flock.py
Labels: Request for 202311 Branch, Cherry Pick Conflict_202311, Request for 202405 Branch

#3062 Fix multi-asic behaviour for ecnconfig
  config/main.py
  scripts/ecnconfig
  show/main.py
  tests/ecn_input/ecn_test_vectors.py
  tests/ecn_test.py
  tests/mock_tables/asic0/config_db.json
  tests/mock_tables/asic1/config_db.json
  tests/multi_asic_ecnconfig_test.py
Labels: Chassis

#3494 [action] [PR:3439] Fix kexec_unload failure on secure boot enabled platforms (#3439)
  scripts/fast-reboot
Labels: automerge

#3500 [action] [PR:3484] Add timeout for rexec's get_password (#3484)
  rcli/utils.py
  tests/remote_cli_test.py
Labels: automerge

#3499 [action] [PR:3424] [Bug Fix] Fix disk check test and drops group test (#3424)
  tests/disk_check_test.py
  tests/drops_group_test.py
Labels: automerge

#3498 [action] [PR:3367] [config] no op if Golden Config is invalid (#3367)
  config/main.py
  tests/config_test.py
Labels: automerge

#3497 [action] [PR:3475] Add lock to config reload/load_minigraph (#3475)
  config/main.py
  tests/config_test.py
  tests/flock_test.py
  utilities_common/flock.py
Labels: automerge

#3504 [action] [PR:3169] [config] Check golden config exist early if flag is set (#3169)
  config/main.py
Labels: automerge

#3506 [action] [PR:3367] [config] no op if Golden Config is invalid (#3367)
  config/main.py
  tests/config_test.py
Labels: automerge
