Repository sonic-net/sonic-utilities, pull requests merged in 2024-12, with the labels that each got.

#3646 [show_tech] Filter out a list of commands in generate_dump script which are not applicable to Supervisor
  scripts/generate_dump
Labels: Request for 202405 Branch

#3653 Revert "Speed up route_check script"
  scripts/route_check.py
Labels: Request for 202405 Branch, Cherry Pick Conflict_202405

#3661 [action] [PR:3656] [config]Restrict YANG validation to Golden Config (#3656)
  config/main.py
  tests/config_test.py
Labels: automerge

#3647 Fix save_file command in generate_dump
  scripts/generate_dump
Labels: Request for 202405 Branch

#3663 [action] [PR:3647] Fix save_file command in generate_dump (#3647)
  scripts/generate_dump
Labels: automerge

#3662 [action] [PR:3650] Update gcu_field_operation_validators.conf.json with Arista-7260CX3-D108C10 (#3650)
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: automerge

#3674 [action] [PR:3670] Support empty golden config file for multi-asic (#3670)
  scripts/db_migrator.py
  tests/db_migrator_test.py
Labels: automerge

#3673 [action] [PR:3670] Support empty golden config file for multi-asic (#3670)
  scripts/db_migrator.py
  tests/db_migrator_test.py
Labels: automerge

#3677 [action] [PR:3515] Revert "[wol] Implement wol command line utility" (#3515)
  setup.py
  tests/wol_test.py
  wol/__init__.py
  wol/main.py
Labels: automerge

#3345 [config db] Trim garbage charactor in "DEVICE_METADATA" of config db
  config/main.py
  tests/config_override_test.py
Labels: Request for 202305 Branch, Request for 202311 Branch

#3671 Fixed the issues with sonic-clear queuecounter for egress queue and voq
  scripts/queuestat
Labels: Chassis, p0

#3678 Speed up route_check script
  scripts/route_check.py
Labels: Chassis, Request for 202405 Branch

#3605 Optimize techsupport reducing number of vtysh calls in scale sceario
  scripts/generate_dump
Labels: Request for 202411 Branch

#3686 [action] [PR:3682] Disable routeCheck monit as part of config reload/minigraph stop service and enable it back as part of service start. (#3682)
  config/main.py
  tests/config_test.py
Labels: automerge

#3679 [counterpoll] make the 'eni' command functional only on the DPU
  counterpoll/main.py
  tests/counterpoll_test.py
Labels: Request for 202411 Branch

#3696 [action] [PR:3646] [show_tech] Filter out a list of commands in generate_dump script which are not applicable to Supervisor (#3646)
  scripts/generate_dump
Labels: automerge

#3697 [action] [PR:3671] Fixed the issues with sonic-clear queuecounter for egress queue and voq (#3671)
  scripts/queuestat
Labels: automerge

#3698 Fix monit connection failure when doing routeCheck/contianerCheck monitor enable after config reload
  config/main.py
  tests/config_test.py
Labels: Request for 202405 Branch

#3699 [action] [PR:3698] Fix monit connection failure when doing routeCheck/contianerCheck monitor enable after config reload (#3698)
  config/main.py
  tests/config_test.py
Labels: automerge
