Repository sonic-net/sonic-utilities, pull requests merged in 2024-07, with the labels that each got.

#3331 Remove suppress-fib-pending CLI and make route_check.py check suppress-fib in BGP configuration
  config/main.py
  doc/Command-Reference.md
  scripts/route_check.py
  show/main.py
  tests/route_check_test.py
  tests/suppress_pending_fib_test.py
Labels: Request for 202405 Branch, Cherry Pick Conflict_202405

#3389 [DPB]Fix return code in case of failure
  config/main.py
  tests/config_dpb_test.py
Labels: Request for 202311 Branch, Request for 202405 Branch

#3393 [action] [PR:3389] [DPB]Fix return code in case of failure (#3389)
  config/main.py
  tests/config_dpb_test.py
Labels: automerge

#3416 [action] [PR:3369] [sfputil] Add loopback sub-command for debugging and module diagnosti… (#3369)
  doc/Command-Reference.md
  sfputil/main.py
  tests/sfputil_test.py
Labels: automerge

#3415 [action] [PR:3370] Update TRANSCEIVER_FIRMWARE_INFO table for all targets in sfputil (#3370)
  sfputil/main.py
Labels: automerge

#3376 [action] [PR:3360] [consutil] Fix consule CLI and enhance unittest (#3360)
  consutil/lib.py
  tests/console_mock/dev/ttyACM1
  tests/console_mock/dev/ttyUSB0
  tests/console_test.py
Labels: automerge

#3427 [action] [PR:3353] Don't exit immediately if running a command under alias mode (#3353)
  utilities_common/cli.py
Labels: automerge

#3417 Enable show ip bgp on sup and -n all for show ip bgp network
  README.md
  rcli/linecard.py
  rcli/rexec.py
  rcli/rshell.py
  rcli/utils.py
  show/bgp_frr_v4.py
  show/main.py
  tests/bgp_commands_input/bgp_network_test_vector.py
  tests/conftest.py
  tests/mock_tables/chassis_state_db.json
  tests/remote_cli_test.py
  tests/remote_show_test.py
  tests/show_bgp_network_test.py
Labels: Chassis for 202205 Branch, Request for 202405 Branch

#3385 [SfpUtil] sfp eeprom with option dom is not working on Xcvrs with flat memory
  sfputil/main.py
  tests/sfputil_test.py
Labels: Bug, Request for 202405 Branch

#3434 [action] [PR:3385] [SfpUtil] sfp eeprom with option dom is not working on Xcvrs with flat memory (#3385)
  sfputil/main.py
  tests/sfputil_test.py
Labels: automerge

#3408 IP Assignment Issue
  config/main.py
  tests/vlan_test.py
Labels: Request for 202405 Branch

#3442 [action] [PR:3437] fix show techsupport date issue (#3437)
  scripts/generate_dump
Labels: automerge

#3441 [action] [PR:3437] fix show techsupport date issue (#3437)
  scripts/generate_dump
Labels: automerge

#3440 [action] [PR:3437] fix show techsupport date issue (#3437)
  scripts/generate_dump
Labels: automerge

#3445 [action] [PR:3408] IP Assignment Issue (#3408)
  config/main.py
  tests/vlan_test.py
Labels: automerge

#3447 Change the default behavior of show ip bgp network
  show/bgp_frr_v4.py
  tests/bgp_commands_input/bgp_network_test_vector.py
  tests/remote_show_test.py
  tests/show_bgp_network_test.py
Labels: Chassis for 202205 Branch, Request for 202405 Branch, Cherry Pick Conflict_202405
