Repository sonic-net/sonic-utilities, pull requests merged in 2024-11, with the labels that each got.

#3544 Speed up route_check script
  scripts/route_check.py
Labels: Request for 202405 Branch, Cherry Pick Conflict_202405

#3597 [config] Bypass standard input for reload
  config/main.py
Labels: Request for 202405 Branch

#3598 [action] [PR:3597] [config] Bypass standard input for reload (#3597)
  config/main.py
Labels: automerge

#3602 [action] [PR:3564] Add Unit Test for portstat (#3564)
  tests/portstat_db/on_sup_na/chassis_state_db.json
  tests/portstat_test.py
Labels: automerge

#3601 [action] [PR:3399] Adds logic to get default disk and check disk type (#3399)
  ssdutil/main.py
  tests/mocked_libs/__init__.py
  tests/mocked_libs/blkinfo.py
  tests/mocked_libs/psutil.py
  tests/ssdutil_test.py
Labels: automerge

#3600 [action] [PR:3495] [Nokia] Add J2C+/H3/H4/H5 to GCU validator (#3495)
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: automerge

#3599 [action] [PR:3579] [doc] correct the fec histogram output for show int counters fec-histogram (#3579)
  doc/Command-Reference.md
Labels: automerge

#3603 [action] [PR:3596] Fix for integer overflow of counter value if its too large (#3596)
  utilities_common/portstat.py
Labels: automerge

#3344 [SPM] Add logic to disable the feature before stopping it and enabling it before starting
  sonic_package_manager/manager.py
  tests/sonic_package_manager/test_manager.py
Labels: Request for 202311 Branch, Cherry Pick Conflict_202311, Request for 202405 Branch

#3614 [action] [PR:3595] Refresh dump file modify timestamp before cleanup call (#3595)
  scripts/generate_dump
Labels: automerge

#3612 [Mellanox] Add Mellanox-SN5600-C224O8 to gcu_field.json
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: Request for 202405 Branch, Cherry Pick Conflict_202405

#3624 [action] [PR:3058] Fix multi-asic behaviour for pg-drop (#3058)
  scripts/pg-drop
  show/main.py
  tests/mock_tables/asic1/counters_db.json
  tests/multi_asic_pgdropstat_test.py
Labels: automerge

#3610 Extra delay between running firmware and updating firmware version
  sfputil/main.py
Labels: Request for 202405 Branch

#3631 [Mellanox] Update the save_file command in generate_dump to handle folders
  scripts/generate_dump
Labels: Bug, Platform: Mellanox, Request for 202405 Branch

#3641 [action] [PR:3060] Fix multi-asic behaviour for watermarkstat (#3060)
  clear/main.py
  scripts/watermarkstat
  show/main.py
  tests/mock_tables/asic0/counters_db.json
  tests/mock_tables/asic1/counters_db.json
  tests/mock_tables/dbconnector.py
  tests/multi_asic_pgdropstat_test.py
  tests/multi_asic_queue_counter_test.py
  tests/multi_asic_watermarkstat_test.py
  tests/watermarkstat_test.py
  tests/wm_input/wm_test_vectors.py
Labels: automerge

#3640 [action] [PR:3513] Upgrade pyroute2 and improve cli response time (#3513)
  setup.py
  utilities_common/multi_asic.py
Labels: automerge

#3639 [action] [PR:3631] [Mellanox] Update the save_file command in generate_dump to handle folders (#3631)
  scripts/generate_dump
Labels: automerge

#3638 [action] [PR:3418] Add sfputil power enable/disable command (#3418)
  sfputil/main.py
  tests/sfputil_test.py
Labels: automerge

#3637 [action] [PR:3059] Fix multi-asic behaviour for dropstat (#3059)
  scripts/dropstat
  show/dropcounters.py
  tests/mock_tables/asic1/asic_db.json
  tests/multi_asic_dropstat_test.py
  tests/single_asic_dropstat_test.py
Labels: automerge

#3636 [action] [PR:3062] Fix multi-asic behaviour for ecnconfig (#3062)
  config/main.py
  scripts/ecnconfig
  show/main.py
  tests/ecn_input/ecn_test_vectors.py
  tests/ecn_test.py
  tests/mock_tables/asic0/config_db.json
  tests/mock_tables/asic1/config_db.json
  tests/multi_asic_ecnconfig_test.py
Labels: automerge

#3635 [action] [PR:3554] Enhance multi-asic support for queuestat (#3554)
  scripts/queuestat
  tests/multi_asic_queue_counter_test.py
  tests/queue_counter_test.py
Labels: automerge

#3634 [action] [PR:3610] Extra delay between running firmware and updating firmware version (#3610)
  sfputil/main.py
Labels: automerge

#3633 [action] [PR:3585] Consolidate the get running config way. (#3585)
  generic_config_updater/change_applier.py
  generic_config_updater/gu_common.py
  tests/generic_config_updater/change_applier_test.py
  tests/generic_config_updater/gcu_feature_patch_application_test.py
  tests/generic_config_updater/multiasic_change_applier_test.py
Labels: automerge
