Repository sonic-net/sonic-utilities, pull requests merged in 2025-03, with the labels that each got.

#3774 [subintf]Fix the interface name length validation for subinterface
  config/main.py
  tests/subintf_test.py
Labels: Request for 202411 Branch

#3790 [action] [PR:3781] Add namespace support for show interface neighbor expected
  doc/Command-Reference.md
  show/interfaces/__init__.py
Labels: automerge

#3793 revert YANG check in db_migrator
  scripts/config_validator.py
  scripts/db_migrator.py
  setup.py
Labels: Request for 202411 Branch

#3792 enable pfcwd for backplane ports
  pfcwd/main.py
Labels: Request for 202411 Branch, Request for msft-202405 Branch

#3796 [action] [PR:3792] enable pfcwd for backplane ports
  pfcwd/main.py
Labels: automerge

#3795 Fixes `show interface transceiver info Ethernet0` command failure for CMIS SFP.
  scripts/sfpshow
  utilities_common/sfp_helper.py
Labels: Bug

#3769 Fix the switch level Voq counter to use switch_id Oid instead of counter name for PACKET_INTEGRITY counter
  scripts/dropstat
  tests/mock_tables/counters_db.json
Labels: p0, Request for 202405 Branch, Request for 202411 Branch

#3797 [Techsupport]Add show route-map command to frr dumps in techsupport
  scripts/generate_dump
Labels: Request for 202411 Branch, Approved for 202411 Branch

#3807 [action] [PR:3668] [GCU] Add data acl table and rule check
  generic_config_updater/gu_common.py
  tests/generic_config_updater/field_operation_validator_test.py
Labels: automerge

#3806 [action] [PR:3704] [db_migrator] Migrate tunnel table
  scripts/db_migrator.py
  tests/db_migrator_input/appl_db/tunnel_table_expected.json
  tests/db_migrator_input/appl_db/tunnel_table_input.json
  tests/db_migrator_input/config_db/tunnel_table_input.json
  tests/db_migrator_test.py
Labels: automerge

#3805 Add scope to field validator.[redo PR: 3675]
  generic_config_updater/field_operation_validators.py
  generic_config_updater/gu_common.py
  tests/generic_config_updater/field_operation_validator_test.py
Labels: Request for 202411 Branch, Request for msft-202405 Branch

#3753 Fixed syslog error "ERR python3:- validateNamespace: Initialize global.." for sfpshow
  scripts/sfpshow
  tests/sfp_test.py
Labels: Request for 202411 Branch, Request for msft-202405 Branch

#3819 feat: add namespace support for show interfaces counters fec-histogram
  show/interfaces/__init__.py
Labels: Request for msft-202405 Branch
