Repository sonic-net/sonic-utilities, pull requests merged in 2025-05, with the labels that each got.

#3865 [chassis][show_tech]Fix show queue counters to only run on host
  scripts/generate_dump
Labels: Request for msft-202405 Branch, Approved for msft-202405 Branch

#3844 Transceiver CLI changes to support DOM and STATUS table related changes
  scripts/sfpshow
  sfputil/main.py
  tests/mock_platform_sfputil/mock_platform_sfputil.py
  tests/mock_tables/state_db.json
  tests/sfp_test.py
  tests/sfputil_test.py
  utilities_common/platform_sfputil_helper.py
  utilities_common/sfp_helper.py
Labels: Request for msft-202412 Branch

#3830 [trim]: Add Packet Trimming CLI
  config/main.py
  config/plugins/sonic-trimming.py
  doc/Command-Reference.md
  scripts/mmuconfig
  scripts/portstat
  scripts/queuestat
  show/interfaces/__init__.py
  show/main.py
  show/plugins/sonic-trimming.py
  tests/buffer_input/buffer_test_vectors.py
  tests/mmuconfig_input/mmuconfig_test_vectors.py
  tests/mmuconfig_test.py
  tests/mock_tables/asic0/counters_db.json
  tests/mock_tables/config_db.json
  tests/mock_tables/counters_db.json
  tests/portstat_input/assert_show_output.py
  tests/portstat_test.py
  tests/queuestat_input/assert_show_output.py
  tests/queuestat_test.py
  tests/trimming_input/assert_show_output.py
  tests/trimming_input/mock_config/empty.json
  tests/trimming_input/mock_config/partial.json
  tests/trimming_input/mock_config/queue_dynamic.json
  tests/trimming_input/mock_config/queue_static.json
  tests/trimming_input/mock_state/all.json
  tests/trimming_input/mock_state/no_capabilities.json
  tests/trimming_input/mock_state/not_supported.json
  tests/trimming_input/mock_state/queue_dynamic.json
  tests/trimming_input/mock_state/queue_static.json
  tests/trimming_test.py
  tests/wred_queue_counter_test.py
  utilities_common/portstat.py
  utilities_common/switch_trimming.py
Labels: Request for msft-202412 Branch

#3782 Fix pg-drop cmd issue on multi-asic
  scripts/pg-drop
  tests/multi_asic_pgdropstat_test.py
Labels: Request for 202411 Branch, Request for msft-202405 Branch

#3871 [Mellanox] Add GCU Support for SKU Mellanox-SN4280-O8C80
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: Platform: Mellanox

#3880 skip pfcwd if disabled in golden_config
  config/main.py
Labels: Request for msft-202412 Branch

#3892 [action] [PR:3885] feat: support namespace arg for show bfd commands
  .gitignore
  doc/Command-Reference.md
  show/main.py
  tests/bfd_input/bfd_masic_test_vectors.py
  tests/mock_tables/asic0/state_db.json
  tests/multi_asic_show_bfd_test.py
Labels: automerge

#3896 add TH5-512 hwsku into gcu support list
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412
