Repository sonic-net/sonic-utilities, pull requests merged in 2025-06, with the labels that each got.

#3905 [action] [PR:3866] Add CLI show commands to view bgp network, neighbors and summary on per-vrf basis
  doc/Command-Reference.md
  show/bgp_frr_v4.py
  show/bgp_frr_v6.py
  tests/bgp_commands_input/bgp_neighbor_test_vector.py
  tests/bgp_commands_input/bgp_network_test_vector.py
  tests/bgp_commands_test.py
  tests/conftest.py
  tests/mock_tables/ipv4_bgp_summary_vrf.json
  tests/mock_tables/ipv6_bgp_summary_vrf.json
  tests/show_bgp_neighbor_test.py
  tests/show_bgp_network_test.py
  utilities_common/bgp_util.py
Labels: automerge

#3900 [Smartswitch][reboot] Addition of pre shutdown and post startup function calls
  scripts/reboot_smartswitch_helper
  tests/test_module.py
  utilities_common/module.py
Labels: Request for 202505 Branch

#3864 [db_migrator] Add version_202411_02
  scripts/db_migrator.py
  tests/db_migrator_test.py
Labels: Request for 202505 Branch

#3902 [intfstat] Align output format between cached/non-cached scenarios
  scripts/intfstat
  tests/intfstat_test.py
  tests/mock_tables/counters_db.json
Labels: Request for 202505 Branch

#3903 [Mellanox] Collect sai.xml to sysdump
  scripts/generate_dump
Labels: Platform: Mellanox, Request for 202505 Branch

#3913 [action] [PR:3902] [intfstat] Align output format between cached/non-cached scenarios
  scripts/intfstat
  tests/intfstat_test.py
  tests/mock_tables/counters_db.json
Labels: automerge

#3912 [action] [PR:3864] [db_migrator] Add version_202411_02
  scripts/db_migrator.py
  tests/db_migrator_test.py
Labels: automerge

#3915 [action] [PR:3891] [build] Update Azure pipeline to use Ubuntu 24.04 image
  azure-pipelines.yml
Labels: automerge

#3921 [action] [PR:3918] Support reboot cause: Kernel Panic - Out of memory
  scripts/reboot
Labels: automerge

#3919 Skip checking offload flags for static routes/sids in route check and add check_sids
  scripts/route_check.py
  tests/route_check_test_data.py
Labels: Request for msft-202412 Branch

#3927 [action] [PR:3895] [multi-asic] Fix the 'config reload' flow in case when multiple golden_config.json files provided
  config/main.py
  tests/config_test.py
Labels: automerge

#3934 [action] [PR:3910] Improved GCU's field validation logic for the WRED_PROFILE table
  generic_config_updater/field_operation_validators.py
  generic_config_updater/gcu_field_operation_validators.conf.json
  tests/generic_config_updater/field_operation_validator_test.py
Labels: automerge

#3935 [action] [PR:3802] [Arista] Add Arista-7050CX3-32S-C28S4 to generic_config_updater
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: automerge

#3939 [action] [PR:3929] Switch to using chrony instead of ntpd : gcu - services_validator.py
  generic_config_updater/services_validator.py
  tests/generic_config_updater/service_validator_test.py
Labels: automerge

#3814 YANG: remove uses clause handling, now part of sonic-yang-mgmt
  sonic_cli_gen/yang_parser.py
  tests/cli_autogen_input/yang_parser_test/assert_dictionaries.py
Labels: yang, Request for 202505 Branch
