Repository sonic-net/sonic-utilities, pull requests merged in 2025-01, with the labels that each got.

#3703 Fixed show interface counters on supervisor for packet chassis
  scripts/portstat
  utilities_common/portstat.py
Labels: Request for 202405 Branch, Request for 202411 Branch

#3680 Delete TRSNCEIVER tables while config reload
  config/main.py
Labels: Request for 202405 Branch, Request for 202411 Branch

#3658 [Mellanox] Add Mellanox-SN5610N-C256S2, Mellanox-SN5610N-C224O8 to GCU validators
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: Request for 202411 Branch

#3718 [action] [PR:3658] [Mellanox] Add Mellanox-SN5610N-C256S2, Mellanox-SN5610N-C224O8 to GCU validators
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: automerge

#3714 [Arista] Add 7060X6-64 to GCU Validator
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: Request for 202411 Branch

#3719 [action] [PR:3714] [Arista] Add 7060X6-64 to GCU Validator
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: automerge

#3716 [yang] Enforce yang full support in full config command
  config/main.py
  tests/config_override_input/new_feature_config.json
  tests/config_override_test.py
  tests/config_test.py
Labels: Request for 202411 Branch

#3693 [ssdhealth] Check for default device before falling back to discovery
  show/platform.py
  tests/show_platform_test.py
  tests/show_test.py
Labels: Request for 202411 Branch

#3715 Remove debug dump import by default
  utilities_common/helper.py
Labels: Request for 202411 Branch

#3710 [config] Exit with non-zero when qos reload fail
  config/main.py
  doc/Command-Reference.md
  tests/config_test.py
Labels: Request for 202411 Branch, Approved for 202411 Branch

#3728 [action] [PR:3715] Remove debug dump import by default
  utilities_common/helper.py
Labels: automerge

#3727 [action] [PR:3710] [config] Exit with non-zero when qos reload fail
  config/main.py
  doc/Command-Reference.md
  tests/config_test.py
Labels: automerge

#3726 [action] [PR:3680] Delete TRSNCEIVER tables while config reload
  config/main.py
Labels: automerge

#3725 [action] [PR:3693] [ssdhealth] Check for default device before falling back to discovery
  show/platform.py
  tests/show_platform_test.py
  tests/show_test.py
Labels: automerge

#3734 Fix show interface counters for Chassis Packet Supervisor
  scripts/portstat
  tests/portstat_db/on_sup_packet_chassis/chassis_state_db.json
  tests/portstat_db/on_sup_packet_chassis/counters_db.json
  tests/portstat_test.py
  utilities_common/portstat.py
Labels: Request for msft-202405 Branch

#3743 Fix ssdhealth failure on multi-asic VS platform
  show/platform.py
Labels: Request for 202411 Branch, Approved for 202411 Branch

#3744 [action] [PR:3743] Fix ssdhealth failure on multi-asic VS platform
  show/platform.py
Labels: automerge
