Repository sonic-net/sonic-utilities, pull requests merged in 2025-04, with the labels that each got.

#3802 [Arista] Add Arista-7050CX3-32S-C28S4 to generic_config_updater
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: Request for 202405 Branch

#3851 [action] [PR:3802] [Arista] Add Arista-7050CX3-32S-C28S4 to generic_config_updater
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: automerge

#3849 [action] [PR:3753] Fixed syslog error "ERR python3:- validateNamespace: Initialize global.." for sfpshow
  scripts/sfpshow
  tests/sfp_test.py
Labels: automerge

#3841 [SRv6] add support for SRv6 counters
  clear/main.py
  counterpoll/main.py
  scripts/srv6stat
  setup.py
  show/main.py
  show/srv6.py
  tests/clear_test.py
  tests/counterpoll_test.py
  tests/mock_tables/config_db.json
  tests/mock_tables/counters_db.json
  tests/show_test.py
  tests/srv6stat_test.py
  utilities_common/srv6stat.py
Labels: Request for msft-202412 Branch
