Repository sonic-net/sonic-utilities, pull requests merged in 2025-02, with the labels that each got.

#3748 [action] [PR:3345] [config db] Trim garbage charactor in "DEVICE_METADATA" of config db
  config/main.py
  tests/config_override_test.py
Labels: automerge

#3749 [action] [PR:3721] [show][interface] Add changes for show interface errors command
  show/interfaces/__init__.py
  tests/interfaces_test.py
  tests/mock_tables/state_db.json
Labels: automerge

#3723 Fix call for spanning-tree commands in dump script
  scripts/generate_dump
Labels: Request for 202411 Branch

#2807 sonic-utilities: WRED stats feature changes on sonic-utilities
  clear/main.py
  counterpoll/main.py
  doc/Command-Reference.md
  scripts/wredstat
  setup.py
  show/main.py
  tests/counterpoll_input/config_db.json
  tests/counterpoll_test.py
  tests/mock_tables/config_db.json
  tests/mock_tables/counters_db.json
  tests/mock_tables/state_db.json
  tests/portstat_test.py
  tests/wred_queue_counter_test.py
  utilities_common/portstat.py
Labels: Request for 202411 Branch

#3745 [show_techsupport][pstore] Archive /var/lib/systemd/pstore info to show techsupport
  scripts/generate_dump
Labels: Request for 202405 Branch, Cherry Pick Conflict_202405, Request for 202411 Branch, Cherry Pick Conflict_202411

#3742 [Mellanox] Add new SN5640 platform and HwSKU
  generic_config_updater/field_operation_validators.py
  generic_config_updater/gcu_field_operation_validators.conf.json
  tests/generic_config_updater/field_operation_validator_test.py
Labels: Request for msft-202412 Branch

#3752 [action] [PR:3723] Fix call for spanning-tree commands in dump script
  scripts/generate_dump
Labels: automerge

#3170 Optimize lag_keepalive by crafting the LACPDU packet ourselves
  scripts/fast-reboot
  scripts/lag_keepalive.py
Labels: Request for 202305 Branch, Request for 202311 Branch

#3708 [QOS] Skip showing unnecessary warning message
  config/main.py
  tests/config_test.py
Labels: Request for 202405 Branch, Request for 202411 Branch

#3762 [action] [PR:3708] [QOS] Skip showing unnecessary warning message
  config/main.py
  tests/config_test.py
Labels: automerge

#3577 [FC] remove FC delay field
  counterpoll/main.py
  scripts/db_migrator.py
  scripts/fast-reboot
  tests/counterpoll_test.py
  tests/db_migrator_input/config_db/cross_branch_upgrade_to_4_0_3_expected.json
Labels: Request for 202411 Branch

#3780 [action] [PR:3763] Fix `vnet_route_check` for active and inactive routes, add `--all` option
  scripts/vnet_route_check.py
  tests/vnet_route_check_test.py
Labels: automerge
