Repository sonic-net/sonic-utilities, pull requests merged in 2025-08, with the labels that each got.

#3938 [sfputil debug] Fix issue: do not check output status when CMIS version is lower than 5.0
  sfputil/debug.py
  tests/sfputil_test.py
Labels: Request for msft-202412 Branch, Request for 202505 Branch, Cherry Pick Conflict_202505

#4011 [action] [PR:3998] [SPM] Rename the variable tag to docker-image-reference
  sonic_package_manager/database.py
  sonic_package_manager/service_creator/creator.py
  sonic_package_manager/source.py
  tests/sonic_package_manager/conftest.py
  tests/sonic_package_manager/test_database.py
  tests/sonic_package_manager/test_manager.py
Labels: automerge

#3984 Fix for #23205 [Smartswitch] Issues caused due to introduction of the chassisd/sonic-utiltiies changes for consecutive admin state changes
  show/chassis_modules.py
Labels: Request for 202505 Branch

#3959 [Mellanox][Smartswitch]Added dpu status output
  scripts/generate_dump
Labels: Platform: Mellanox, Request for 202505 Branch

#4014 [action] [PR:3959] [Mellanox][Smartswitch]Added dpu status output
  scripts/generate_dump
Labels: automerge

#4018 [action] [PR:3911] [sfputil] Use host lane mask as part of rx-output enable/disable
  sfputil/debug.py
  tests/sfputil_test.py
  utilities_common/platform_sfputil_helper.py
Labels: automerge

#4017 [action] [PR:4010] sfputil and sfpshow eeprom and DOM CLI enhancement to display data for all CMIS transceivers
  scripts/sfpshow
  sfputil/main.py
  tests/mock_tables/state_db.json
  tests/sfp_test.py
  tests/sfputil_test.py
  utilities_common/sfp_helper.py
Labels: automerge

#3906 Added json support intfutil
  scripts/intfutil
Labels: Request for msft-202412 Branch, Request for 202505 Branch

#4023 [action] [PR:3906] Added json support intfutil
  scripts/intfutil
Labels: automerge

#3875 Pr json support queue and priority-group watermark and persistent-watermark
  scripts/watermarkstat
  show/main.py
  tests/watermarkstat_test.py
  tests/wm_input/wm_test_vectors.py
Labels: Request for msft-202412 Branch

#4026 [action] [PR:4024] Revert "[SPM] Rename the variable tag to docker-image-reference"
  sonic_package_manager/database.py
  sonic_package_manager/service_creator/creator.py
  sonic_package_manager/source.py
  tests/sonic_package_manager/conftest.py
  tests/sonic_package_manager/test_database.py
  tests/sonic_package_manager/test_manager.py
Labels: automerge

#3993 [trim]: Add Packet Trimming Drop Counters CLI
  clear/main.py
  counterpoll/main.py
  doc/Command-Reference.md
  scripts/queuestat
  scripts/switchstat
  setup.py
  show/main.py
  show/switch.py
  tests/clear_test.py
  tests/counterpoll_test.py
  tests/mock_tables/asic0/counters_db.json
  tests/mock_tables/config_db.json
  tests/mock_tables/counters_db.json
  tests/portstat_db/counters_db.json
  tests/portstat_input/assert_show_output.py
  tests/portstat_test.py
  tests/queuestat_input/assert_show_output.py
  tests/show_test.py
  tests/switchstat_input/common_output.py
  tests/switchstat_input/mock_counters/all.json
  tests/switchstat_input/mock_counters/empty.json
  tests/switchstat_input/mock_counters/no_counters.json
  tests/switchstat_input/mock_counters/no_map.json
  tests/switchstat_input/mock_counters/partial.json
  tests/switchstat_input/mock_counters/updated.json
  tests/switchstat_input/mock_counters/updated_tag.json
  tests/switchstat_input/multi_asic_output.py
  tests/switchstat_input/single_asic_output.py
  tests/switchstat_test.py
  tests/synchronous_mode_test.py
  utilities_common/netstat.py
  utilities_common/portstat.py
  utilities_common/switchstat.py
Labels: Feature Request :rocket:, Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 Branch, Cherry Pick Conflict_202505

#3874 Pr json support for show platform temperature
  scripts/tempershow
  show/platform.py
  tests/show_platform_test.py
Labels: Request for msft-202412 Branch

#4035 [action] [PR:3788] Switchport mode update for 'show interfaces status'
  scripts/intfutil
  tests/vlan_test.py
Labels: automerge

#4002 [nvidia-bluefield] Add CLI for packet-drop and config-record
  config/plugins/nvidia_bluefield.py
  tests/config_nvidia_bluefield_test.py
Labels: Platform: Mellanox, Request for msft-202506 Branch

#4043 [action] [PR:4041] [smartswitch] Update get_gnmi_port() based on smartswitch config updates
  scripts/reboot_smartswitch_helper
Labels: automerge

#4038 Add Arista 7800 platforms to GCU validator
  generic_config_updater/gcu_field_operation_validators.conf.json
Labels: Request for msft-202405 Branch, Cherry Pick Conflict_msft-202405, Request for 202505 Branch, Cherry Pick Conflict_202505
